### ISSUE TITLE
`TopologyFaultToleranceTest.shouldDetectTopologyChanges` is flaky

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10234]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once (as of 2022/08/31)
- Does it block your work? No
- Do we suspect that it is a real failure? Not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<pre>
Caused by: java.lang.AssertionError: Expected partition <3> to have a healthy leader, but it only has the following brokers: <[BrokerInfoImpl{nodeId=0, host='0.0.0.0', port=2527, version=8.1.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=LEADER, health=HEALTHY}, PartitionInfoImpl{partitionId=2, role=LEADER, health=HEALTHY}, PartitionInfoImpl{partitionId=3, role=FOLLOWER, health=HEALTHY}]}, BrokerInfoImpl{nodeId=1, host='0.0.0.0', port=2531, version=8.1.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER, health=HEALTHY}, PartitionInfoImpl{partitionId=2, role=FOLLOWER, health=HEALTHY}, PartitionInfoImpl{partitionId=3, role=FOLLOWER, health=HEALTHY}]}, BrokerInfoImpl{nodeId=2, host='0.0.0.0', port=2535, version=8.1.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER, health=HEALTHY}, PartitionInfoImpl{partitionId=2, role=FOLLOWER, health=HEALTHY}, PartitionInfoImpl{partitionId=3, role=FOLLOWER, health=HEALTHY}]}]>
</pre>

**Logs**

[Test results for Integration Tests.zip](https://github.com/camunda/zeebe/files/9461510/Test.results.for.Integration.Tests.zip)

**Comment by npepinpe** [comment]
To recap: the test starts a cluster of 3 brokers, 1 gateway. For each broker, sequentially, it:

- Disconnects the broker by stopping the messaging service (such that it cannot receive or talk to other nodes), without waiting for topology changes.
- Waits until the broker is not part of the topology anymore (by polling the gateway regularly). Polling is up to 30 seconds.
- Reconnects the broker by starting its messaging service again (such that it receives requests and can reply to them), without waiting for topology changes.
- Waits until the topology is complete: there are 3 brokers in the cluster, each partition has a unique and healthy leader, and each partition has 2 followers. Polling is up to 15 seconds, after which it times out.

What failed above is that partition 3 had no leader (you can see from the assertion that, indeed, all brokers are followers for partition 3).

A naive solution would be to increase the timer of the final assertion to bring it in line with the one where we disconnect the node. It's worth trying it out now, as we don't have logs (at the moment anyway).

At the same time, we can look at the possible sources of flakiness, and try to use our :brain: :

The failed assertion is waiting for a healthy leader for all partitions, but partition 3 only has followers. This could indicate two things:

1. There is a bug, and no leader is ever elected (very bad)
2. There is a bug, and it takes longer for a leader to be elected (bad, but not as bad)
3. There is no bug, and there is pressure on the system leading to a slow election.

Let's assume 3 for now, as we have no indicators of 1 & 2 without any logs.

The current election timer is the priority timer, and we have 3 partitions. This means we have the following distribution, where L also denotes the preferred leader for a given partition:

```
P\N|    N 0|    N 1|    N 2
P 1|    L  |    F  |    F  
P 2|    F  |    L  |    F  
P 3|    F  |    F  |    L  
```

Secondary priorities usually alternate, but in this case we only have 3 partitions, so the second preferred leader for partition 1 is node 1, for partition 2 is node 2, and for partition 3 is node 0, or from left to right in order of preferred leadership:

```
P_1 -> N_0, N_1, N_2
P_2 -> N_1, N_2, N_0
P_3 -> N_2, N_0, N_1
```

The default election timeout is 2.5 seconds. This means after 2.5 seconds, nodes should start an election. As there are always 2 nodes present, and the secondary leader is always present, we expect up to 2 election time outs to occur, since the target priority has to be lowered by at least one tick. So we expect at least 5 seconds to elapse between elections. Note that this 5 seconds includes both the time we wait for the disconnected node to be removed from the topology, and also the time we wait for the topology to be complete.

We've seen in the past GC pauses of up to 10 seconds, so I suppose it could be that 15 seconds is not high enough. It seems unlikely, and I unfortunately don't have proof (an automated GC log parser for very high pauses to log warnings would be amazing if anyone is bored), so I'm a little wary of just blaming that. Maybe we can dig a little more.

So let's take a look at the logs. The logs we have are for the successful run, but that doesn't mean we can't get any info out of them.

12:16:38.309 - the cluster is fully up and ready.
12:16:40.142 - we disconnect 0
12:16:40.161 - 2 fails to probe 0
12:16:40.315 - gateway fails to probe 0
12:16:40.317 - 1 fails to synchronize with 0
12:16:40.654 - REACHABILITY_CHANGED event fired for 0 on node 1 (and around the same time, on other nodes). You can see node 1, 2, and gateway, are requesting each other to probe node 0.
12:16:41.803 - 1 removes 0 from the cluster. The other nodes follow suit within ~200ms.
12:16:41.804 - An election is triggered by node 2 for partition 1. Node 1 transitions to candidate. This causes the `ZeebePartition` to transition from follower to follower - unclear how useful that is, but hopefully we handle this case gracefully.
12:16:41.820 - Node 2 voted for 1, so node 1 transitions to leader.
12:16:42.082 - Node 0 is reconnected.
12:16:44.766 - Node 1 is disconnected.

We can see it took roughly 6 seconds to do a full round trip - disconnecting 0, waiting for it to be removed, reconnecting it, waiting for the topology to be complete. Scanning the rest of the log, this is fairly average, and well below 15 seconds. That said, long GC pauses wouldn't necessarily be deterministic, so it doesn't invalidate that hypothesis.

My proposal: I'll open a PR which add more logging so we can more easily determine how long each loop takes (do-able now, but a little annoying), and increase the timeout to 30 seconds. I'll mark the issue as stale, and we can close it in 2 weeks if it doesn't re-occur. If it does, we can work on this and/or reopen, and we will have more logs (as, remember, we don't have the logs for the failed runs here).

**Comment by megglos** [comment]
closing as stale
