### ISSUE TITLE
DMN tables deployment error via Zeebe client

### ISSUE THREAD

**Issue by RazvanStanciu95** [camunda/zeebe#10298]
Hi,

I am trying to deploy these 2 DMN tables, see them created in Camunda Modeler cloud:

![table_1](https://user-images.githubusercontent.com/11362717/189083491-a67903d7-500b-49f9-afce-7bd8a90ac0ac.png)

![table_2](https://user-images.githubusercontent.com/11362717/189083528-b0689e61-bfb7-478c-bb17-e5205a9b017c.png)

I am facing these errors and I am not sure why given that the table works when deploying the instance via the interface.

```
Expected to deploy new resources, but encountered the following errors:
FEEL expression: failed to parse expression '': Expected (ifOp | forOp | quantifiedOp | disjunction):1:1, found ""
FEEL unary-tests: failed to parse expression '= SUCCESS': Expected (negation | positiveUnaryTests | anyInput):1:1, found "= SUCCESS"
FEEL expression: failed to parse expression '': Expected (ifOp | forOp | quantifiedOp | disjunction):1:1, found ""
FEEL unary-tests: failed to parse expression '= payment.DestinationSortCode': Expected (negation | positiveUnaryTests | anyInput):1:1, found "= payment."
```

Any tips on how to update the tables to solve the above? I am quite new to Camunda so apologies in advance!

**Comment by saig0** [comment]
@RazvanStanciu95 from the error message, I see two issues: 

- the [input expressions](https://docs.camunda.io/docs/components/modeler/dmn/decision-table-input/#input-expression) are not set
  - set a [FEEL expression](https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-expressions-introduction/), for example, to access a variable 
- the [input entries](https://docs.camunda.io/docs/components/modeler/dmn/decision-table-rule/#input-entry) starts with an equal sign `=` 
  - expressions in DMN don't have a prefix like in BPMN
  - an input entry should be a [FEEL unary-tests expression](https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-expressions-introduction/)  
  - to compare the input with a value, you don't need `=`. Have a look at the [docs](https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-unary-tests/#comparison)

Additionally, keep in mind that string values must be enclosed in double quotes (e.g. `"SUCCESS"`). Otherwise, it would be interpreted as a variable access.

**Comment by RazvanStanciu95** [comment]
Fixed, thank you for your time.
