### ISSUE TITLE
Support user task candidate users

### ISSUE THREAD

**Issue by lzgabel** [camunda/zeebe#10346]
**Is your feature request related to a problem? Please describe.**
As a user I would like to specify task  candidate-users for user tasks.

There is a scenario to set the specified candidate group (such as department A, or role B), and specify candidate users (these users are not necessarily in department A, or role B).

**Describe the solution you'd like**
A user should be able to define the user task  candidate-users in BPMN, as custom extension elements.

The attribute should allow to set static values, i.e. the user id, and expressions to compute the values during process execution.

**Additional context**
See Camunda Platform docs about this feature https://docs.camunda.org/manual/7.16/reference/bpmn20/tasks/user-task/#candidate-users.

**Issue tracking**
--
* [ ] https://github.com/camunda/camunda-modeler/issues/3151

**Comment by korthout** [comment]
Thanks for describing the feature and your use case @lzgabel

Note that there is a workaround for that. Because `candidateGroups` just needs to be a list of strings, we can put anything in those strings, even JSON. That allows us to create structures to differentiate between the candidate groups types (e.g. department, role or user).

So your specific use case could be created using `candidateGroups` only: 
```json
"candidateGroups": [
    "{ \"type\": \"department\", \"name\": \"A\" }",
    "{ \"type\": \"role\", \"name\": \"B\" }",
    "{ \"type\": \"user\", \"name\": \"C\" }"
]
```

I do acknowledge that using candidate groups to replace candidate users doesn’t feel semantically correct. So we should consider this feature request nevertheless.

//cc @felix-mueller

**Comment by lzgabel** [comment]
> Thanks for raising this topic. From my perspective we should support candidate users as well for User Tasks.


Hi @felix-mueller.  
Thanks for your confirmation.  ❤️ 

> @lzgabel is this a topic where you would be interested in contributing?

Yes, I'd love to. I will submit a PR soon. 🤝
