### ISSUE TITLE
Add signal events support in the bpmn model api

### ISSUE THREAD

**Issue by skayliu** [camunda/zeebe#10530]
**Is your feature request related to a problem? Please describe.**

As a user, i'd like to there is apis support for signal event modelling. And finally we can run signal events in C8.

**Describe the solution you'd like**

First thing first, we should add signal event support in the bpmn model api of C8

**Describe alternatives you've considered**

None

**Additional context**

Align the capabilities with C7.
[Events](https://docs.camunda.org/manual/7.17/reference/bpmn20/)
[Signal Events](https://docs.camunda.org/manual/7.17/reference/bpmn20/events/signal-events/)
[BPMN2.0](https://www.omg.org/spec/BPMN/2.0.2/PDF)

**Comment by skayliu** [comment]
Hi,@saig0, I'd love to make a PR for this, may i ?

**Comment by saig0** [comment]
@skayliu awesome. :tada: I'm looking forward to your PR. :rocket: 

If you want to participate in the [Hacktoberfest](https://camunda.com/hacktoberfest2022/) then you should wait until the 1st of October. 

---

Please be aware that the implementation of the execution logic of signal events is not defined yet. Signal events may end up similar to message events but distributed to all partitions. I could imagine that a signal event has only a name but no correlation key or a time-to-live (TTL).

So, the implementation effort could be very high and include a lot of communication to define the expected behavior/feature first.

**Comment by skayliu** [comment]
Yes, I totally understand, It's more complex then message events, so i want to support the bpmn model api first.

**Comment by skayliu** [comment]
@saig0, Also, the bpmn model api for conditional events is almost done.

**Comment by saig0** [comment]
@skayliu great. :+1: 

We just need to make sure to not expose or allow features in the Model API that are not supported yet (or in the near future).
