### ISSUE TITLE
[question] Open the zeebe project using the vscode editor and report the import problem

### ISSUE THREAD

**Issue by PrettySea** [camunda/zeebe#10644]
Open the zeebe project using the vscode editor and report the import problem
io.camunda.zeebe.gateway cannot be resolved, what`s the reason?

![image](https://user-images.githubusercontent.com/47853044/194696032-6b0fd728-64a9-4d2b-95c3-35db6a88bdb4.png)

**Comment by Zelldon** [comment]
You have to built the project first, via maven. This will generate the classes and make them available to you.

**Comment by PrettySea** [comment]
@Zelldon maven is now installed and GatewayGrpc and GatewayOuterClass are generated, but cannot Resolve
![image](https://user-images.githubusercontent.com/47853044/194697106-b5cf5441-6dba-407e-a69f-7130aab27c86.png)

**Comment by megglos** [comment]
@PrettySea please excuse the late response but we are unfortunately not proficient with vscode to effectively help you root-cause this :/

Assuming you performed a full successful maven build `mvn clean install -DskipTests -DskipChecks` on the root of the repo, confirming your java & maven setup is fine, it all comes down to your vscode setup itself being the issue here.

I hope though you may managed to overcome that issue in the meantime and would close this issue as we don't see us in a position to be of much help here.

If you encounter any underlying issues though, e.g. with the maven build itself or such, please reach out again. :)
