### ISSUE TITLE
Message column families are not cleaned up and can cause outages

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10643]
**Describe the bug**

I have now proof that the message column families in our mixed benchmarks are not cleaned up 
![messages](https://user-images.githubusercontent.com/2758593/194691366-602c773f-dcbd-404d-8c6b-4d0d215662f6.png)

These are the cause of https://github.com/camunda/zeebe/issues/10552#issuecomment-1272235756.

There is no way to clean up these column families, which is why I mark this bug as severity/critical. The state will grow at some point to a size, which will be no longer handlable by raft either.

**To Reproduce**

Run a mixed benchmark. You can run a benchmark with this branch [to get better insights](https://github.com/camunda/zeebe/commits/zell-investigate-mixed).

Especially https://github.com/camunda/zeebe/commit/547bf9c845b4b26ea3d4ceb375131f3d5b5c8c21 is interesting for the column family key count and https://github.com/camunda/zeebe/commit/8c134305f860703891010ad72c9c6332f950e0e2 for rocksdb statistics.

**Root Cause**

When appending a `expire` message command, the entire message including its variables is added to the appended command. And the commands are batched in a (default `maxMessageSize` of) 4MB buffer. 

https://github.com/camunda/zeebe/blob/720656b69cd28f5b4d14d516cad6f52a250c4107/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java#L37-L54

Depending on the size of the variables, a "big" chunk of memory will be already occupied for a single expire message command inside the buffer. Once the buffer is reached or exceeded, the `MessageTimeToLiveChecker` will stop collecting expired messages. 

In the mixed benchmark 100 messages per second are published to Zeebe. Each message is published with variables having a size of ~13kb (see `big_variables.json` - the actual json file size is ~46kb). Since the `MessageTimeToLiveChecker` runs every 60s, it must collect ~6k expired messages every 60s. With a partition size of 3, that means it must expire ~2k messages per partition. But with a variable size of ~13kb per message, the `MessageTimeToLiveChecker` can only collect ~300 expired messages every 60s. That's the point where Zeebe starts to build up state in the message column families. Consequently, the state grows infinitely, resulting in a significant performance drop.

**Expected behavior**

Column families are cleaned up correctly. Meaning, the expired messages are discarded at the same pace as they are published to Zeebe. To break down:
* Only the relevant message key is written to the expire message command (to save memory). That way, the checker can append up to 30k expire message commands in a 4MB buffer.
* Since only the message key is required, Zeebe can prevent doing an additional lookup to retrieve the actual stored message.

**Hints**
* Exporters:
  * By excluding irrelevant data in the command, the exported command to expire a message will only contain the message key.
  * That means, the correlation key, the variables, etc. are not part of any exported expire message command.
  * The same applies to the expired event that gets append to the log stream when the command got processed successfully.

**Environment:**
- OS: 
- Zeebe Version: 8.1.0, 8.2, (haven't checked for 8.0)
- Configuration:

**Comment by menski** [comment]
After discussion with team, we see this issue as high severity and not critical as we don't see right now the risk of data loss related with this issue. Our current assumption is that if a customer would face this issue, we would be able to provide a fix to recover the system. We will discuss in the next planning if we want to prioritize this issue for the upcoming patch releases.

**Comment by Zelldon** [comment]
I have run the mixed benchmark with 8.0 and it seems to be a regression with 8.1.

![general](https://user-images.githubusercontent.com/2758593/194877708-c7224be1-0302-474d-8189-83e1b845b9b4.png)
![snapshot](https://user-images.githubusercontent.com/2758593/194877710-6533e884-4353-4039-85c8-c96d26606910.png)

I disabled the publisher for the mixed benchmarks. We should enable it again after fixing the issue https://github.com/camunda/zeebe/commit/966dac308fb3bcbfc803b4a3e22fb0197bae59b4

**Comment by saig0** [comment]
I can't verify that the state in the message columns is not removed by using an engine test (e.g. `ProcessExecutionCleanStateTest`). 

The observations could be explained by the following:
- by default, the Java client uses a TTL for messages of **1 hour** 
- the benchmark publishes 100 messages per second
- as a result, the message state contains 360k messages before it starts removing them
- a job is scheduled every 60 seconds to remove messages 
- the job writes an `expire` command for each message 
- since version `8.1`, all commands are written as a batch
- each batch contains ~6k commands (or more)
- if the first command of the batch is not processed before the next job is executed then the next job will write the commands for the same messages (because the messages are removed from the state when the `expire` command is processed)

This would be a similar situation as we know already with too many timers in the state.

For the benchmark, we should keep in mind that the message TTL has an impact on the performance because it produces records.

```
6k `publish message` commands / minute 
+ 6k `expire` commands / minute 
+ 6k `create process instance` commands / minute  (for timer process)
+ 12K `create process instance` command / minute  (starter)
+ process instance follow-up commands
``` 

Next steps:

- [ ] in the benchmark: enable the message scenario again and set the message TTL to `0` (i.e. disable TTL); alternatively, we could enable TTL (e.g. `1 minute) and reduce the rate  
- [ ] in the Java client: change the default message TTL from [1 hour](https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java#L57) to `0` (i.e. disable TTL)
- [ ] in the Go client: change the default message TTL from [5 seconds](https://github.com/camunda/zeebe/blob/main/clients/go/cmd/zbctl/internal/commands/publishMessage.go#L74) to `0`

**Comment by saig0** [comment]
We explained the behavior in the comment above. To sum it up, it is not recommended to publish many messages with long TTL if the broker has a constant high load.

**Comment by romansmirnov** [comment]
@saig0 & @Zelldon, I came across this problem/issue while working on customer performance topics. It still needs a final validation by collecting of additional data points, but with the current data points and understanding, they run into this described issue resulting in a significant drop in throughput. That's why I spent some time to get a better understanding of the underlying issue.

While I agree to some degree with the above analysis, I think this is not very likely to happen. Meaning, yes, it potentially could happen that after submitting the batch of commands to expire/discard the messages, it could take some "time" until the actual commands are being executed. And in the meantime, the checker runs again and submits at least the same set of commands. With that assumption, we would see a spike in the "Overall Processing Latency" metrics, i.e., the metrics would show a latency of at least 1 minute. Since the screenshot does not include these metrics, of course, I cannot rule out that assumption, but I believe this is not very likely to happen. To me, that would mean that Zeebe is completely overwhelmed with the workload triggered by something else.

Also, I slightly disagree that setting the TTL to 0 solves the issue, it just delays the issue by at least 1h (or longer).

To my understanding, the underlying issue is when submitting a command to expire/discard a message, the entire message including its variables is written to the log stream.

https://github.com/camunda/zeebe/blob/720656b69cd28f5b4d14d516cad6f52a250c4107/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java#L37-L54

The mixed benchmark starts process instances by a message start event (and others via timer and so). Therefore, it publishes a message with variables, and correct me if I am wrong, the size of the submitted variables is ~46kb per message (it uses the `big_variables.json` by default).

Since a single expire command contains the entire message including the variables, the command already occupies ~46kb chunk of memory. Given that the checker collects these expire commands in a batch, and the batch is limited to 4MB it will only be able to submit ~300 expire commands at once (per partition).

To reproduce, I locally published 1k messages with the `big_variables.json` and TTL 2 minutes. Stopped Zeebe and started Zeebe after 2 minutes, the logs showed the following (I have added a log statement that prints out a log statement when the checker cannot append an entry anymore):
```
Can't append entry: 'RecordBatchEntry[key=2251799813686146, sourceIndex=-1, recordMetadata=RecordMetadata{recordType=COMMAND, intentValue=2, intent=EXPIRE, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=MESSAGE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.7}, unifiedRecordValue={"name":"foo","correlationKey":"897","timeToLive":120000,"variables":"hK9...' with size: 13948 this would exceed the maximum batch size. [ currentBatchEntryCount: 299, currentBatchSize: 4170452]
```

Note: If I don't include variables, ~30k of such expire commands can be submitted as a batch.

According to the above analysis, every minute ~6k of expired messages must be discarded. Assuming an even distribution of the messages across the partitions, it means ~2k messages per partition must be discarded. But the checker only submits ~300 expire commands. And that's where Zeebe builds up the state over time until the state does not fit into the block cache anymore resulting in the throughput drop.

In my opinion, the actual issue is appending the command containing the entire message with variables. Actually, the command only needs the message key, as the corresponding processor/applier only reads the key and nothing else from the message to discard. So instead of changing the default to TTL = 0, I would rather only write an expire command containing the message key (and a pretty much empty message). That way:
* Zeebe would not limit itself by including the variables in the command.
* The additional [lookup](https://github.com/camunda/zeebe/blob/720656b69cd28f5b4d14d516cad6f52a250c4107/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java#L345) could be avoided as Zeebe already has the message key coming from the `deadline` column family.

@Zelldon & @saig0, do I miss something? What are your thoughts?

**Comment by saig0** [comment]
@romansmirnov great analysis. :+1: 

I agree that we don't need to write the whole message record for the `expire` command, especially not the variables. Sounds like an easy fix. :rocket:

**Comment by romansmirnov** [comment]
Based on the received feedback, I decided to reopen this issue. Also, I updated the issue description to provide additional context.

**Comment by Zelldon** [comment]
Thanks @romansmirnov :+1:
