### ISSUE TITLE
Proof of Concept: Replace Dispatcher

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10691]
**Description**

After letting the idea sleep for a while https://github.com/camunda/zeebe/issues/3856 :) I thought yesterday again about it whether we could replace the dispatcher.

After #9600 we are closer to being able to replace it (I think). We introduced during the abstraction a new class called [RecordBatch](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/api/records/RecordBatch.java) which is filled during processing. Previously we kept only a ByteBuffer but now the batch allows to keep Record objects and write them later to the Dispatcher. 

The Dispatcher could potentially be replaced now with a [ManyToOneQueue](https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/ManyToOneConcurrentArrayQueue.java) from Agrona.

Benefits:

 * It allows to reduce one copy operation. Meaning no longer copying the data to the Dispatcher buffer, just copying object references
 * We can get rid of the Dispatcher, which can be seen as tech-depth.
 * We could get rid of the maxMessageSize limitations

Alternatively, we might be also able to migrate to the [ManyToOneRingBuffer.java](https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBuffer.java) which is kind of similar.

**Comment by npepinpe** [comment]
AFAIK the main advantage of the ring buffer is it can be backed by a mmap'd file, and as such can be used for IPC. In our case, the queue is probably all we need and the buffer would add overhead (unless I'm missing something :thinking:)

**Comment by megglos** [comment]
Planning:
It might be more complicated than anticipated. Thus starting as early in the quarter would be preferred.
Would make sense to to a POC here first. It is an area of technical depth.

**Comment by oleschoenburg** [comment]
One more thing:

`LogStreamWriter.tryWrite` currently returns a long position that is only used to indicate success or failure of the write.
It doesn't actually need to be a position though which helps in making the `Sequencer` lock free because it then has to do one thing only, appending to a queue. Positions can be assigned later, after writes are sequenced.

We can also experiment with this more, for example by offering an additional (or alternative) method that is blocking. Some writers, for example the `ProcessingScheduleService` could potentially be much simpler if they wouldn't have to implement retry logic.

**Comment by npepinpe** [comment]
I thought the ProcessingStateMachine was actually using the `lastWrittenPosition` for some of its internal logic. If we don't return that, how would it get this information?

**Comment by oleschoenburg** [comment]
Uhh yeah, my bad, I got excited :D 

Still, it's the only writer that actually needs it so maybe we could look into it to see if we can implement this differently.
