### ISSUE TITLE
Implement a `Serializer` that writes record batches with dispatcher framing

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10919]
The sequencer is an implementation of `LogStreamBatchWriter`. It supports multiple writers and a single reader.
Every `LogAppendEntry` is assigned a position and `LogStreamBatchWriter.tryWrite` returns the highest position of the batch.

To prevent unlimited buffering of `LogAppendEntry`, the queue length is controlled. If it is too long, `tryWrite` will result in an error code.

**Comment by npepinpe** [comment]
To summarize:

Part of the dispatcher replacement will be to move serialization downstream, at the moment we're handing off the record/entry to the underlying storage. Since entries are already immutable, we don't gain much by serializing them early on, and we may waste some time on it.

So instead, the serialization will occur right before it's passed off to the Raft server. Having a centralized point to handle it will help speed up future refactoring when we get to that point.

> In the future, this could be further improved by handing off a `BufferWriter` to the Raft server, and having the entry serialize itself only when it hits the journal.
