### ISSUE TITLE
Centralize flow control in `LogStorageAppender`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10922]
The `LogStorageAppender` currently uses either Gradient2 or Vegas for limiting the amount of append requests it pushes to the log storage. This is necessary, especially because the log storage is implemented by the raft layer which must not be overwhelmed with requests so that we don't miss any heartbeats.

Currently, the rate limiting, associated metrics and the listener which gets notified when entries are appended or when errors in the log storage occur are littered over the `LogStorageAppender`. Additionally, it currently requires that the appender acquires buffers from the dispatcher before checking the request limits which is not possible to do with the new sequencer where the appender can't drop an acquired batch if limits are reached.

To solve this, I'd like to introduce a new class that is responsible for flow control and associated metrics in the appender.

**Comment by npepinpe** [comment]
I don't personally have a new idea around flow control in this case. I toyed briefly with the idea of a credit based system, but it wasn't clear what gain we would get here. I think for that, the biggest gain would be to make the Raft server also a consumer, or make it consume directly from the sequencer (via some adapter), then it would make sense to revisit.

So for now, I would propose leaving the flow control much the same way we had it:

- A soft-memory bound for the sequencer buffer
- The rate limiter when pushing to the Raft server

Right now the dispatcher has a hard memory bound, since we have a fixed buffer. This may be difficult to achieve with the sequencer, but as every item reports an approximate serialized size, we could have a soft memory bound for the sequencer queue, by keeping track of the sum of `LogAppendEntry::getLength` of the whole queue, and updating it accordingly on offer/poll.  Then simply refuse offer when it would go over.

> There's always the edge case of the bound being, say, 128MB, and someone wanting to add a 128MB entry. In these cases, I usually would allow it, since we've already allocated the memory for the entry anyway. So you would say, if the queue is empty, just accept anything.

The rate limiter I will keep as is, but we can still isolate it further from the appender. Right now, the appender initializes everything; the whole rate limiting could be merged into the storage, in fact, where the storage is the one pushing back, e.g.

```java
interface LogStorage {
/**
   * Writes a block containing one or multiple log entries in the storage and returns the address at
   * which the block has been written.
   *
   * <p>Storage implementations must guarantee eventually atomicity. When this method completes,
   * either all the bytes must be written or none at all.
   *
   * <p>The caller of this method must guarantee that the provided block contains unfragmented log
   * entries.
   *
   * @param lowestPosition the lowest record position of all records in the block buffer
   * @param highestPosition the highest record position of all records in the block buffer
   * @param blockBuffer the buffer containing a block of log entries to be written into storage
   * @returns true if the write was accepted, false on backpressure
   */
  boolean append(
      long lowestPosition, long highestPosition, ByteBuffer blockBuffer, AppendListener listener);
}
```

Since we don't really have a "clever" back pressure mechanism (e.g. providing some kind of back off or credit), then simply returning true/false is probably OK, but we could be more explicit with a specific control enum (ofc, a `Result` type would be great too :)).

Pushing it down to the storage has two side effects:

1. Brings the whole rate limiting into the broker (where the `AtomixLogStorage` is implemented), making it much easier to make it configurable.
2. Makes the rate limiting storage specific, which makes sense, but of course is a little silly as we don't expect to have a second storage system any time soon :smile: 

It's generally a beneficial change, but the value isn't super high I think.

@oleschoenburg - let me know if I misunderstood the purpose of the issue. As it is now, though, I would propose moving the rate limiting behavior to the storage (from the appender POV), and making it configurable normally via the broker configuration. But I understand all this is probably quite low prio, so maybe there's a more task instead.

**Comment by npepinpe** [comment]
Change of plan: instead we will keep the rate limiting/flow control as is, but we will acquire the listener from the sequencer itself, and release it on commit (as we do now). This means slightly updating the sequencer to tie entries to the listener so it can be released on commit.

As such, it doesn't make sense to work on this yet until the sequencer is there and in use by the appender. Additionally, we will need to benchmark this to make sure the configuration is appropriate.
