### ISSUE TITLE
`LogStreamWriter#tryWrite` should return an actor future

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10923]
Since we are planning to implement `Sequencer` as an actor, we want to change the interface of `LogStreamWriter` so that `tryWrite` returns a future. As long as we use the dispatcher, this will simply return an already completed future.

**Comment by npepinpe** [comment]
Proposal:

- [ ] Modify the method to return `ActorFuture<Long>`
- [ ] Update usage to not return a -1 on failure but instead return a failed future
- [ ] Update all usages to handle the call asynchronously
- [ ] Ensure the synchronous log stream's is still synchronous, e.g. `long tryWrite()`
- [ ] Rename method to `write()` (since the concept of failure is baked into the return type)

**Comment by npepinpe** [comment]
First roadblock: the retry mechanisms we use don't play nicely with asynchronous operations :upside_down_face:

**Comment by npepinpe** [comment]
See the linked PR, but in general we decided to opt-out of this issue for now, and we may revisit it once we implement flow control with the sequencer.
