### ISSUE TITLE
PoC Process Instance Migration

### ISSUE THREAD

**Issue by menski** [camunda/zeebe#11099]
**Description**

As part of the discovery phase of https://github.com/camunda/product-hub/issues/166 we have to identify how we want to implement process instance migration. 

The goal of the PoC is to clarify technical concepts around process instance migration, validate the technical concepts on feasibility and create a first high level breakdown of different scopes to break down the epic into smaller iterations.

**Comment by shahabio** [comment]
👍🏼  for this

**Comment by korthout** [comment]
Spike kickoff prepared and members invited.

**Comment by korthout** [comment]
Results of the spike kickoff:

- We will not implement a PoC, but instead design some APIs that would allow us to implement this in iterations
- We should consider migrating multiple instances in one command
- Outputs:
	- API designs and ideas for iterations 
	- If possible, provide flexibility options for the iterations that can be discussed with customers

**Comment by korthout** [comment]
Results of the first spike session (day 1), with @remcowesterhoud, @berkaycanbc, and @abbasadel :

**what did we do?**
- we looked at and discussed the [C7 feature](https://docs.camunda.org/manual/develop/user-guide/process-engine/process-instance-migration/) and the [basic example](https://docs.camunda.org/manual/develop/user-guide/process-engine/process-instance-migration/#process-instance-migration-by-example)
- we shortly discussed our main proposal and looked at an example
- we looked at and discussed the [C8 Process Instance Modification API](https://docs.camunda.io/docs/apis-tools/grpc/#modifyprocessinstance-rpc) to see how Modification differs from Version Migration
- we also looked at the C7 API for Modification to verify that this is similar to the C8 API, although with differences in specifics (C7 has cancel all instances at element, C8 requires specifying a specific element instance)

**what did we notice**
- c7 uses a two-step mechanism:
  - define migration plan
  - execute migration plan
- we think a similar approach may work for c8, but we need to consider granularity in the API
- c7 leaves state in tact, but we plan to activate before each currently active element
  - this implies applying input mappings again
  - this also involves re-evaluating Assignments for user tasks and other such expressions
  - eventually we could allow skipping all of those via API (e.g. allow skipping io mappings), but for Assignments this requires additional work (i.e. we somehow need to set the assignee on the job headers)
- this also raises the question, how to deal with locally scoped variables?
- we shortly discussed the process instance history, where Zeebe needs to provide enough data through the API response (or through the exported events) such that Operate can determine the history

**next session:**
- we want to explore a simple API design for zeebe
- and provide a pseudo implementation to explore it

**Comment by berkaycanbc** [comment]
The initial gRPC request structure we designed in the Spike session (day 2).

```proto
message MigrateProcessInstanceRequest {
  // key of process instance to migrate
  int64 processInstanceKey = 1;

  MigrationPlan migrationPlan = 2;

  message MigrationPlan {
    // the process definition key to migrate into
    int64 targetProcessDefinitionKey = 1;
    // source (to migrate from) element id and target element id (to migrate into)
    repeated MappingInstruction mappingInstructions = 2;
  }

  message MappingInstruction {
    // the element id to migrate from
    string sourceElementId = 1;
    // the element id to migrate into
    string targetElementId = 2;
    // future extensions might include different types of instructions
    // for now, however, the start instruction is implicitly a
    // "startBeforeElement" instruction
  }
}
```

**Comment by korthout** [comment]
Thanks for sharing @berkaycanbc! That helps me explain what we learned today!

Today, we spent time designing the API. During this, we discovered some valuable things:

1. **We chose to make the API support only single-instance migrations**
  - the first thing we ran into was whether we should support a single instance to be migrated at a time or allow multiple instances to be migrated simultaneously
  - we discussed why the other commands (create, cancel, modify, etc) are all for single entities 
  - single instance per command allows fine-grained rejection with the currently available tools (rollback command on failure)
  - so it is much easier to implement for us
  - multiple instances per command would require a way to inform about the partial completion or would suffer from the same all-or-nothing problem that C7 had (which was considered bad UX)
  - we can use a re-usable migration plan to make API usage easy when many instances need to be migrated (this can be solved in the client)
  - single instance per command fits better to the stream processing concept of Zeebe
2. **No source process definition is needed in the migration plan**
  - a source process definition must be provided to the C7 migration plan
  - the source process definition is already known for each process instance
  - but we require a target process definition (either defined by the `processDefinitionKey` or by the combination of `bpmnProcessId` and `version`)
  - if available, a source process definition could be used to validate the request in Zeebe (can this migration plan be used for this process instance?)
  - this validation is not necessary, i.e. without it, we would anyways migrate **TO** the target process definition, so the source doesn't matter much
3. **We document in the schema that the mapping instructions implicitly have the start before element type. A `type` property can be added later when we want to support multiple mapping instruction types**
  - we discussed how the API should inform the user that the mapping instructions don't result in the same state but instead instruct Zeebe to start before the target element
  - since this behavior may be unexpected (especially to C7 users), we must make it clear to them
  - we looked at using a `map<string, string>` for the source element id -> target element id mapping first, but this does not inform the user about this behavior
  - then we looked at naming the instruction properties explicitly, leading to long names
  - since we have this same problem in start instance anywhere and process instance modification, we looked at those APIs
  - they support the ability to extend the instruction with more properties, like `type`, and explain in the documentation that the current type is a `start before instruction`
  - we should ensure this is clear in the client's API so users don't have wrong expectations.

---

In the next session, we'll look into writing a pseudo implementation for this API design.

**Comment by remcowesterhoud** [comment]
The pseudo-code for the spike is on this branch https://github.com/camunda/zeebe/tree/migration_spike_day3

**Comment by korthout** [comment]
Today, we implemented the designed API in pseudo-code during a mob programming session. Thanks, @remcowesterhoud, for driving and sharing the code! And thanks, everyone, for joining again! 🚀 

During our mob programming session, we encountered the following lessons learned:

- We must extract creating the process instance record from `CreateProcessInstanceProcessor` into a reusable behavior (move into `ElementActivationBehavior`)
- We must extract terminating the existing process instance from `ProcessInstanceModificationProcessor` into a reusable behavior
- We must ensure that `ElementActivationBehavior` activates the process instance, not only subprocesses. It seems to do this, but it's not clear from the naming of the methods nor the JavaDoc
- We must introduce a `ProcessInstanceAnalyzer` that finds the active non-container element instances from the process instance

The pseudo-code only focussed on a happy path. In the next session, we'll:
- discuss this pseudo-code
- consider special cases
- and devise a way to split this into several deliverables

**Comment by korthout** [comment]
Yesterday, we discussed the pseudo-implementation, considered special cases, and reasoned about potential iterations. While writing up our findings, I ended up writing the full results of this spike.

# Concept
First, let's shortly recap the concept that allows us to implement this feature in Zeebe. 

The API would look something along these lines:
```feel
message MigrateProcessInstanceRequest {
  // key of process instance to migrate
  int64 processInstanceKey = 1;

  MigrationPlan migrationPlan = 2;

  message MigrationPlan {
    // the process definition key to migrate into
    int64 targetProcessDefinitionKey = 1;
    // source (to migrate from) element id and target element id (to migrate into)
    repeated MappingInstruction mappingInstructions = 2;
  }

  message MappingInstruction {
    // the element id to migrate from
    string sourceElementId = 1;
    // the element id to migrate into
    string targetElementId = 2;
    // future extensions might include different types of instructions
    // for now, however, the start instruction is implicitly a
    // "startBeforeElement" instruction
  }
}
```

This API allows for defining a migration plan consisting of a target process definition and a set of mapping instructions. Each instruction looks like `[source element id -> target element id]`. When migrating an instance, we make an activation instruction for each activate element instance (excl. container elements like sub-process) based on the migration plan. These activation instructions are then used to create a new instance of the target process. The activation instructions will have the `start before element` type.

This means that **active element instances that are mapped to the same element in the target process, are activated newly in the target process**. This includes applying the input mappings and evaluating any FEEL expressions (e.g. a user task's `assignee` expression). This may be unexpected to users that expect that the process instance is somehow copied to the target process. We must highlight this in documentation, in our API, and in tools like Operate. Eventually, we could support skipping the input mappings on such instructions through the API, but this would likely not make it into the first iteration.

This migration plan can be reused in migrations of individual process instances. This allows the engine to stay true to its stream processing capabilities while staying user-friendly when migrating large sets of process instances. It also allows migrating some of the process instances, and individually rejecting those Process Instance Migrations we could not perform.

# Iterations and special cases
During this session, we discussed several special cases. Some are complex and may be turned into iterations. What follows is a list of potential iterations, their limitations, and how they try to deal with special cases.

1. **Keeping the number of active elements the same**
- this is the case when the mapping instructions define an element in the target process for each activate element
- we need to map one or more active instances to start-before-element activation instructions
- this is the basic behavior we defined on spike day 3, and should probably be the first iteration
- the first iteration should have some support for variables:
	 - global variables and local variables of sub processes will be copied for each ancestor scope
	 - this is necessary to correctly evaluate the input mappings of elements targetted by activation instructions
	- local variables of the active element instances that are mapped to activation instructions will not be passed along with the activation
	- they were likely the result of input mappings on the activate element in the source process, but the target process may have different or no input mappings
- the first iteration will reuse an instance of a flow scope for the activation instructions targeting an element nested inside a flow scope that is also activated due to another activation instruction
	- similar to [activating elements in an existing flow scope with Process Instance Modification](https://github.com/camunda/zeebe/issues/9642)
- this implementation does not support activating elements of the types, similar to [Process Instance Modification](https://docs.camunda.io/docs/components/concepts/process-instance-modification/#limitations):
	- a start event of a process or a subprocess
	- a boundary event
	- an event that belongs to an event-based gateway
	- an element inside a multi-instance subprocess
	- a sequence flow
- the first iteration does not support migrating the child process instance of an active call activity

2. **Activating an additional element**
- this is the case when the target process has some parallel flow that did not exist in the source process. So an additional element instance must be activated.
- this could be represented in the migration plan's mapping instructions in two forms:
  1. `[nothing -> target element id]`
  2. `[source element id -> target element id, source element id -> target element id 2]`
- note that multiple instances can be added using additional mapping instructions, e.g. repeat mapping instruction `i` twice to create two new instances of `target element id`, something similar can be considered for mapping instruction `ii`
- this may be a straightforward addition that could be part of the initial iteration

3. **Choosing not to activate an element**
- this is the case when the target process has replaced some parallel flow that used to exist in the source process. So one of the superfluous element instances must not be activated in the target process.
- this could be represented in the migration plan's mapping instructions in the following ways:
  1. `[source element id -> nothing]`
  2. by simply leaving out a mapping instruction for this source element id
- note that **there is no way to select a subset of active instances of an element**, e.g. both instances of a twice active user task will either be terminated together, or they are both mapped to start before element instructions for the same element. Users will need to apply Process Instance Modification to choose a more specific behavior for each of the individual active instances
- this may be a straightforward addition that could be part of the initial iteration

4. **Dealing with nested elements**
- when a migration plan instruction activates a nested element, then we may have to select a specific ancestor (similar to [modification with nested elements](https://docs.camunda.io/docs/components/concepts/process-instance-modification/#activate-a-nested-element))
- by default, we always reuse an instance of a flow scope for the activation instructions targeting an element nested inside a flow scope that is also activated due to another activation instruction
	- we cannot make any other assumptions about which ancestor should be selected because the source and target process may differ substantially
	- there may be some cases where we could infer the likely selected ancestor, but the engine should not make such guesses
- in a future iteration, we could support selecting the ancestor scope for each mapping instruction:
	- using an `ancestor scope id` for each mapping instruction
		- this would allow re-using a sub process as the flow scope for several activation instructions targetting elements inside that sub process
		- note that this does not allow creating two instances of the sub process and reusing each for several instances of elements inside that sub process 
	- using a mapping tree (i.e. a tree structure that resembles the process) that describes each of the instances that should be activated and their ancestor instances
		- this would be more flexible and powerful, but it would also be harder for users to define such a mapping tree
		- for example, consider the following processes with three active user tasks due to the multi-instance sub process:

<img width="599" alt="Screenshot 2023-04-25 at 16 16 19" src="https://user-images.githubusercontent.com/3511026/234310196-c5f2c9bb-52a8-41b7-91b3-97218f801f84.png">	
		
```json
{
  "source_element_id": "USER_TASK_1",
  "mapping_tree": {
    "ancestor_id": "MY_NEW_PROCESS",
    "descendants": [{
        "ancestor_id": "SUB_PROCESS_WITH_PARALLEL_GATEWAY",
        "descendants": [
          { "target_id": "USER_TASK_1" },
          { "target_id": "USER_TASK_2" }
        ]
      },
      {
        "ancestor_id": "SUB_PROCESS_WITH_PARALLEL_GATEWAY",
        "descendants": [
          { "target_id": "USER_TASK_1" },
          { "target_id": "USER_TASK_2" }
        ]
      },
      {
        "ancestor_id": "SUB_PROCESS_WITH_PARALLEL_GATEWAY",
        "descendants": [
          { "target_id": "USER_TASK_1" },
          { "target_id": "USER_TASK_2" }
        ]
      }
    ]
  }
}
```

5. **Passing locally scoped variables along** 
- by default, local variables of the active element instances that are mapped to activation instructions will not be passed along with the activation
- the mapping instruction could be extended to specify a set of variables names that when existing on the activate element instance should be passed along with the activation instruction
- this could also be extended by supporting a `pass all local variables` flag

6. **Dealing with multi-instance**
- this case seemed too complex to consider at this time
- it would make a good candidate for a later iteration
- there are no ideas on how to support this yet

7. **Dealing with child process instance of an active call activity**
- this case seemed too complex to consider at this time
- it would make a good candidate for a later iteration
- there are no ideas on how to support this yet

# Open questions
After this spike, we are left with several questions that we'd like to find answers to:
- does the initial iteration provide value to users?
	- does it deal with actual use cases from users?
	- would it be easy enough to use for those cases?
	- how do users experience the concept that active instances are not copied from the source to the target process, but are activated with a start before element instruction?
- how do users feel about migrating single instances with a reusable migration plan?
- do users want to add a source process definition key to the migration plan to avoid using it in situations that were not considered?
- do users agree that local variables should not be passed along with the activation instruction?
- would users prefer the simplicity of the `ancestor scope id` to select an ancestor, or is there a need for the more powerful but cumbersome mapping tree concept explained in iteration 4?
- what do users consider the priority ordering of the iterations based on their use cases?

**Comment by aleksander-dytko** [comment]
@korthout @remcowesterhoud @abbasadel so in short summary the iterations would look like:

1. Keeping the number of active elements the same
This means that I can migrate all running flow node instances of single process instance, with 1:1 mapping of active flownode instances.

2. Activating an additional element
It means that I can migrate all running flownode instances + create new flownode instances during migration

3. Choosing not to activate an element
Meaning that I can migrate some running flownode instances and terminate the rest.

4. Dealing with nested elements
5. Passing locally scoped variables along
6. Dealing with multi-instance
7. Dealing with child process instance of an active call activity

Is that the correct summary?

**Comment by korthout** [comment]
@aleksander-dytko That's a good summary of the iterations. As mentioned, some of these may be rather straightforward to add (i.e. 2 and 3), while others (i.e. 6 and 7) are highly complex with lots of unknowns.
