### ISSUE TITLE
Prometheus shows incorrect metrics from the benchmarks

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#11330]
Sometimes, in the benchmark cluster, gateway is shown as leader/follower for partitions. 

![image](https://user-images.githubusercontent.com/1997478/209115569-edb0bd3b-f4a4-40ba-b389-2d10a8832e37.png)

At this time, gateway is also shown as processing.
![image](https://user-images.githubusercontent.com/1997478/209115732-894353c3-ff98-4c59-b5fb-ace6825c1b51.png)

This messes up our benchmark throughput comparison. As it throughput shown includes the numbers from gateway. 

The gateway is not actually processing anything at that time. Crossed checked from the logs. Also the gateway which is showns as leader and processing has been terminated long time ago. So it is clearly a bug in metrics scraping.

### Observations
IP of terminated gateway pod matches with a currently running broker. The gateway is marked as leader/follower if the broker is leader/follower for corresponding partitions. 

Here zeebe-1 and the gateway shares the same ip. The gateway is already terminated. But both are leaders for partition 2.
![tmp-20789-qDDs2KERrKB8-image](https://user-images.githubusercontent.com/1997478/209116299-dd7bef50-a653-4540-9f5c-0d3b216da468.png)
![tmp-20789-5b5WmbpW1qTq-image](https://user-images.githubusercontent.com/1997478/209116440-ac97b7dd-ef2c-4f7c-844f-99d0f6e5999e.png)
![image](https://user-images.githubusercontent.com/1997478/209116570-1e64f33d-a818-4e00-a449-8649c084d73e.png)

Another example. Here zeebe-2 and the terminated gateway shares the same ip. They both are shown as leader for partition 1 and 2.
![tmp-20789-f6ut9CNk32XJ-image](https://user-images.githubusercontent.com/1997478/209116825-0ababa37-8f6c-4112-9085-b3fafbffe2f2.png)
![tmp-20789-4WdIdpGNDt7x-image](https://user-images.githubusercontent.com/1997478/209116874-45f7541f-d8cb-4d40-bd22-8fdf1d0aecf3.png)
![image](https://user-images.githubusercontent.com/1997478/209117168-8e9fe2be-3263-4b41-a797-a6a1b20dfc1d.png)

So this is clearly not a bug in Zeebe. But in the monitoring infra. Not yet clear if it is some config issue on our side or a bug in pometheus or gcp infra.

**Comment by npepinpe** [comment]
Good catch, the observation about IP reuse may hint at some bug where it's merging metrics based on IP (I think in their lingo this is something to do with location).

To add to your observation, the pod `medic-cw-49-79bcae7-benchmark-zeebe-gateway-5c7b7f5696-5bpkg` is dead, but it still exists - it seems it failed in error state? It seems we have many pods in that namespace in error state:

![image](https://user-images.githubusercontent.com/43373/209129644-41fd909c-dd3c-4bfc-a27f-22483feb3c07.png)

It's unclear if this is related, but it could be.

**Comment by npepinpe** [comment]
The gateway has been removed from the metric value now (if you look at the time window since I removed the pod). 

My guess is this is what was happening:

1. Pods reuse the same IP
2. Since the old gateway pod is dead _but not removed from the API_, its labels are added to the scraped data for the pod with the reused IP.

If that's the case, then you would hope they would actually check the status of the pods before appending the labels. Since we're not deploying the scraping ourselves, I don't think there's much we can do :(

We could check with the SREs as to how we can prevent getting in a situation where we have so many failed pods, but that's a mitigation (though it might be good to do anyway - I don't know if it could be a sign of something worse :shrug:). 

As we don't have support for managed Prometheus with our current billing plan, we also can't reach out to Google about this.

For now I'll clear out all the errored pods across our clusters. If anyone thinks of another solution, let me know.

From my POV, we have 4 options:

1) Pay to get support from Google (unlikely :smile:)
2) Move our benchmarks/tests into a SRE-team managed stage (though we have admin access to do most things without them)
  2a) Maybe as a compromise, they set up the stage for us but then we own it? Though it still makes it a bit more complex for us to keep up with their changes. This could be an option though. Maybe we pick 1 person from our team to be the "SRE", and another as fallback.
3) We go back to having a Prometheus Operators deployed per cluster, and try to maintain it up to date. This means multiple Grafanas again, and generally more maintenance work.
4) We deploy a Prometheus Operator per cluster, but with Thanos sidecars, so we can have a single Grafana/query interface. The downside is this deployment is much more complex :( The good news is the Helm chart can also take care of that for us to some extent.

Option 2 sounds best imo :)

**Comment by deepthidevaki** [comment]
I remember reading sometime ago that, by default, failed pods are not automatically deleted. They are kept in case we need it for debugging. This is probably why there are so many failed pods. But atleast one of the gateway pod that I looked into was not in Error state but just Terminated. So not sure why it was not deleted.

**Comment by npepinpe** [comment]
The console reports scaling down issues of nodes due to pods not being removed. I never looked into it though, so it could be related :thinking:

**Comment by Zelldon** [comment]
> I remember reading sometime ago that, by default, failed pods are not automatically deleted. They are kept in case we need it for debugging. This is probably why there are so many failed pods. But atleast one of the gateway pod that I looked into was not in Error state but just Terminated. So not sure why it was not deleted.

This is exactly also what I remember.

>  pick 1 person from our team to be the "SRE"

Happy to be an SRE :laughing: but not sure whether this solves actually the issue, since in SaaS we have the same (dead pods lurking around). Or is the managed prometheus the problem? Because this is what we not have in SaaS. 

BTW I think it was anyway the plan to migrate soon or later to SaaS with our benchmarks to further reduce the infra costs of our team (I know it is just moving the costs :sweat_smile: )

**Comment by korthout** [comment]
@deepthidevaki I see that this issue is on the ZPA board as well. Can you clarify what is expected of us?

**Comment by deepthidevaki** [comment]
@Zelldon What was the reason you added it to ZPA board?

**Comment by Zelldon** [comment]
Well I see that as a shared responsibility new to me that we are in charge of the benchmark infrastructure.

Since AFAIK ZPA has been assigned as responsible for the deliverable which I still not sure whether this makes sense.

**Comment by deepthidevaki** [comment]
Thanks @Zelldon Ya. It makes sense this to be a shared responsibility. But then it is not clear who takes the responsibility to fix it :smile: 

> Can you clarify what is expected of us?

@korthout I don't have an answer for this.

**Comment by npepinpe** [comment]
I'm pretty sure we identified the issue. There's one thing I'd like to try, which is use the PodMonitoring spec instead of ClusterPodMonitoringSpec. In the meantime, performing manual garbage collection works.

It also only seems to affect the normal cluster - maybe because of spot instances?

**Comment by megglos** [comment]
@megglos let's check-in with SRE/Infra if we could get a setup provided

**Comment by npepinpe** [comment]
Yes :+1:
