### ISSUE TITLE
Cannot use local variables in output mapping of error boundary event

### ISSUE THREAD

**Issue by datakurre** [camunda/zeebe#11407]
Is this a bug or a feature?

I was expecting to be able to first set local variables on activated task, then throw error, and finally, on output mapping of the error boundary event, use those local variables. Instead an incident of missing variable is raised.

**To Reproduce**

With the attached BPMN (in a zip)

[OutputMappingTest.zip](https://github.com/camunda/zeebe/files/10408092/OutputMappingTest.zip)

```
$ zbctl create instance OutputMappingTest --insecure
{
  "processDefinitionKey": "2251799813698351",
  "bpmnProcessId": "OutputMappingTest",
  "version": 1,
  "processInstanceKey": "2251799813698396"
}

$ zbctl activate jobs Task --insecure
{
  "jobs": [
    {
      "key": "2251799813698401",
      "type": "Task",
      "processInstanceKey": "2251799813698396",
      "bpmnProcessId": "OutputMappingTest",
      "processDefinitionVersion": 1,
      "processDefinitionKey": "2251799813698351",
      "elementId": "Activity_1sfl475",
      "elementInstanceKey": "2251799813698400",
      "customHeaders": "{}",
      "worker": "zbctl",
      "retries": 3,
      "deadline": "1673589895623",
      "variables": "{}"
    }
  ]
}

$ zbctl set variables 2251799813698400 --variables '{"variable": "value"}' --local --insecure
Set the variables of element instance with key '2251799813698400' to '{"variable": "value"}' with command '2251799813698473'

$ zbctl throwError job 2251799813698401 --errorCode ERROR --errorMessage Test --insecure
Threw error with code 'ERROR' on job with key 2251799813698401
```

![OutputMappingTestIncident](https://user-images.githubusercontent.com/160447/212235592-a32a3e30-69a2-4aa5-9ea2-53b14cc50077.png)
![OutputMappingTestVariables](https://user-images.githubusercontent.com/160447/212235598-6b7e5b02-cd1d-40b1-853e-09bbd3524899.png)

**Expected behavior**

I was expecting to use local variables in output mapping of a boundary error event.

**Environment:**
- OS: Linux
- Zeebe Version: 8.1.5
- Configuration: Hazelcast Exporter

**Comment by remcowesterhoud** [comment]
We should investigate how we want to deal with this behaviour. In 8.2 we can pass variables when throwing an error event, this might already be a workaround for this as the variable would be available on the scope of the catching boundary event.

**Comment by korthout** [comment]
Thanks for reporting @datakurre. I've had a look at this and can reproduce the behavior. However, I think this is expected behavior. ✅ 

❌ The Boundary Event is attached to the Task. The Task does not contain the Boundary Event (i.e. it is not a parent/child relationship). The Variables that should be visible from the Boundary Event are only those that exist on the local scope of the Boundary Event **and** those of the scopes above it (e.g. at a Sub Process or root of the Process scope). In your example, only Variables at the Boundary Event and at the root of the Process are visible to Expressions at the Boundary Event.

❌ In addition, the Event interrupts the Task. By the time the Event becomes active, the Task is already gone (i.e. terminated). So any Variables existing at the Task are also gone at that time.

👍 I agree with @remcowesterhoud that the upcoming feature in 8.2 may help solve your problem. With 8.2 you can pass variables along with the thrown error, and these are available at the Boundary Event.

💡 As a workaround in versions before 8.2, you can use a Message Event instead. This has some semantic differences in your process model, but would offer you the ability to pass variables to the Boundary Event.

@aleksander-dytko We talked about this issue before. Would you be willing to say something on this issue from your perspective?

**Comment by datakurre** [comment]
@korthout Thanks for the detailed explanation. Passing variables with error makes sense. Do those remain in error scope or be possibly merged into higher scope in usual fashion?

**Comment by korthout** [comment]
@datakurre Yes they are propogated if no output mappings exists, and created locally when output mappings exist. However, they suffer from [this issue](https://github.com/camunda/zeebe/issues/11001) just like messages with variables. So, when no output mappings exists, then the variables are created both at the local scope **and** propagated to higher scopes.

**Comment by datakurre** [comment]
Thanks you for confirming and reminding. I am ok with 8.2 behavior.
