### ISSUE TITLE
Truncate `errorMessage` to prevent exceeding `maxMessageSize`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11460]
Similar to https://github.com/camunda/connector-sdk/issues/345, Zeebe should truncate error messages it produces to a sensible value. This is to prevent extremely large generated error messages from exceeding the `maxMessageSize` which, for example, can lead to incidents not being created.

For users, a truncated error message is more helpful than getting no response at all.

**Comment by remcowesterhoud** [comment]
@oleschoenburg Could you explain a situation in which this would occur? Didn't we already fix this with https://github.com/camunda/zeebe/pull/10402?

**Comment by oleschoenburg** [comment]
@remcowesterhoud Maybe? I'm not sure tbh. @saig0 recommended to create an issue for this, maybe he can provide more context.

**Comment by saig0** [comment]
@remcowesterhoud it's about improving the UX in Zeebe. We want to limit the `errorMessage` in the job and the incident record. 

If a client (i.e. a job worker) provides a too-large error message, we still want to fail the job and create an incident. Since it makes not much sense to store a huge error message and it could exceed the batch size, we cant to shrink the error message to a reasonable size. 

We raised the issue after seeing that a connector tried to fail a job with a huge error message. By accident, the error message contained a big JSON payload. As a result, the connector was not able to fail the job. See the details [here](https://github.com/camunda/connector-sdk/issues/345).

This situation could happen to any job worker. Or, even within the engine processing, for example, if an expression failed and we try to create an incident with a huge error message.
