### ISSUE TITLE
Remove the default un-overridable `-Xms128m` value

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#12416]
**Is your feature request related to a problem? Please describe.**
It is hard to tune the JVM if I cannot override the default `-Xms128m`. I can't override it via `JAVA_OPTS` because it is used at first, and then goes explicit `-Xms128m` (and finally applied):
```
exec "$JAVACMD" $JAVA_OPTS -Xms128m -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8...
```

**Describe the solution you'd like**
I would like to move all JVM options into the default Docker environment variable (`JAVA_OPTS`) so that users could override it easily (`-Xms` included).

**Describe alternatives you've considered**
We could just remove `-Xms128m` from the default options, but I can't predict the consequences.

**Additional context**
See the details [here](https://camunda-platform.slack.com/archives/C6WGNHV2A/p1681141205701259).
I would like to see the changes backported in 8.0, 8.1, 8.2 as well 🙂

**Comment by megglos** [comment]
this affects the dist module (which is shared? 😅 ), the script is generated via the `appassembler-maven-plugin`, which has a feature request for exactly this open since 2016 😅 
https://github.com/mojohaus/appassembler/issues/48

Just synced with @Zelldon on this, the best would probably be to remove this flag from the plugin config and stick to jvm defaults
https://github.com/camunda/zeebe/blob/main/dist/pom.xml#L290

**Comment by remcowesterhoud** [comment]
Oh right, I don't know how I missed that in the split document 🤦 

I'll assign it to both our project in that case

**Comment by aivinog1** [comment]
Hey @remcowesterhoud! If this is not occupied I could provide the PR to fix it:
> Just synced with @Zelldon on this, the best would probably be to remove the Xms flag from the plugin config and stick to jvm defaults

**Comment by remcowesterhoud** [comment]
@aivinog1 Thanks! It's not occupied so go ahead. I'll assign the issue to you 👍
