### ISSUE TITLE
Won't parallelise within a parallel gateway

### ISSUE THREAD

**Issue by vincentgiraud** [camunda/zeebe#12446]
Describe the Bug

Adding multiple http json activities in a parrallel gateway will result in executing each activity sequentially.
It doesn't happen with a parralel multi instance.

Steps to Reproduce

Execute this using any mock rest service with a 5 (or else) second delay:

<img width="444" alt="Capture d’écran 2023-04-15 à 12 55 08" src="https://user-images.githubusercontent.com/11131880/232451710-70e6dbb8-64c1-4346-aa47-84d51cf56aea.png">

The process will complete in ~20 sec

Expected Behavior

The process completes in ~5 sec

Environment

OS: Mac OS 13.1.1 M1
Library versions: both connector-bundle 0.16.1 and 0.18.1
Camunda version: 8.2.0 docker compose

**Comment by koevskinikola** [comment]
Hi @vincentgiraud,

Thank you for raising this topic.

I see that you're using Connectors in the process you provided. In Zeebe, these are just BPMN service tasks, and for each service task, a job is created.

The jobs are created in parallel when the service tasks are activated. 

So this isn't an issue in Zeebe, as the jobs are polled and processed by external job workers. Each job worker can be configured in a different way on how to process jobs (i.e. how many jobs, what type, etc.)

The Connectors work on top of this API, so I suspect that the issue lies there.

As a result, I will close this issue in favor of https://github.com/camunda/connectors-bundle/issues/470 which you already opened. Alternatively, I would suggest opening a help request topic at [forum.camunda.io](https://forum.camunda.io/) since this might be a configuration issue, and the community there may certainly help you.

Best,
Nikola
