### ISSUE TITLE
Can Zeebe replace Kafka without the need for an additional Kafka

### ISSUE THREAD

**Issue by heerzhang** [camunda/zeebe#12543]
Can Zeebe replace Kafka without the need for an additional Kafka, Compared to Kafka Zeebe message processing flow

How much performance loss is there

**Comment by berkaycanbc** [comment]
Hey @heerzhang, thanks for your interest in our project and the question.

The situation depends on the use case. Because Zeebe is designed to run BPMN and DMN flows in a highly scalable, distributed manner. Therefore, Kafka and Zeebe not built for exact same purposes. However, there are cases where they work well together.

Based on our [contribution guide](https://github.com/camunda/zeebe/issues/12543) please refer such questions to our [forum](http://forum.camunda.io/) or [Slack](https://www.camunda.com/slack) channel. That way, you can learn more about potential usages of Kafka along with Zeebe and get answers to your other general questions.
