### ISSUE TITLE
Limit partition leaders/followers at Zeebe Broker node

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#12631]
**Is your feature request related to a problem? Please describe.**
My problem is next: I know that my Zeebe Brokers work fast and resilient (no partition leader's changes, low latency, etc) if there are no more than two partition leaders on one node. If there are more than two partition leaders at the same host - it becomes a bottleneck. So it would be nice if we could soft limit the number of leaders and followers at the one broker node. 

**Describe the solution you'd like**
Just introduce a soft (best-effort, meaning that if possible (there are enough nodes)) limit of leaders and followers per node.

**Describe alternatives you've considered**
I understand, that there is a fixed partition mechanism exists but it is not convenient to work with it, because we should revisit the config whenever we are adding a new broker node. So, in terms of alternatives I would consider "fair" (meaning that every node would be best-effort equally loaded (leaders and followers of the partition) partition distributing. But, I think, that is the easiest way to achieve a "fair" partition distribution - just limit the broker (again, in soft matter, if possible).

**Comment by npepinpe** [comment]
Hey @aivinog1 - it can be tricky to implemented an automated way of ensuring leadership is appropriately balanced, as it can inadvertently lead to unnecessary downtime. As we consider this is a somewhat complex/larger topic, we wouldn't take this on yet.

In the meantime, you can work around this by making use of our [rebalancing feature](https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/rebalancing/). If you couple this with [priority election](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/priority-election/), then you can get a pretty stable, "perfect" balancing.

[Here's an example of how we maintain this in our load tests](https://github.com/zeebe-io/benchmark-helm/blob/main/charts/zeebe-benchmark/templates/leader-balancing-cron.yaml). Note that for us, since these are load tests, we're more interested in long term throughput/latency than small periods of unavailability, which is why blindly rebalancing fits our use case. It may not fit all use cases however.

- Link to docs about priority election
- Link to docs about rebalancing endpoint
- Link to benchmark-helm rebalancing cron job
