### ISSUE TITLE
Forcefully terminate a process instance

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#12696]
**Is your feature request related to a problem? Please describe.**

Some process models can sometimes cause whole partitions to become completely bricked. For example, process models with a combination of loops, large multi-instance collection spawning activities, or straight-through processing (e.g. FEEL script tasks, undefined tasks, manual tasks, etc.) can cause us to write a large amount of follow up records, much faster than we can process or export. This can lead to:

- The exported system being overloaded, e.g. Operate cannot import fast enough, Elasticsearch runs out of disk space, etc.
- Runaway process instances cannot be canceled because the command is either not accepted, or written so far down the log that it takes hours to get there, at which point we've written millions more follow up records.
- Node is out of disk space, leading to all partitions stopping.

**Describe the solution you'd like**

While preventing such situations is ideal, as a first step, we would like to provide an escape hatch for when they arise by allowing users to forcefully terminate a process without having to wait for all events to be processed.

This means providing a way to bypass the causality chain of the partition by directly modifying the state projection.

We would have to:

1. Provide an API endpoint (whether a management or client endpoint is to be determined) where users can forcefully terminate a PI by key
2. The leader of the partition for this PI must then modify the state to mark that PI as forcefully terminated. **It may not be possible to write to disk anymore, so we may have to simply modify the state**.
3. The state modification must be replicated to all followers, much like the exporter state. This is to ensure consistency between all nodes should an election occur.
4. Once a PI is forcefully terminated, then all records associated it still have to be read but can be skipped/not processed/replayed. **We cannot delete them from the log - this not only breaks the append-only contract, but is much more complicated**
5. The records must also be skipped by the exporters. However, we may want to notify the external systems that the PI has been forcefully terminated somehow, so we may need some solution here. Maybe we still need to write a record at the end of the log specifying it was forcefully terminated.

In terms of UX, it would be great to be able to differentiate between normal termination and forceful termination, if only for monitoring and auditing purposes.

**Describe alternatives you've considered**

- Static analysis of process models to detect endless loops. This may not always be possible, and there may very well be valid use cases for such. Unclear how easy that is, especially things like a process with a call activity where the called ID is a variable which could point to the process itself.
- Fair/weighted process scheduling. A rather complex solution, where the processor ensures that one PI cannot overwhelm the partition at the cost of other PIs or external user commands. This could be achieved by performing more look-ahead and determining whether it's safe to continue processing a given PI or if it should yield, and writing deferred computation records to resume it.

**Additional context**

Several incidents occurred recently which were the results of users deploying looping, straight-through processes, which were producing too writing more than the system could process/export. One was writing an exponential number of follow up records, which led to an unrecoverable out of disk space, where there was nothing to compact yet, so processing could never resume.

**Comment by korthout** [comment]
@npepinpe I worry that termination of the process instance is considered a loss of data.

Instead of termination of the process instance, I'd rather see something like suspension of the process instance. For example, by creating a process instance-level [Incident](https://docs.camunda.io/docs/components/concepts/incidents/) with a new `ErrorType` that prevents any further progress unless they are attempts to repair the instance, e.g. Modification, SetVariable, Migration, etc. This aids in visibility and allows users to repair the instance.

Such a solution is also what we are investigating in relation to:
- #5121 
- https://github.com/camunda/product-hub/issues/686

I understand if that would not make it into the first iteration, but I'd hope we can replace the termination logic with what I've described here in some future iteration.

**Comment by Zelldon** [comment]
Yesterday I was also thinking about suspending process instances just for the same use case, from the operations point of view, to get my system healthy again or avoid an imbalance of exporting and processing. 

Not sure whether the proposed solutions above are optimal, due to the state changes without processing a command. 

----

What I thought we could do is have a runtime transient toggle that can be flipped for every process instance. If we see that a process instance makes problems we could flip it and the process instance will be ignored. Kind of similar to being blacklisted, but not persistent. If we restart the instance can be executed again. 

**What does ignored mean?** 

There could be two things either, completely skip all commands, but then you will lose the progress. OR you simply append the current command for the process instance at the end of the log, without processing it. This allows to make progress still on other instances, and later again on the PI if it is no longer suspended. (BTW IMHO commands shouldn't be exported anyway (https://github.com/camunda/zeebe/issues/6749))

We need to allow certain commands like canceling still be processed for such PI. This allows to clean up, similar to we should allow for blacklisted instances.

_______


To develop this further I could imagine that we could at some point have this even automatically, like normal OS scheduling or as we know in K8. If you have X process instances and Y CPUs than a PI is only allowed to take Y/X CPU time, if more we could suspend it for a time frame (append the current command at the end such it will be processed later).

**Comment by korthout** [comment]
🤔 Interesting ideas @Zelldon. 

Yielding the commands (appending them to the end of the log instead of processing them) would solve parts of these issues, but not the fork bomb case where the log keeps expanding. Consider a fork bomb that's been running for a few minutes unnoticed. There are likely already thousands if not millions of unprocessed commands for that instance on the log. These will all be yielded to back of the log continuously. New commands will take at least the time that it takes to yield all those commands.

I'm personally more in favor of skipping the commands. This puts the process instance in a state of limbo just like a blacklisted process instance. All we need is a way to start up processing again, and to allow the user to cancel the instance. 

- We could persist the skipped commands. As soon as we want to continue, we write these back to the log and continue processing. This has two downsides: disk usage and fork bomb would continue. So I don't think we should do this.
- We could ignore the skipped commands. As soon as we want to continue, the user can usePI modification / migration to re-start the processing, or they can simply cancel the instance. 

Lastly, I was wondering how you'd keep track of a runtime flag for each process instance? If a user has large state (millions of running PI) then this would consume a lot of memory. Why not persist it like blacklisting?

**Comment by megglos** [comment]
@felix-mueller this is the feature I mentioned in the stakeholder round today in order to allow us to better handle incidents that are caused by malicious processes

**Comment by megglos** [comment]
ZDP-Planning:
- ZDP is picking this up to assess solutions for this asap to allow engineers to handle incidents better going forward

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- The solution of bypassing the log is unrelated to ZPA, as we only build things on top of the log stream.
- We are interested in what happens to the process instance. The state of this PI is our responsibility
- Please reach out to us when you need involvement on deciding what happens with the PI! We are happy to support 🙂 
- We're planning to work on this unless we need to support the ZDP team. As a result we will remove it from our project board.

**Comment by Zelldon** [comment]
First of all, I want to thank you all for your ideas and brain dumps you have done here. :bow: 

I thought about this for a while and also re-read all your comments. If you're interested, I used the following [gdoc](https://docs.google.com/document/d/1NDKjq7osuzYoFd5Jtj9Xhe5_buw8rVU6nLIqBDQwJ74/edit) to summarize and better assess potential solutions. 

I have a potential solution in mind, let me shortly explain it to you.

## Proposal:

I think we can combine several ideas together to get the best out of it. 

It makes sense to have a two-step process implemented, which allows to first ban the instance and secondly (if wished) to cancel the instance.

We provide an API where we can send “ban instance X” request. We access the ZeebeDB with a separate context, as we do with the Exporters, and mark the process instance as banned. I think this should bring us a quick win and feels potentially easy to implement. 

The ban column family is less frequented, which should allows us to already stop the processing for a specific PI, without conflicts. It might make sense to think about the blacklisting cache again, whether we really need it or we just delete it (otherwise we have to update flag).

The banning of the instance should be confirmed with an event on the log, this allows to replicate the state change, and followers can do the same.

Please be aware as soon as the instance is banned, there is right now no way to recover. [The process instance is in limbo, as ](https://github.com/camunda/zeebe/issues/12696#:~:text=I%27m%20personally%20more%20in%20favor%20of%20skipping%20the%20commands.%20This%20puts%20the%20process%20instance%20in%20a%20state%20of%20limbo%20just%20like%20a%20blacklisted%20process%20instance.%20All%20we%20need%20is%20a%20way%20to%20start%20up%20processing%20again%2C%20and%20to%20allow%20the%20user%20to%20cancel%20the%20instance.)[Nico Korthout](mailto:nico.korthout@camunda.com) said so nicely. To handle this differently I see this out of the scope of this feature since we expect it to use only for severe issues where the cluster is otherwise not recoverable (and/or can make no progress).

You may ask why is that actually the case. Because we likely skip commands which are then lost. Furthermore, there is right now no way to remove some PI from the banned instances list. A potential follow-up could be to allow removing instances from that list and applying PI modification (to repair instances).

We could think of [persisting the skipped records into the state](https://github.com/camunda/zeebe/issues/12696#:~:text=We%20could%20persist%20the%20skipped%20commands.%20As%20soon%20as%20we%20want%20to%20continue%2C%20we%20write%20these%20back%20to%20the%20log%20and%20continue%20processing.%20This%20has%20two%20downsides%3A%20disk%20usage%20and%20fork%20bomb%20would%20continue.%20So%20I%20don%27t%20think%20we%20should%20do%20this.), but I would rather not do that, since it could cause severe other issues due to limited space, etc. It is also not clear to me whether the gains are outweighed by the costs since we can also easily run process instance modification to recover such.

The approach above is a combination of multiple others mentioned before, and I feel it is best to not make it too easy to erase customer data, which is why cancelation is/can be the second step. 

Generally, cancelation involves more work, due to the child's cancelation, etc. This should happen in the processing, with a separate command. Since it might fail as well, due to large nested instances, etc, but with this approach it is fine since it is already banned in this case. 

In order to allow the cancelation we need to make sure that we implement the [cancelation for banned instances.](https://github.com/camunda/zeebe/issues/12772)

## Next

As a next step, I would like to spend some time doing a POC and play a bit around with that. Please feel free to raise any concerns with this approach. I'm open for discussions of course.
