### ISSUE TITLE
Don't mutate state through `JobTimeoutTrigger`

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#12797]
We need to make sure that `JobTimeoutTrigger` does not have the ability to mutate state.

`JobTimeoutTrigger.scheduleDeactivateTimedOutJobsTask` is able to mutate state while it should not be allowed to do so. The state may only be mutated by event appliers, see 
- https://github.com/camunda/zeebe/issues/6171

Once this is resolved, we could add an arch unit test to verify that only Event Appliers are using the mutable state.

This is a blocker for:
- #12302

**Comment by oleschoenburg** [comment]
This is related to https://github.com/camunda/zeebe/issues/6521

Also, job backoffs appear to have the same issues. The `JobBackoffChecker` is calls `DbJobState#findBackedOffJobs` which removes entries from the backoff column familiy:

**Comment by oleschoenburg** [comment]
The important invariant is that there is always a one to one mapping from deadline to jobs. As long as we have that, it is clear when to remove or update a deadline and we don't have to rely on the checker to clean up deadlines.

What I missed previously were two things that @korthout kindly cleared up for me:
1. We already have a way to map jobs to deadlines. I thought we'd need a new column family but the information is already available in the column family that maps job keys to job records. It's just not specialized for deadlines.
2. When processing job related events that update deadlines, the event _should_ already include the _current_ job record with the correct deadline.

Note the _"should"_ in there. As of now, **this is not the case for all processors**, and some events are written with the record taken from the command, not the state. And so the `TIMED_OUT`, `RECURRED_AFTER_BACKOFF` and `YIELDED` events contain deadlines that might not match what's in the state. This is already a bug :lady_beetle: that is (at least partially) compensated for by the cleanup of deadlines when the checker runs.


After we fix this bug, the entire job deadline behavior can be described with the following rules:
1. When a job is `ACTIVATED`, the event contains a job record with a new deadline that is added to the deadline column family. It's not necessary to cleanup other deadlines for this job because there are none.
3. When a job transitions away from `ACTIVATED` to a new state or is deleted, the deadline found in the event is removed from the state.
4. A checker process periodically scans deadlines and writes new `TIME_OUT` commands with the job record from the state.
5. When processing a `TIME_OUT` command, verify that command and state deadline match, otherwise reject the command. If they match, write a `TIMED_OUT` event with the job record from the state.
6. On processing the `TIMED_OUT` event the job is made `ACTIVATABLE` again. Rule 3 applies and the deadline is removed.

Rule 5 is a bit open for interpretation. Instead of requiring an exact match between state and command deadline, we could also process the command as long as the state deadline is **not in the future**. This is more lenient and jobs would timeout sooner but still not too soon. This might help with long processing queues though, where a new deadline is set before the first `TIME_OUT` command is processed. 
However, I don't think it is necessary for correctness and it feels like cheating the stream processing rules a little bit. After all, before reaching the `TIME_OUT` command the job could have transitioned to a (hypothetical!) state where it will no longer timeout automatically.
The risk of being not lenient and requiring that command and state deadline match exactly is that with permanently long processing queue, the timeout mechanism would stop functioning if the job would update constantly before the `TIME_OUT` command is processed. I don't see this as a big problem though, as far as I understand this is not breaking any correctness guarantees.
