### ISSUE TITLE
Inter-entry dependencies within a context

### ISSUE THREAD

**Issue by nhomble** [camunda/zeebe#13191]
**Description**

Given a feel expression 

```
{
  expr0: input,
  expr1: expr0 + 1,
  expr2: expr1 + expr1
}
```

When evaluating with the context 
```
{
  "input": 13
}
```

Then the output of this expression is

```
{
      "expr2": 28,
      "expr1": 14,
      "expr0": 13
}
```
--
This was a surprising outcome of the expression. We didn't expect to build dependencies across entries within the same context; however, we think this is really powerful. 

We would like to confirm that this is supported behavior since we had a hard time locating this behavior in the docs. If this is expected, an outcome of this ticket could be to update [the context literal page](https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-context-expressions)

We tested this with zeebe-dmn:8.2.4.

**Comment by nhomble** [comment]
From the samples we see an example of this: https://camunda.github.io/feel-scala/docs/learn/samples/context-samples/ but I think it would be helpful to make this explicit in the reference documentation.

**Comment by saig0** [comment]
> We would like to confirm that this is supported behavior

Yes, I can confirm that this is expected behavior. :+1: 

The behavior is mentioned here: 
- https://docs.camunda.io/docs/components/concepts/variables/#inputoutput-variable-mappings
- https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-context-expressions/#literal

Feel free to suggest your improvements for the docs by creating a PR. :rocket:
