### ISSUE TITLE
Jobs not timing out in v8.1.12

### ISSUE THREAD

**Issue by jaeger401** [camunda/zeebe#13190]
**Describe the bug**

In a self-hosted 8.1.12 Zeebe cluster, unfinished jobs are not timing out when the workers are terminated. As a result, the jobs are not sent back out to new workers and reactivated. They and the process instances that contain them remain stuck permanently.

On Zeebe 1.3.2, we do see the jobs timing out as expected.

**To Reproduce**

We are still working on reproducing the issue. We wanted to alert you right away in the interim, because we've seen this reliably in production and it's a blocker to upgrading.

The observed real world scenario is as follows:
1. Worker grabs a job
1. Worker gets a `SIGTERM` and shuts down without completing or failing the job
1. Worker starts back up
1. Worker is never reassigned the job by the Zeebe cluster

**Expected behavior**

We expect that jobs, when abandoned, would time out and be made available for other workers to pick up.

**Log/Stacktrace**

Below are screenshots from our own internal monitoring tool (similar to Operate), which consumes the Kafka messages from the Kafka Exporter.

Audit log snippet from 1.3.2, which shows the job timing out and then being reactivated and completed:

![Screenshot 2023-06-22 at 12 28 11 PM](https://github.com/camunda/zeebe/assets/2601267/3a4e7dbb-9763-453a-9840-37acc66f51f8)

Audit log snippet from 8.1.12, which shows the job getting stuck without ever timing out:

![image](https://github.com/camunda/zeebe/assets/2601267/a5353b31-6830-4606-b114-d9ef0a1c752e)

**Environment:**
- OS: Linux
- Zeebe Version: 8.1.12 (via official Camunda Docker image)
- Configuration: 
  - Camunda Helm chart 8.1.6 (`zeebe` and `zeebe-gateway` subcharts only)
  - Kafka Exporter 3.1.1
  - [zeebe-client-ruby](https://github.com/zeebe-io/zeebe-client-ruby) 0.17.0 (also tested with 0.19.0)

**Comment by korthout** [comment]
ZPA triage:
- We need to investigate this bug report in more detail
- If bug is valid, it's a high impact (severe regression)
- There are supposed to be tests in place for this, so we wonder how this could be
- @jaeger401 could you inform us:
  - whether you have specific configurations for the ruby client?
  - the timeout specified for the jobs? (in the 1.3.2 logs it appears to be ~1.5m)
  - whether there are logs below the last line for 8.1.12? (they only show ~1m which is not enough for the job timeout in your 1.3.2 example)

**Comment by korthout** [comment]
Thanks for the quick update @jaeger401. Such an example would be amazingly helpful. We've marked this issue's investigation as `upcoming`, and plan to work on it in the next iteration.

**Comment by kevinmook** [comment]
@korthout to give a quick update on our end: we're still working on a reproducible test case using zbctl.

We're finding that whenever we upgrade from 1.3.2 to 8.1.12, often when we redeploy our workers many in progress jobs that were killed mid-process aren't properly timing out and are stuck in limbo.

We're working on using zbctl to reproduce this locally, but unfortunately this isn't happening on our local machines. We have a theory that it's because our local machines are different from our production environment in two important ways: they have a lot less traffic, and locally we only have one instance of Zeebe (acting as both broker and gateway).

We're in the process of writing a pair of bash scripts to test this in our staging environment over the weekend (using zbctl to force jobs to time out at least once before completing them) to see if we can reproduce the issue there.

We'll let you know what we find. We also want to call out that this is a long weekend for us (we're based in the US, and it's the weekend of July 4th), so we might not get back to you until mid next week. This is an important issue for us and we really appreciate you looking into it, and we want to make sure we're responsive to any questions you may have.

**Comment by kevinmook** [comment]
I have to head off for the weekend, but it looks like our test script reproduces it reliably in our staging environment.

Our staging environment has 2 gateways, 3 brokers, 3 partitions, and a replication factor of 3.

If we use zbctl to deploy a bpmn (we used [the getting started bpmn](https://docs.camunda.io/assets/files/gettingstarted_quickstart_advanced-3786a5f1c2a32871b2cc0580bb44266f.bpmn)) and activate the "test-worker" job but never complete it, it doesn't seem to ever time out.

It should be as simple as running the following in a similarly configured Zeebe 8.1.12 cluster:

```bash
zbctl deploy resource camunda-cloud-quick-start-advanced.bpmn

# create a few instances
zbctl create instance camunda-cloud-quick-start-advanced
zbctl create instance camunda-cloud-quick-start-advanced
zbctl create instance camunda-cloud-quick-start-advanced

zbctl activate jobs test-worker --maxJobsToActivate 25 --timeout 1s --requestTimeout 1s
```

Let us know if there's anything else we can do to help or if you still can't reproduce the issue. We can reproduce the issue consistently with our script (100% of the processes get stuck, meaning none of the activated jobs have timed out).

One thing our script does is create a new instance every 1 second, and the consumer (worker) script activates in batches of 25 every 5 seconds.

We're also more than happy to hop on a call (after the long weekend), screenshare, or send over any scripts or configurations if it would help.

Thank you again for looking into this!

**Comment by rusterholz** [comment]
To be clear, in @kevinmook's example above, when you run `zbctl activate jobs test-worker --maxJobsToActivate 25 --timeout 1s --requestTimeout 1s` you should see in the output that three jobs activate, one for each of the created instances. If you then wait, say, 10 seconds, and run `zbctl activate jobs test-worker --maxJobsToActivate 25 --timeout 1s --requestTimeout 1s` a second time, you will see _no_ jobs activate -- where the expected behavior is that the three jobs originally activated would have timed out shortly after the first activation, and should be available again.

**Comment by Zelldon** [comment]
Is it only on 8.1 reproducible or also on another version? (Sorry, I haven't tried yet just to clarify)

Can you also share the configuration of your cluster? I see you use the helm chart, correct?

**Comment by rusterholz** [comment]
Hi @Zelldon, thanks for your response. At present we have only reproduced this bug on 8.1.12. And we have confirmed it is _not_ present on 1.3.2. However we haven't tested it specifically with any other versions. Let me know if that would be helpful.

We are using the camunda-platform helm chart from https://helm.camunda.io, but we disable large portions of that chart (we don't use elasticsearch, tasklist, operate, optimize, identity, or keycloak). Here's a ZIP file containing the output from `helm template` for one of our clusters: [production-blue.yml.zip](https://github.com/camunda/zeebe/files/11959621/production-blue.yml.zip)

In that file you'll see that the docker image we use is `ezcater-production.jfrog.io/zeebe-docker:8.1.12` -- our image simply adds the kafka exporter JAR and a couple of bash scripts on top of the image provided by Camunda. None of those changes should substantially impact Zeebe's operation, as far as we're aware. For your reference, here's a ZIP file containing our Dockerfile, so you can see for yourself: [Dockerfile.zip](https://github.com/camunda/zeebe/files/11959684/Dockerfile.zip)

If this isn't what you're looking for, let me know!

**Comment by korthout** [comment]
>zbctl activate jobs test-worker --maxJobsToActivate 25 --timeout 1s --requestTimeout 1s

@kevinmook I worry that this request (using a timeout of 1s) may have you run into the job timeout resolution threshold of 30s. Giving you the wrong impression that jobs can be timed out after 1s, while in fact, this likely takes longer.

How it currently works is that jobs deadlines are checked once every 30s. For any jobs with an expired deadline, the checker appends a `Job:TIME_OUT` command on the log. The command is processed when the streamprocessor reaches it, resulting in a `Job:TIMED_OUT` event and the job becoming available again for activation.

Whether this 30s resolution is reasonable, or not, it's there currently. There's an old feature request to improve the job timeout resolution 😅:
- https://github.com/camunda/zeebe/issues/5073

Still, this does not explain how jobs may completely stop timing out for extended periods of time, as you've mentioned:
> We've waited hours and the workflows never recover.

**Comment by kevinmook** [comment]
> I worry that this request (using a timeout of 1s) may have you run into the job timeout resolution threshold of 30s. Giving you the wrong impression that jobs can be timed out after 1s, while in fact, this likely takes longer.

@korthout thanks for that clarification! When testing locally against a single Zeebe instance, I did notice it took longer than 1 second for the job to time out and be able to be activated again, but it did eventually time out. However as @jaeger401 mentioned, in our higher envs none of those jobs ever time out (even after an hour+; we noticed some never timing out even days later, stalling our workflows).

**Comment by korthout** [comment]
@kevinmook I've tried to reproduce this, but the jobs simply timeout correctly for me. I have an idea to troubleshoot this.

> **Warning** Please only do this for a test case, as this enables the hidden debug exporter which should not be used in production and can severly affect performance.

Can you add the env var `ZEEBE_DEBUG=true`? This enables the debug exporter which logs each record in JSON format through log4j. Please run your test again, and provide the logs from each broker. This will help me understand what's happening internally.

**Comment by kevinmook** [comment]
An update!! It turns out that this is related to pausing and resuming Zeebe (something we do hourly to support backups).

The following script should allow you to reproduce the issue, even locally with only a single node:

```bash
curl -XPOST http://zeebe:9600/actuator/partitions/pauseProcessing
# wait 5 or so seconds (waiting may not be necessary)
curl -XPOST http://zeebe:9600/actuator/partitions/resumeProcessing

zbctl create instance camunda-cloud-quick-start-advanced
zbctl create instance camunda-cloud-quick-start-advanced
zbctl create instance camunda-cloud-quick-start-advanced

zbctl activate jobs test-worker --maxJobsToActivate 25 --timeout 1m --requestTimeout 10s
# returns 3 jobs

# wait 5 minutes

zbctl activate jobs test-worker --maxJobsToActivate 25 --timeout 1m --requestTimeout 10s
# returns { "jobs": [] }
```

**Comment by korthout** [comment]
I'm able to reproduce it like this! Thanks @kevinmook for the reproducible example and the pleasant communication on slack 🙇 

This means the workaround is to not pause processing, although that may not be a possible workaround for all users. We'll have to prioritize this again with the new knowledge.

**Comment by Zelldon** [comment]
Sorry to chime in, as I was anyway looking in this area today. I think I know what the issue is.



On pause we "cancel the timer" (set the flag to false to not reschedule) https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java#L55

https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java#L71-L73

On resume the check is wrong


https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java#L60

**Comment by korthout** [comment]
You're right @Zelldon. On resume the checker should simply make an initial pass to see if there are any jobs that have exceeded their deadline.

We can simply remove the if statement from the onresume method.

Should be straightforward to test as well, so sizing this as x-small.

Until a patch is available, @kevinmook you might consider exploring backup without downtime, which is available since 8.2 ([docs](https://docs.camunda.io/docs/self-managed/backup-restore/backup-and-restore/)). This only requires pausing exporting not pausing the stream processing.

**Comment by korthout** [comment]
I've added it to discuss at the upcoming iteration planning for Zeebe Process Automation Team.

**Comment by kevinmook** [comment]
@korthout and @Zelldon thank you both, we really appreciate the help, discussion, and super quick fix!
