### ISSUE TITLE
Align with Docker base image best practices

### ISSUE THREAD

**Issue by cmur2** [camunda/zeebe#13214]
**Description**

Related to https://github.com/camunda/product-hub/issues/1356 all C8 components must adhere to the [best practices](https://confluence.camunda.com/display/HAN/Dockerfile+Base+Images) by implementing them or being an (approved+documented) exception.

According to the current [Adoption Status](https://confluence.camunda.com/display/HAN/Dockerfile+Base+Images#DockerfileBaseImages-AdoptionStatus) for Zeebe this means:

- introduce [strict pinning](https://confluence.camunda.com/display/HAN/Dockerfile+Base+Images#DockerfileBaseImages-StrictVersionPinningforBaseImages) by changing https://github.com/camunda/zeebe/blob/main/Dockerfile
- check whether Alpine can be adopted or provide written reasoning why it is not feasible

**Comment by npepinpe** [comment]
We've already started work via https://github.com/camunda/zeebe/issues/12959

As a first step we'll move to the Alpine based Temurin image. Later we can investigate building our own Java base image on top of Alpine, if only to keep us more up to date with base image security fixes, as each additional layer on top of a base image adds delays for security patches to get added.

I did want to challenge a few things there, if you have some time though (e.g. pro-actively apply security patches ourselves to our own Java base image at the cost of reproducibility).

**Comment by cmur2** [comment]
> As a first step we'll move to the Alpine based Temurin image.

Nice :+1: I think if it is Alpine 3.18 based there shouldn't be too much problems in C8 SaaS but you'll probably test it carefully, anyways.

> I did want to challenge a few things there, if you have some time though (e.g. pro-actively apply security patches ourselves to our own Java base image at the cost of reproducibility).

Sure, I'm available :) I think manually applying security patches can have more upsides than downsides in your usecase, so definitely open to that :+1:

**Comment by npepinpe** [comment]
So the easy way of applying patches is simply to update installed packages to their latest version. Downside is:

1. It's blindly updating everything, not just security patches. It seems Alpine doesn't support making a distinction between security updates and other kinds.
2. Builds won't be reproducible anymore (unless we vendor the APKINDEX tar ball =/)

For 1, well, there isn't all that much installed in the first place, so maybe it's acceptable. For 2, I can't remember the last time we wanted to reproduce a build, except within very short time frames, so unclear how much value we get from that currently.

**Comment by megglos** [comment]
moving to ready as @npepinpe is already on it

**Comment by npepinpe** [comment]
Another question (though this may be more a product decision) is, do we consider moving from an Ubuntu base to Alpine a breaking change?

For example, doing this _will_ break the Helm chart, as it currently overwrites the startup command with a `bash` script - Alpine, by default, does not include `bash`, but `sh`.

We can update the Helm chart, but this may break existing user deployments, or anybody who was building on top of our own image.

**Comment by hown3d** [comment]
@npepinpe adding bash in the alpine image by apk would fix that issue at first to not introduce breaking changes. 
I would expect the new alpine based image to work without changes in Kubernetes configuration.

**Comment by npepinpe** [comment]
Hey @hown3d , thanks for the perspective. Bash was just an example though, there might be other changes which would break existing deployments, since ubuntu based images contain about 3 times the number of utilities, and who knows what everyone is relying on.

Since one of the goals here is to reduce effort related to CVE maintenance (including informing users how certain flagged vulnerabilities are irrelevant for us), reinstalling everything is counterproductive (of course we could say only bash is important and everything else is acceptable :shrug:)

At some point I think we'll have to bite the bullet. The problem is I don't have any real data on how many builds would break by switching to an Alpine based image.

Maybe it's enough to, say, have an image which works out of the box with the existing Helm chart, and we can remove bash in the future. I don't think bash is a big source of CVEs, so should be fine.

**Comment by hown3d** [comment]
If it's about CVE maintenance, maybe check out the images from [chainguard](https://github.com/chainguard-images/images). They provide secure and minimal images, that contain as close to 0 CVEs. The images are based on the [Wolfi OS project](https://github.com/wolfi-dev/os).

**Comment by npepinpe** [comment]
I evaluated the Chainguard images [here](https://github.com/camunda/zeebe/issues/12959). I agree they likely have less vulnerabilities, but it's also a bit of a chicken and egg, where most vulnerability scanners simply have no information about the base image and it's unclear how well it gets scanned for CVEs. Plus, extending them is somewhat painful (much like Google's Distroless) due to the steep learning curve behind apko and melange.

At any rate, the issue with breaking changes remains the same, whether it's chainguard or alpine based :shrug:

**Comment by hown3d** [comment]
Indeed, it is accurate to say that extending it can pose some challenges. 
My suggestion would be to utilize the [wolfi-base](https://edu.chainguard.dev/chainguard/chainguard-images/reference/wolfi-base/overview/) image, which includes **apk** and **busybox** enabling the installation of packages. Using the wolfi-base image would allow to build and extend the image by Dockerfile.
As wolfi employs the APKINDEX, security scanners should also extract data from it. 

A downside would be that it would be neccessary to install jre during build.

It is worth noting that there are still lingering breaking changes by those changes, as you rightly mentioned.

**Comment by npepinpe** [comment]
> A downside would be that it would be neccessary to install jre during build.

To be fair, I was thinking we might do this in the long run anyway, if only to keep our base image faster up to date with security patches (since the official JRE images are often behind by up to a month).

**Comment by npepinpe** [comment]
Happy to get feedback on the PR. I created it as a PR, but I actually meant to make it a draft PR to get some early feedback :sweat_smile:
