### ISSUE TITLE
Allow custom job worker executors

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13428]
**Is your feature request related to a problem? Please describe.**

I would like to use virtual threads for my job worker executor, and also measure the time a job spends waiting, once submitted, before it's processed. Right now, all I can configure is the number of threads in the job worker's pool. Additionally, that thread pool is always global per client.

**Describe the solution you'd like**

I'd like to use a thread-per-task execution model, relying on virtual threads for execution. By providing my own executor I can also instrument it more easily.

**Describe alternatives you've considered**

- I can re-implement the job worker myself - cumbersome, I'd rather not do that.
- I can instrument the job handler. This doesn't count time spent in the executor's queue, however.
- I can have the job handler forward it to my own custom executor. This is the best workaround, but it feels unnecessary.

**Additional context**

This is very low priority, but it's definitely a nice to have :)

**Comment by koevskinikola** [comment]
ZPA triage:
- Setting the `scope/clients-java`. The issue deals with improving performance and UX, so adding the appropriate labels.
- The Java client still supports Java 8, which conflicts with this feature.
- @npepinpe we're closing this issue since we don't see a possibility in implementing it in our Java client. If you have any ideas on how to implement this, please provide them. If not in the official Java client, maybe they can be implemented in community projects.

**Comment by npepinpe** [comment]
I'm not sure how allowing custom executors for job workers conflicts with Java 8, but I guess me saying Virtual Threads made it sound scary ;)

If I just open a PR for it, will you consider it? It's what, 20 lines of code?

**Comment by npepinpe** [comment]
OK so this was slightly more than 20 lines of code, but still not too big. Mostly tests and comments :upside_down_face:
