### ISSUE TITLE
Gateway readiness fails when tls enabled

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#13431]
**Describe the bug**

When tls enabled on gateway for [secure client communication](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/security/secure-client-communication/), readiness check fails. 

<details><summary>Failed health status</summary>
 <p>

```
{
   "components" : {
      "diskSpace" : {
         "details" : {
           ....
         },
         "status" : "UP"
      },
      "gatewayClusterAwareness" : {
         "status" : "UP"
      },
      "gatewayPartitionLeaderAwareness" : {
         "status" : "UP"
      },
      "gatewayResponsive" : {
         "details" : {
            "error" : "java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\nChannel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]",
            "healthZeebeClientProperties" : {
               "requestTimeout" : "PT0.5S",
               "securityProperties" : {}
            },
            "timeOut" : "PT0.5S"
         },
         "status" : "DOWN"
      },
      "gatewayStarted" : {
         "status" : "UP"
      },
      "livenessGatewayClusterAwareness" : {
         "details" : {
            "derivedFrom" : "ClusterAwarenessHealthIndicator",
            "lastSeenDelegateHealthStatus" : {
               "status" : "UP"
            },
            "maxDowntime" : "PT5M",
            "wasEverUp" : true
         },
         "status" : "UP"
      },
      "livenessGatewayPartitionLeaderAwareness" : {
         "details" : {
            "derivedFrom" : "PartitionLeaderAwarenessHealthIndicator",
            "lastSeenDelegateHealthStatus" : {
               "status" : "UP"
            },
            "maxDowntime" : "PT5M",
            "wasEverUp" : true
         },
         "status" : "UP"
      },
      "livenessGatewayResponsive" : {
         "details" : {
            "derivedFrom" : "ResponsiveHealthIndicator",
            "lastSeenDelegateHealthStatus" : {
               "details" : {
                  "error" : "java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\nChannel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]",
                  "healthZeebeClientProperties" : {
                     "requestTimeout" : "PT5S",
                     "securityProperties" : {}
                  },
                  "timeOut" : "PT5S"
               },
               "status" : "DOWN"
            },
            "maxDowntime" : "PT10M",
            "wasEverUp" : false
         },
         "status" : "DOWN"
      },
      "livenessMemory" : {
         "details" : {
            "threshold" : 0.01
         },
         "status" : "UP"
      },
      "livenessState" : {
         "status" : "UP"
      },
      "ping" : {
         "status" : "UP"
      },
      "readinessState" : {
         "status" : "UP"
      }
   },
   "groups" : [
      "liveness",
      "readiness",
      "startup"
   ],
   "status" : "DOWN"
}
```

</p>
</details>

Both `gatewayResponsive` and `livenssGatewayResponsive` fails because of some SSL error.   

This was unnoticed before because readiness check was disabled by default in camunda platform helm until 8.2. From 8.2 it is enabled by default. 

**To Reproduce**

Start a single gateway with TLS enabled as documented [here](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/security/secure-client-communication/). And then query `http://gateway-host:9600/actuator/health`.

**Expected behavior**

Health and readiness check should work with TLS enabled.

**Environment:**
- Zeebe Version: All versions (reproduced with 8.0.x, 8.1.5, and 8.2.7)

related to https://jira.camunda.com/browse/SUPPORT-17529 
https://jira.camunda.com/browse/SUPPORT-16945

**Comment by npepinpe** [comment]
See https://github.com/camunda/zeebe/issues/11799#issuecomment-1558773952

I guess it was already linked to a support issue. Workaround is to disable the check by setting the following env var:

```
MANAGEMENT_HEALTH_GATEWAY-RESPONSIVE_ENABLED=false
```

**Comment by deepthidevaki** [comment]
I will leave it open for easy visibility. I searched for open bugs for this, but couldn't find any.

Please close both issues when it is fixed.

**Comment by megglos** [comment]
Hey @deepthidevaki ,

as I try to follow-up on this with the distribution team, the only official config exposed relating to TLS on the helm chart is enabling it on the ingress https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L595-L600 .

In that support case tls was enabled on the zeebe pod by the customer via setting `ZEEBE_GATEWAY_SECURITY_ENABLED` etc., so it’s kind of special and not a general issue/breaking change with the helm charts intended way to enable TLS. Where if tls is enabled on the ingress the check should still work as TLS terminates at the ingress and the health check directly accesses the pod endpoint, do I understand this correctly?

I would then conclude no change to the helm chart is needed and assume likelihood of others hitting that regression is on the lower end ^^ If someone sets up TLS termination manually on the pod, they can make use of the workaround until this issue is resolved on the zeebe side.

**Comment by deepthidevaki** [comment]
> the only official config exposed relating to TLS on the helm chart is enabling it on the ingress

@megglos 
Is that the recommended way to do it? If so, we can also recommend it to the customer. Is there any documentation on it? The only [documentation](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/security/secure-client-communication/) I found is to configure it on Zeebe gateway. 

> I would then conclude no change to the helm chart is needed and assume likelihood of others hitting that regression is on the lower end ^^ If someone sets up TLS termination manually on the pod, they can make use of the workaround until this issue is resolved on the zeebe side.

:+1:

**Comment by npepinpe** [comment]
Can we just get rid of this `ResponsiveHealthIndicator`? I don't think it really purposefully demonstrates that it's responsive:

1. The user can query the topology themselves to see if the service is working
2. The user queries the health endpoint, which queries the topology, to see if the service is working

It just seems like extra steps. I understand that the idea is for things like load balancers to not send requests to an unresponsive gateway, but I would argue that it really doesn't bring that much value for the added complexity, since the gateway client has to be configured for all possible gateway configuration (TLS, authentication, etc.) Plus it only checks that the gRPC server serving the right service, but not things like "can you actually send requests to brokers?" or the likes. It doesn't even do anything with the topology itself :shrug:

**Comment by oleschoenburg** [comment]
Maybe we should just implement the gRPC [health checking protocol](https://grpc.github.io/grpc/core/md_doc_health-checking.html) and then recommend [gRPC probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#probe-check-methods)?

**Comment by npepinpe** [comment]
Surprise surprise, we already do serve the gRPC health check protocol! But it's very basic, only reporting whether the gateway started or is shutting down. But it'd be cool to extend it :+1:

**Comment by oleschoenburg** [comment]
Ah TIL :+1: 
I guess this would not 100% replace the `ResponsiveHealthIndicator` anyway because we'd not do a topology request that way. 

I'm not attached to the `ResponsiveHealthIndicator` so just removing it for now also sounds good to me.

**Comment by megglos** [comment]
:information_source: What determines the liveness/readiness of the Gateway as of now?

readiness: `StartedHealthIndicator`

[liveness](https://github.com/camunda/zeebe/blob/main/dist/src/main/resources/application-gateway.properties#L9):
`livenessGatewayResponsive` ==> ResponsiveHealthIndicator  (doing a topologyRequest on the grpc endpoint of the pod)
`livenessGatewayClusterAwareness`  ==> gateway::getStatus
`livenessGatewayPartitionLeaderAwareness`  ==> doing topologyManager.getTopology and checking if there is a leader known for every partition
`livenessMemory`  => checking if JVM has at least 10% free memory (actually intended was >1%, according to the initial task https://github.com/camunda/zeebe/issues/4339 is that a bug? :smile: )

I see the following options going forward:

:one: Make sure users can configure the internal zeebe client to work properly in such scenarios (there is actually dedicated config present for tls and oauth config)
:heavy_plus_sign: Pro:
- the check’s semantics stay as they are

:heavy_minus_sign: Con:
- it seems still like a weird UX, I may have to configure a client for my gateway within the Gateway? Likely to be missed and causing questions and support cases
- the gateway being able to connect to it’s own GRPC port does not mean that port is properly reachable from outside the pod

:wrench: Effort:
- improve docs, hoping users will pick that up without needing help :crossed_fingers:
- potentially extending the helm chart for allowing to config the client

:two: We remove the ResponsiveHealthIndicator as suggested by Nicolas 

:heavy_plus_sign: Pro:
- less complexity in our liveness check
- grpc readiness/connectivity can be checked via a grpc_health_probe via the existing GRPC health endpoint which exists since this PR (thanks to @npepinpe for raising that!)
  - as of now there is no real readiness probe implemented, that was decided [here](https://github.com/camunda/zeebe/issues/4339#issuecomment-627277532), the ready endpoint is still used by e.g. the helm chart but it equals the startup probe semantics, we may follow-up using the grpc health check as readiness endpoint
- cluster awareness and connectivity is already covered by the other checks

:heavy_minus_sign: Con:
- semantics of the actuator liveness probe changes, needs announcement
- don’t like the idea of backporting it, effectively we only lose the grpc connectivity being part of liveness though so it might be the best compromise to prevent new issues related to it

:wrench: Effort:
- 💥 ResponsiveHealthIndicator
- docs announcement + update guide
- follow-up with controller and distribution team of actually adding a grpc probe
