### ISSUE TITLE
Cannot process record due to process deployed version being null.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/zeebe#14309]
**Describe the bug**

The issue seemed to happen while processing. The exporter could not process the record as the DeployedProcess.getVersion() returns null, because ProcessState.getLatestProcessVersionByProcessId()" is null. 

```
Expected to process record 
'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE, authorization=UNKNOWN}, value={"resources":[],"processesMetadata":[{"bpmnProcessId":"Process_Connect_Intra","version":4,"processDefinitionKey":2251799813740831,"resourceName":"diagram_connect_intra.bpmn","checksum":"vE026arBq5Hh09ilkSj4Cw==","isDuplicate":false,"tenantId":"<default>"}],"decisionRequirementsMetadata":[],"decisionsMetadata":[],"tenantId":"<default>"}}' 
without errors, but exception occurred with message 
'Cannot invoke "io.camunda.zeebe.engine.state.deployment.DeployedProcess.getVersion()" 
because the return value of "io.camunda.zeebe.engine.state.immutable.ProcessState.getLatestProcessVersionByProcessId(org.agrona.DirectBuffer)" is null'.
```

**To Reproduce**

Dont know as of moment, the previous behavior in the [logs](https://console.cloud.google.com/logs/query%3Bquery=logName:%22stdout%22%0Aresource.type=%22k8s_container%22%0Aresource.labels.container_name=%22zeebe%22%0Aresource.labels.project_id=%22camunda-cloud-240911%22%0Aresource.labels.namespace_name=%22179a54e4-45b8-4850-8ff8-7caca6407a47-zeebe%22%0Aresource.labels.cluster_name=%22prod-worker-4%22%0Aresource.labels.location=%22australia-southeast1%22%0Aresource.labels.pod_name=%22zeebe-1%22%0A%3BpinnedLogId=2023-09-14T00:20:12.977565274Z/az5svd4vg7gfo3zz%3BcursorTimestamp=2023-09-14T00:21:43.373199577Z%3BstartTime=2023-09-13T23:50:42.977Z%3BendTime=2023-09-14T00:50:42.977Z?project=camunda-cloud-240911) seems normal at first glance.

**Log/Stacktrace**

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.deployment.DeployedProcess.getVersion()" because the return value of "io.camunda.zeebe.engine.state.immutable.ProcessState.getLatestProcessVersionByProcessId(org.agrona.DirectBuffer)" is null
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.isLatestProcess(StartEventSubscriptionManager.java:68) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.tryReOpenStartEventSubscription(StartEventSubscriptionManager.java:58) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processDistributedCommand(DeploymentCreateProcessor.java:108) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:31) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
```

**Environment:**
- OS: 
- Zeebe Version: 8.3.0-alpha6
- Configuration:

**Comment by megglos** [comment]
ZDP-Triage:
- happened on a trial cluster, the user deleted the cluster after
- this seems to be a processing error that is gracefully handled and will result in a command rejection
- it actually happened while processing not exporting
- the causing error in the engine needs investigation as it is a potential regression
- might be related to start event subscriptions
- should be raised to ZPA for investigation on the actual cause, could be critical if it's indeed a regression

**Comment by megglos** [comment]
@koevskinikola could this be a regression related to Multi Tenancy?

**Comment by korthout** [comment]
ZPA Triage:
- should be investigated before the 8.3 release
- let's mark this as critical, because this appears to block deploying and can lead to partition inconsistency
- #14366 appears to have the same root cause

**Comment by korthout** [comment]
I had a look into this yesterday. I was not yet able to reproduce or even to understand how this could happen, but I'll share my findings so far.

🧺 I started by collecting similar issues:
- https://github.com/camunda/zeebe/issues/14366
- https://github.com/camunda/zeebe/issues/14309
- https://github.com/camunda/zeebe/issues/14055 (3 weeks ago)
- https://github.com/camunda/zeebe/issues/11734 (Feb 17th)
- https://github.com/camunda/zeebe/issues/11414 (Jan 16th)

🔍 All these issues have `getLatestProcessVersionByProcessId` in their stacktrace, but they come from different places:
- [Cancel process instance](https://github.com/camunda/zeebe/issues/14366) on 8.3.0-alpha6
- [Create deployment](https://github.com/camunda/zeebe/issues/14055#issue-1873096848) (distributed to another partition using command distribution) on 8.3.0-alpha4
- [Call activity](https://github.com/camunda/zeebe/issues/14055#issuecomment-1700454899) on 8.2.12
- [DeploymentDistributeProcessor](https://github.com/camunda/zeebe/issues/14055#issuecomment-1700454899) on 8.2.12

🤔 While similar, the last two on 8.2.12 may have a different root cause, as 8.3.0 introduces several related topics:
- Create deployment over command distribution
- Delete process using resource deletion

🕵️ After collecting this, I wondered: could a newer process version be distributed to another partition before the older version is distributed to that same partition?
- Yes, individual commands sent to another partition are unreliable, which is why we've built command distribution to provide a reliable mechanism for distributing commands
- However, this does not lead to the failure
  - I adjusted the engine not to send the deployment of the first version of a process to other partitions
  - and wrote a multi-partition test case that deploys two versions of processes
  - the exception is not thrown because version 2 that is distributed is [first persisted to state](https://github.com/camunda/zeebe/blob/09f444092d8f42e402449eb2cde0a546b781a4c0/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L109-L111) before it is looked up as being the last version, and so it doesn't return null

🔬 Looking more closely [at the code](https://github.com/camunda/zeebe/blob/09f444092d8f42e402449eb2cde0a546b781a4c0/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/StartEventSubscriptionManager.java#L57-L58), I wondered: could it be that a non-executable process would be distributed but not stored in state and so could not be found?
- No, even when pooled together with executable processes, the non-executable process is not distributed. It is not extracted into the process metadata.

And this is where I stopped. 🔚

**Comment by Zelldon** [comment]
@korthout happened on PROd again. Might be worth to investigate the running cluster.

https://console.cloud.google.com/errors/detail/CMHx49mjl8qiRQ;service=zeebe;time=P7D?project=camunda-cloud-240911

**Comment by nicpuppa** [comment]
@Zelldon get we get a snapshot of the state ?

**Comment by Zelldon** [comment]
@nicpuppa see slack please handle [it their](https://app.slack.com/client/T0PM0P1SA/C05TBCABJUS) I have to other medic duties still to do

**Comment by nicpuppa** [comment]
data directory can be found `[here](https://drive.google.com/drive/folders/16VnPRGYisXY-0weDKmMLRIhyXlZd5TPw)`

**Comment by remcowesterhoud** [comment]
## Root-cause

It's an issue with the caching of process versions. There is a scenario in which different keys in the cache reference the same value object. Because of this versions of different processes can influence each other.

1. If we deploy a process we store it in the state using a shared object (nextVersion) (this name is still bad btw)
2. If get the version info we search in the cache. If we can't find it we get it from the state and store this in the cache.
3. Since getting it from the state wraps the values in the same object it means the entries in the cache all reference this same object. So if the object changes it changes for all entries.

We can fix it by making sure we copy the value from the state before storing it in the cache.

**Reproducible test case**

```java
  @Test
  public void x() {
    // given
    final var process1V1 = creatingProcessRecord(processingState, "process1").setVersion(1);
    final var process1V2 = creatingProcessRecord(processingState, "process1").setVersion(2);
    final var process2V1 = creatingProcessRecord(processingState, "process2").setVersion(1);
    final var process2V2 = creatingProcessRecord(processingState, "process2").setVersion(2);
    final var process2V3 = creatingProcessRecord(processingState, "process2").setVersion(3);

    // when
    processState.putProcess(process1V1.getKey(), process1V1);
    processState.putProcess(process2V1.getKey(), process2V1);
    processState.putProcess(process2V2.getKey(), process2V2);
    processState.clearCache();
    processState.putProcess(process1V2.getKey(), process1V2);
    processState.putProcess(process2V3.getKey(), process2V3);

    // then
    assertThat(processState.getNextProcessVersion("process1")).isEqualTo(2);
  }
```
