### ISSUE TITLE
TransientState is not migrated any more

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14331]
**Describe the bug**

With the recent changes for #14252 we moved the migration to the partition installation, this in consequence means we migrate the state separately and throw away the state objects afterward.

It looks like some migration intend to migrate the transient state as well, not sure why. 

See https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/state/migration/DbMigrationState.java#L276-L277

I'm not sure whether this is really a problem, needs to be discussed. My current assumption is that when we really need it we refill the transient state, on replay for example. 

In order to overcome this (if it is really necessary) we could reuse the migrated state and pass it to the engine (which is created in one of the next transition steps).

@korthout maybe you know or can assess whether this is an issue.

\cc @romansmirnov

**To Reproduce**
See above

**Expected behavior**

Not sure.

**Comment by korthout** [comment]
This migration task predates 8.0. As it's not possible to update older versions to 8.x, we can remove any migration tasks that upgrade to versions `<= 8.0`

As there are only a few migration tasks since 8.0, we quickly checked and didn't find any that attempt to migrate transient state.

I'll open a new issue to remove the old migration tasks (pre 8.0)

**Comment by Zelldon** [comment]
Awesome thanks @korthout
