### ISSUE TITLE
Add Form Deployment support to Go client

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#14371]

**Comment by berkaycanbc** [comment]
Today, I worked on the issue and couldn't update the mock gateway file. Asked help from @Zelldon and still we couldn't get it to work. Since, @npepinpe has more context about this, we will wait him to be back to finish the implementation.

Marking this one as blocked now. If we do not make a progress on this, we can even think of closing it since the `DeployResource` gRPC in Go client already working for forms but no proper response returned only.

Related branch I created: https://github.com/camunda/zeebe/tree/14371_add_form_deployment_support_to_go_client

Cc: @nicpuppa

**Comment by koevskinikola** [comment]
@Zelldon @berkaycanbc a lot of the code there is autogenerated. I believe I worked on it as part of the `EvaluateDecision` epic.

Let me know if you need my help.

One thing to note is that something might have changed after the update of the Go version.

**Comment by npepinpe** [comment]
I had a look at the branch Berkay linked, and there's a few things:

1. The generated gateway code is mangled, and lots of things were removed, notably the two interfaces we were mocking: `GatewayClient` and `Gateway_ActivateJobsClient`.
2. This [issue](https://github.com/golang/mock/issues/494) does a good job of explaining the problem.

So I would propose the following:

1. Restore the gateway generated code - or is it supposed to be like this?
2. Either run in source mode (e.g. `mockgen -source=pkg/pb/gateway.pb.go GatewayClient,Gateway_ActivateJobsClient`), or add the following file to the `internal/mock_pb` package:

<details><summary>internal/mock_pb/mockgen.go</summary>

```go
//go:generate echo $PWD - $GOPACKAGE - $GOFILE
//go:generate mockgen -build_flags=-mod=mod -package $GOPACKAGE -destination mock_gateway.pb github.com/camunda/zeebe/clients/go/v8/pkg/pb GatewayClient,Gateway_ActivateJobsClient
package mock_pb
```

</details>

You can then just generate code in the future using `go generate ./...` from the module root  (i.e. `clients/go` folder). Switching from `-mod=mod` to `-mod=vendor` in the build flags will fix the issue where the mockgen/model package isn't vendored. Note that `source` mode gives you more readable generated code, but may not work well with templating/generics in the future.
