### ISSUE TITLE
Naming convention in ZeebeClientConfiguration.jobWorkerExecutor() differs from other properties

### ISSUE THREAD

**Issue by sbuettner** [camunda/zeebe#14459]
## Description 
While reviewing the PR to upgrade the `spring-zeebe` client to the latest [alpha](https://github.com/camunda-community-hub/spring-zeebe/pull/469#discussion_r1336281937) we found out that the [naming convention](https://github.com/camunda/zeebe/blob/b1a13e14494322053dd6d42f477854357ed5ec3c/clients/java/src/main/java/io/camunda/zeebe/client/ZeebeClientConfiguration.java#L110) for the `jobWorkerExecutor` property differs from the other properties as they follow the java bean convention.  

## Expectation
The expectation was that the naming convention is the same for all config properties in the form of `getPropertyName()`.
  
cc @1nb0und

**Comment by berkaycanbc** [comment]
- This makes total sense. It is better if we keep API naming conventions stable. 👍 
- Since this is not a blocker but an improvement, marking it as later.
- Also, this is a good first issue.

**Comment by noveshb** [comment]
Hi @berkaycanbc, I am starting my open source contribution, I think I can work on this issue, need to change the name of the function in ZeebeClientConfiguration.java interface and its implementation or usage such that it follows the naming convention i.e. jobWorkerExecutor() to getJobWorkerExecutor() and ownsJobWorkerExecutor() to getOwnsJobWorkerExecutor()
Can i pick this up as my first issue ?

**Comment by noveshbainsla** [comment]
Hi @berkaycanbc, I am starting my open source contribution, I think I can work on this issue, need to change the name of the function in ZeebeClientConfiguration.java interface and its implementation or usage such that it follows the naming convention i.e. jobWorkerExecutor() to getJobWorkerExecutor() and ownsJobWorkerExecutor() to getOwnsJobWorkerExecutor()
Can i pick this up as my first issue ?

**Comment by berkaycanbc** [comment]
I double checked with the team if we should directly change the name of the existing methods. Since mentioned changes are part of the public Java Client API, we should provide backward compatibility there. It is not possible to change existing method names but we can add new ones and call the existing ones.

At this point, such name change is only an improvement but not a blocker. Therefore, I am closing this issue.

@sbuettner Please re-open this issue if you think it is still valuable to have the name change.

@noveshbainsla thanks for considering your first contribution! Since I am closing this one, please take a look at other `good first issue` labeled ones and feel free to ask if it is still available. 👍
