### ISSUE TITLE
Form events are not replayed

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15194]
This could cause problem in `replay` mode, Form events will be missed and not added to the state.

**Comment by korthout** [comment]
I've quickly verified the issue, and this can lead to the loss of the deployed Forms on 8.3 and 8.4.0-alpha1.

In that case, existing jobs of User Tasks may still be referring to the key of that form, but it no longer exists in Zeebe. 

I'm looking into what happens when instances activate User Task with form id set after the replay missed the Form events.

**Comment by korthout** [comment]
In short: **The impact is a potential loss of deployed form**. 

When that happens, the user will notice because newly activated User Tasks will raise an Incident that the Form cannot be found.

User must redeploy the form to fix the problem, but the bug can re-occur afterward until we have a fix.

**Comment by korthout** [comment]
Marking it as sev high because users can recover easily. Loss of data is very limited. And chance of occurrence is low. A fix is on the way though.
