### ISSUE TITLE
Expose partitionId on exporter startup

### ISSUE THREAD

**Issue by abbasadel** [camunda/zeebe#15418]
**Is your feature request related to a problem? Please describe.**
We are currently working on creating a custom exporter. We need the `controller` provided on the `open` method of the exporter to expose two additional fields:
 * `partitionId` of the exporter
 * last exported record position, that is updated on calling the `updateLastExportedRecordPosition` method

These are required to allow synchronization of the exported data with the downstream system on restart of the exporter. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

Our current workaround is to use reflection as follows:
 
```java
 
private int extractPartitionId(Controller controller) {
        try
{             //TODO: get a new build from Camunda that exposes partitionId on the Controller             //controller is type ExporterContainer             //((ExporterContainer)controller).actor.actor.partitionId             Class<?> exporterContainer = Class.forName("io.camunda.zeebe.broker.exporter.stream.ExporterContainer");             Field actorControlField = exporterContainer.getDeclaredField("actor");             actorControlField.setAccessible(true);             ActorControl actorControl = (ActorControl) actorControlField.get(controller);            Field actorExporterDirectorField = ActorControl.class.getDeclaredField("actor");             actorExporterDirectorField.setAccessible(true);             ExporterDirector exporterDirector = (ExporterDirector) actorExporterDirectorField.get(actorControl);             Field partitionIdField = ExporterDirector.class.getDeclaredField("partitionId");             partitionIdField.setAccessible(true);             return (int) partitionIdField.get(exporterDirector);         }
catch (NoSuchFieldException | IllegalAccessException | ClassNotFoundException e)
{             throw new RuntimeException(e);         }
    }

```
**Additional context**
[SUPPORT-19375](https://jira.camunda.com/browse/SUPPORT-19375)

**Comment by koevskinikola** [comment]
ZPA triage:
- @camunda/zeebe-distributed-platform as this is a feature request relating to the Exporter API for implementing a custom exporter, would you mind having a look at it?

**Comment by npepinpe** [comment]
ZDP triage:
- There were concerns that exposing the partition ID will weaken the exporter's idempotency guarantees. 
- It's a fairly small FR, let's put it in the next planning cycle and see.

**Comment by npepinpe** [comment]
Proposal:

- [ ] Add a `io.camunda.zeebe.exporter.api.context.Context#getPartitionId` method which provides the partition ID to the exporter on configuration
- [ ] Add a `io.camunda.zeebe.exporter.api.context.Controller#getLastExportedRecordPosition()`, which returns the last exported record position. This should return the initial one on open, and also reflect updates during the exporter lifetime. _For now we can omit the attached metadata_, because there's already another method to fetch that.

It's fine to add to the context because we _always_ configure an exporter before we open it, and we configure _every time_, not just once initially. So a user who wants to use the partition ID in the `open` method would do:

```java
public final class MyExporter implements Exporter {
  private int partitionId;

  @Override
  public void configure(final Context context) {
    partitionId = context.getPartitionId();
  }

  @Override
  public void open(final Controller controller) {
    // do something with the partitionId
  }
}
```

Since the context is information about the exporter runtime, and the controller is about interaction from the exporter to the broker, it makes more sense to pass such info in the context.
