### ISSUE TITLE
Limit the number of element in the process caches

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15533]
**Describe the bug**

When deploying a process, new models are added to the deployment cache, which is kept in memory. The deployment cache is right now unbounded which causes the broker to fail after a certain time. Recently we faced an [incident](https://camunda.slack.com/archives/C068P5KSSGP)  where a customer deployed a lot of processes and the broker was stuck in a restart loop

**Expected behaviour**

Having a bounded cache, so that the cache size does not grow indefinitely and cause the broker to crash. We should implement a similar approach to [Decisions Cache](https://github.com/camunda/zeebe/blob/6cbc4ff2500e751acf6a9b8a12e91740e6ab9bfe/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbDecisionState.java#L96), by keeping a certain amount of data inside the cache, and evicting the less used elements when we reach the max size

**Comment by Zelldon** [comment]
As already stated above by Nic and written by me in the incident channel:

> When deploying new models are added to the deployment cache, which is kept in memory. The deployment cache is right now unbounded which causes the broker to fail after a certain time (when enough models are deployed). The broker will start with a clean cache. Process models are then added if PI is executed or new deployment is created.

To prove this I also checked the heap.dumps which we have found in the related broker nodes. You can find one [here](https://drive.google.com/drive/folders/1ohaIrSB7fUwNUtaSDsgdOPJ6Sn-cAz_R) 

----

For example we have `processesByProcessIdAndVersion = java.util.HashMap#21089 : 3,690 elements`

![maps](https://github.com/camunda/zeebe/assets/2758593/24447f1a-a7ff-4b01-b6bb-74a976e7b9d8)

This is a two level map, first the processID, then the version and then the actual value (the process)

Already at the first entry we can see that the processIds are quite large. 
![processIds](https://github.com/camunda/zeebe/assets/2758593/78b8d19f-9329-4b16-a837-ab05d83d9d7f)


When checking the actual value we see that one of 8 has a resource with size ~40k bytes.
![deployments](https://github.com/camunda/zeebe/assets/2758593/dcddfa3b-ce9d-4ae2-9ea4-d9e7eb8cc871)

Now making the math (estimation):

If every processId has around 8 versions and each is around 40K then the size per process is: 40 * 8 = 320k (+ processId 20k) ~340k

Now 3,7k elements -> 3,7k * 340 = 1.258.000.000 bytes (1.2 gig)

Since we have three partitions we can roughly multiply this by 3 and we will hit our limit of memory here.

**Comment by Zelldon** [comment]
Not sure about the processId being so large, looks like we use a DirectBuffer which wraps a byteArray. The array seems to be that large, but the buffer capacity is not. I think this was a red-hering. 

Also checking all processIds I see no large processId, the longest has 42 characters.


```
// extract all processes from CF

// get all processIds
cat processes.json | jq '.data[].value.bpmnProcessId' > processids.txt

// count
$ cat processids.txt | jq 'length' | sort -n | tail -1
42
```

**Comment by Zelldon** [comment]
Checking the sizes of the resources:


```
cat processes.json | jq '.data[].value.resource | length' > sizes.txt

# max
$ cat sizes.txt  | sort -n | tail -1
70436

#AVG
 awk 'BEGIN{s=0;}{s+=$1;}END{print s/NR;}' sizes.txt 
18636.1

```

**Comment by berkaycanbc** [comment]
ZPA Triage:

- The solution is straightforward to implement.
- Setting severity as "mid" since the problem occurs in a specific use case.
- Setting priority as "later" because of the current capacity of the team.

**Comment by Zelldon** [comment]
Caused again OOMs in an incident, see https://app.slack.com/client/T0PM0P1SA/C06M40KCMU6

**Comment by megglos** [comment]
ZPA-Triage:
- makes sense to align caching behavior for DMN and BPMN
- could be a quick-fix aligning caching for processes and decisions
- we also need to adopt this for the form cache
