### ISSUE TITLE
Disable Ehcache auto configuration

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15624]
**Description**

It seems we have a transitive dependency to ehcache somewhere, which causes the autoconfiguration for it to kick in. AFAIK we don't use Ehcache anywhere, so we should disable the auto configuration.

Please do correct me if we've recently added it.

**Comment by koevskinikola** [comment]
ZPA triage:
- We can disable this code through the `dist` module's `application.properties`.
- It seems that the Ehcache auto configuration comes from an `identity-sdk` dependency (8.4). We can disable it from our side, but we need to raise an issue with Identity.
- @npepinpe is the auto configuration causing issues with our project?
- Sizing is `x-small` since it's just an addition to the `spring.autoconfigure.exclude` property.
- We can set the priority once we understand the impact of it on our project.

**Comment by npepinpe** [comment]
It's a very small thing which is simply loading unnecessary resources, no urgency or anything, so far only log pollution :upside_down_face:

**Comment by oleschoenburg** [comment]
So identity makes use of Ehcache to cache tokens. As far as I can tell, spring does not pick up on this and there's no autoconfiguration happening. I checked by settting `debug=true` in the application.properties.
Apart from the following log line:
> INFO  org.ehcache.core.EhcacheManager - Cache 'tokenCache' created in EhcacheManager

was there anything else that you saw @npepinpe? Because that is coming directly from identity so it's not something that we can disable.

**Comment by npepinpe** [comment]
No, all good then. We could disable the log I suppose, it's not particularly useful at the info level honestly :+1:
