### ISSUE TITLE
TenantAwareTimerStartEventTest.shouldTriggerTimer is flaky

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#15834]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far
- Does it block your work? I guess not
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Expecting actual:
  [("tenant-a", TRIGGER), ("tenant-a", TRIGGER)]
to contain sequence:
  [("tenant-a", TRIGGER), ("tenant-a", TRIGGERED)]
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by korthout** [comment]
@saig0 Do you still have links to where this occurred?

**Comment by saig0** [comment]
@korthout No. I just saw the flaky test in a failed CI job. I found no more log output for a deeper analysis.

**Comment by oleschoenburg** [comment]
Happened again on main: https://github.com/camunda/zeebe/actions/runs/7842404452/job/21400676737

Logs here: 
[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/14220483/Test.results.for.unit.tests.6.zip)

**Comment by korthout** [comment]
Thanks @oleschoenburg 

```
10:11:15 C DPLY      CREATE         - #01-> -1  -1 -
10:11:15 E PROC      CREATED        - #02->#01 K01 - process.xml -> "process" (version:1)
10:11:15 E TIME      CREATED        - #03->#01 K02 -  @"startEvent"[ -1]  in <process "K01"[?
]> due T10:12:15.4032 reps
10:11:15 E DPLY      CREATED        - #04->#01 K03 - process.xml
10:12:15 C TIME      TRIGGER        - #05-> -1 K02 -  @"startEvent"[ -1]  in <process "K01"[?
]> due T10:12:15.4032 reps
10:12:15 C TIME      TRIGGER        - #06-> -1 K02 -  @"startEvent"[ -1]  in <process "K01"[?
]> due T10:12:15.4032 reps
10:12:15 E TIME      TRIGGERED      - #07->#05 K02 -  @"startEvent"[ -1]  in <process "K01"[K
04]> due T10:12:15.4032 reps
10:12:15 E PROC_EVNT TRIGGERING     - #08->#05 K05 -  @"startEvent"[K01] in <process K01[K04]
> (no vars)
```

The `Timer:TRIGGER` command appears to have been sent twice for the same timer start event at the same time (record timestamp).

The `DueDateTimerChecker` has a 100ms resolution, meaning that after a single pass of expired expired timers it will reschedule itself in 100ms. If the initial `Timer:TRIGGER` command has not been processed yet before that time, a secondary pass would encounter this timer again.

Typically, the scheduled command cache would filter out this second pass, but the command cache is not used in engine tests. It's debatable whether that makes sense.

Regardless, the test itself is somewhat flaky, because it does't consider that multiple commands to trigger the timer could exist on the log before a triggered event for that timer.

We'll simply need to avoid asserting commands in tests, but focus on the effects they have by asserting events. I'll open a PR
