### ISSUE TITLE
Migrate child process instances

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15922]
Similar to https://github.com/camunda/zeebe/issues/15921, we also want to support migrating active child process instances, i.e. process instances called from a call activity.

This would be useful because it expands the coverage of process instances that can be migrated.

When working on this issue, please consider whether the call activity instance must be updated in any way. If so, we may need to add a new `ProcessInstance:CHILD_MIGRATED` event. Re-using the `ProcessInstance:ELEMENT_MIGRATED` for the call activity instance would be wrong semantically, as the call activity instance wasn't migrated.

**Comment by berkaycanbc** [comment]
Checked if there are any properties of the call activity instance that should be updated during the migration of the called child process instance. It turned out that it is not necessary. Only following fields of the child process instance can change:

* the process definition key of the child process instance
* the bpmn process id of the child process instance
* the version of the child process instance
* the element id of the active element inside the child process instance

Checked following classes to see if anything needs to be updated for the calling call activity:
[`ProcessInstanceRecord`](https://github.com/camunda/zeebe/blob/3ae7465c9c6efb119da1919b7f0a59fe9c2802ed/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/processinstance/ProcessInstanceRecord.java#L24) -> no data kept for child process instance
[`ElementInstance `](https://github.com/camunda/zeebe/blob/3ae7465c9c6efb119da1919b7f0a59fe9c2802ed/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/instance/ElementInstance.java#L21) -> only [called child instance's key](https://github.com/camunda/zeebe/blob/3ae7465c9c6efb119da1919b7f0a59fe9c2802ed/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/instance/ElementInstance.java#L36) is kept but it will not change during the migration
[`DBElementInstanceState`](https://github.com/camunda/zeebe/blob/3ae7465c9c6efb119da1919b7f0a59fe9c2802ed/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbElementInstanceState.java#L35) -> parent and child instances are connected through [instance keys](https://github.com/camunda/zeebe/blob/3ae7465c9c6efb119da1919b7f0a59fe9c2802ed/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbElementInstanceState.java#L87) that will not change during the migration of child process instance
