### ISSUE TITLE
Provide a `gateway-protocol-rest` module for the generated OpenAPI code

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#16164]
### Description

REST API-related code generated from the OpenAPI specification defined in https://github.com/camunda/zeebe/issues/16163 is contained in a new `gateway-protocol-rest` module.

### Additional context

Blocked by #16163

**Comment by npepinpe** [comment]
To clarify, this issue will be about generating the shared models which have no dependencies into a separate module. 

Do we really believe this is all that useful? :thinking: Since you're missing the client and server part anyway, your left with very little. Should we leave that to the consumer to generate what they need? :thinking: 

At the same time, it's not a whole lot of code for us to maintain (just a build file, really), so :shrug:

**Comment by koevskinikola** [comment]
@npepinpe as it's not a lot, I think it's okay if we generate it. And we may expand this module in the future once we start unifying the C8 APIs. 

In that case, it's better if we generate it, rather than our customers since we would be able push out dependency updates.
