### ISSUE TITLE
Spike - Support REST in the Zeebe Java client

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#16184]
### Description

Spike a possible solution on how to grow the Zeebe Java client into a **Zeebe Java SDK**. The goal is to support REST communication with the Zeebe Gateway.

### Goals
- [ ] Evaluate HTTP client implementations for working with REST API requests and responses.
- [ ] Determine steps for reusability of the existing `Command` client structure while switching between the gRPC and HTTP clients.
- [ ] Determine the possibility of re-using the same authentication configuration.
- [ ] Determine how to achieve feature parity with client-side gRPC interceptors.

**Comment by npepinpe** [comment]
I'm going on FTO, but I almost finished the prototype for the client part. Of course, feel free to iterate on it or challenge it while I'm gone :upside_down_face: You can see the branch/PR here: https://github.com/camunda/zeebe/compare/np-rest-client?expand=1

Note that the goal was not to find the best design here, but rather to figure out how everything would work with Apache HC5. So definitely, in terms of design and integration into the existing client configuration/UX, this would need more work!

That said, let's see what this solves:
- A thin abstraction, `HttpClient`, is introduced to be used by the commands, with methods for get, post, etc., that will wire everything together as simply as possible, such that the resulting command is just building the request and sending it, and nothing else (i.e. much like it does now with the `asyncStub`).
  - It can provide default request config, and scope the client to a given host/path prefix, TLS context, etc.
- Authentication is handled via the existing `OAuthCredentialsProvider` which implements a new interface, `RestCredentialsProvider`, mostly because we tied the initial interface to tightly with gRPC :slightly_smiling_face: You can see how the new interface is used in `AuthCallback`, but it's very simple.
  - Ideally we can find a solution to minimize user pain here during configuration. As you can see, in terms of implementation, the logic is mostly the same, but it's more about: how do you determine a request to be retried (exception versus status code), and where do you put the resulting headers (in a `Metadata` gRPC object, or just in a plain `Map` of headers)
- TLS configuration (incl. support for self signed)
  - gRPC expects a chain of X.509 certificates in a PEM encoded file, but HC5 expects a standard Java trust store.
  - The simplest way would be to just force users to use a trust store, and the PEM file for gRPC. This is of course the worse UX.
  - The prototype shows how to build a programmatic trust store out of a PEM file, so the same config can be used everywhere.
  - That said, migrating both gRPC and REST to using trust store would simplify things, and may be more idiomatic, so :man-shrugging:
- Asynchronous JSON parsing
  - Since we need the complete response to convert to a POJO (unless we change our POJOs to be stream-enabled like SBE structures), the asynchronous parsing here is mostly about converting the incoming bytes into the AST representation of the objects. Basically, as each bytes come in, we feed it to the parser, and when a new token is readable, we append it to our token buffer.
  - At the end, we generate the POJO from the token buffer, which is then freed.
  - This unfortunately doesn't save much in terms of memory (you still end up using double the memory for a short amount of time), but naively it's more responsive, since you amortize the JSON parsing across the request lifetime, and the only things it does is the POJO conversion at the end. This approach also allows you to detect errors faster.
  - Naive benchmarks show an improvement in terms of throughput, but honestly, they weren't scientific benchmarks, so take it or leave it. That said, I don't think it's super complex, and it's largely how Spring does it (I modeled the solution on their own tokenizer for WebClient :slightly_smiling_face:)
  - **Even if you leave the async JSON parsing**, I would still urge you to keep using the async client. You can just buffer the whole incoming response into a byte buffer, and then feed it to the JSON mapper.
- The response parsing basically uses a `oneOf` kind of structure, where it's either a successful JSON response, or a problem (i.e. `ProblemDetail`). This is detected thanks to Spring sending different content type headers based on the results :+1:
  - I really wish we could use the `Either` type there, but our util module is only for Java 21 :sweat_smile:

Things I did not do:
- How to allow users to customize via middleware/interceptors
- How to allow users to customize the client in general
- How to allow usage of HTTP/2 if possible, which can bring performance improvements - this also has to be enabled on the server side of course
- Performance benchmarks to tune the default HC5 configuration

imo I think request encoding does not need to be asynchronous, as the `send` call can eat that cost. But we could of course do it in the future.

**Comment by npepinpe** [comment]
I also evaluated other clients by the way. Even though we may drop Java 8 support, I would still pick Apache HC5 instead. As Tobi pointed out, the standard client is nice, but considering the client is meant to be embedded in different JVMs, it may behave slightly differently from version to version. So better to have one which we know is standard across all deployments :+1:

I also think the additional features brought by full featured REST clients (RESTEasy, Jersey, Feign, etc.) are really worth it for a production client. We already have our own client abstraction, and we will not be doing a crazy amount of things under the hood. Since most of them anyway rely on HC5 or OkHttp or something, we might as well learn and understand how the low level client works.

Finally, between OkHttp and HC5, I would opt for HC5 instead because:
- OkHttp is Kotlin first, meaning it brings the Kotlin stdlib to the client, and also all docs are in Kotlin. As far as I remember, we decided that Java was our language of choice at Camunda for now (though correct me if I'm wrong)
- OkHttp is more opinionated (see dropped support for TLS/SSL versions, for example). It means it's easier to configure and work with out of the box, though.
- OkHttp is less flexible in general (which ties in with the point above).

That said, the one good point about OkHttp was that you could use it as a transport for gRPC instead of Netty, so we could have effectively leveraged the same library here. This could be nice in a way, especially if people used our client on Android, but I highly doubt they do :sweat_smile: (??) (edited) 

At any rate, here's an unstructured dump from my notes. This is a bit rushed since I'm out for the next two weeks unfortunately, but adding it for posterity:

Apache HTTP Client v. 5.3

|                              | Apache HTTP Client 5.x                                                 | reactor-netty-http                                                           | RESTEasy                                                                              | Jersey                                                                                                                                           | OpenFeign                                                        | Native                             | OkHttp                                                        | Retrofit                                                             |
|------------------------------|------------------------------------------------------------------------|------------------------------------------------------------------------------|---------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------|------------------------------------|---------------------------------------------------------------|----------------------------------------------------------------------|
| Minimum Java version         | 7                                                                      | 8                                                                            | 11                                                                                    | 11                                                                                                                                               | 8                                                                | 11                                 | 8                                                             | 8                                                                    |
| Governance                   | Apache                                                                 | VMWare                                                                       | RedHat                                                                                | Eclipse                                                                                                                                          | Open source community                                            | Oracle                             | Square                                                        | Square                                                               |
| Age                          | At least since 2008                                                    | 2020                                                                         | ~2010                                                                                 | ~2010                                                                                                                                            | 2013 (2016)                                                      | 2018                               | 2016                                                          | 2016                                                                 |
| Last release                 | 2024.01.24                                                             | 2024.01.09                                                                   | 2024.01.13                                                                            | 2023.12.12                                                                                                                                       | 2024.02.07                                                       | -                                  | 2023.10.17 (next major version in heavy development)          | 2020.05.20                                                           |
| Dependency tree depth        | 3 (one is SLF4J)                                                       | 9 (7 are Netty, already included via gRPC)                                   | 10 (1 is Apache HTTP, about half are JAX-RS)                                          | 7 (half are JAX-RS)                                                                                                                              | 0-6 (a bring-your-own model with existing integrations)          | 0                                  | 2 (brings in the complete Kotlin stdlib though)               | 3 (2 are from OkHttp)                                                |
| Size                         | 2.0MB                                                                  | 6.7MB                                                                        | 3.6MB                                                                                 | 3.6MB (with HC5)                                                                                                                                 | 5.6MB (with SLF4J, Micrometer, HC5, and Jackson)                 | 0                                  | 3.0MB                                                         | 4.8MB                                                                |
| Activity                     | releases 1-2 per quarter                                               | releases once per month                                                      | releases 1-2 per quarter                                                              | releases ~1 per quarter                                                                                                                          | releases ~1 per month                                            | -                                  | very active development for next major version and patches    | none?                                                                |
| Community                    | hard to say, GitHub is just a mirror, but it's the most popular client | 2.5K stars, part of Spring WebFlux project and others, alternative to RxJava | 1.1K, fairly popular in the enterprise world, unclear in terms of community           | 900 stars, unclear in terms of community, but very popular as reference JAX-RS implementation                                                    | 9.2K stars, hundreds of contributors                             | -                                  | very popular in the android world                             | popular in the android world                                         |
| TLS self-signed certificates | support through custom TrustStrategy                                   | support through Netty                                                        | support via custom trust store                                                        | support via specific connector providers (e.g. HC5, or Netty)                                                                                    | support via specific connectors (e.g. HC5)                       | support through custom trust store | helpers for self signed certs                                 | through OkHttp                                                       |
| OotB OAuth2 support          | partial                                                                | no                                                                           | no                                                                                    | support for browser based flows                                                                                                                  | no                                                               | no                                 | no                                                            | no                                                                   |
| HTTP Proxy support           | yes                                                                    | yes                                                                          | yes                                                                                   | yes                                                                                                                                              | yes                                                              | yes                                | yes                                                           | yes                                                                  |
| Interceptor/middleware       | yes                                                                    | yes                                                                          | yes                                                                                   | yes                                                                                                                                              | yes                                                              | ?                                  | yes                                                           | yes                                                                  |
| HTTP/2                       | yes                                                                    | yes                                                                          | yes                                                                                   | yes (via connection provider)                                                                                                                    | yes (via specific clients)                                       | yes                                | yes                                                           | yes (via OkHttp)                                                     |
| Logging                      | SLF4J                                                                  | SLF4J                                                                        | jboss-logging (facade)                                                                | JUL                                                                                                                                              | SLF4J (via adapter)                                              | JUL                                | any? (via interceptor and event listeners)                    | same as OkHttp                                                       |
| Metrics                      | none, but micrometer provides OotB support for HC5                     | provides own interface with adapters (e.g. micrometer)                       | microprofile metrics                                                                  | none, but micrometer provides OotB support for Jersey 2                                                                                          | via adapters (e.g. micrometer)                                   | none                               | none, but micrometer provides OotB support for OkHttp3        | same as OkHttp                                                       |
| Tracing                      | none, but micrometer provides OotB support for HC5                     | provides own interface with adapters (e.g. micrometer)                       | microprofile tracing                                                                  | none, but micrometer provides OotB support for Jersey 2                                                                                          | via adapters (e.g. micrometer)                                   | none                               | none, but micrometer provides OotB support for OkHttp3        | same as OkHttp                                                       |
| JSON                         | none                                                                   | none                                                                         | via jackson                                                                           | via jackson                                                                                                                                      | via jackson                                                      | none                               | none                                                          | via jackson                                                          |
| Fluent API                   | yes                                                                    | yes                                                                          | yes                                                                                   | yes                                                                                                                                              | yes                                                              | yes                                | yes                                                           | no                                                                   |
| Interface/Proxy API          | no                                                                     | no                                                                           | yes                                                                                   | no                                                                                                                                               | yes                                                              | no                                 | no                                                            | yes                                                                  |
| Caching                      | yes, memcache and ehcache ootb and custom                              | no                                                                           | browser-like cache (in-memory) using cache control headers                            | no                                                                                                                                               | via adapters                                                     | no                                 | only to file, but support custom providers                    | same as okhttp                                                       |
| Retry                        | yes                                                                    | yes                                                                          | yes (via provider/interceptor)                                                        | yes (via provider/interceptor)                                                                                                                   | yes (via adapters)                                               | no                                 | sort of (basic retry logic on connection errors)              | sort of (via okhttp)                                                 |
| Custom DNS resolver          | yes                                                                    | yes                                                                          | yes (via providers)                                                                   | yes (via providers)                                                                                                                              | yes (via adapters/providers)                                     | no?                                | yes                                                           | yes                                                                  |
| Error handling               | via callbacks and exceptions, must decode and interpret response       | via flux methods (doOnError, retryWhen, etc.)                                | can provide ExceptionMapper to decode exceptions                                      | nothing special                                                                                                                                  | custom error decoders/mapping                                    | -                                  | via callbacks, but nothing special                            | you can use the response abstraction to gracefully handle exceptions |
| Testing                      | nothing special provided                                               | standard reactor stuff, but nothing special for http client                  | nothing special for the client side, but if you use the proxy framework, easy to mock | [very nice test framework for ad-hoc server responses](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/test-framework.html) | nothing special, but everything is an interface, so easy to mock | -                                  | provides a mock web server, but this is usable by all clients | same as okhttp                                                       |


## [Apache HC5](https://hc.apache.org/httpcomponents-client-5.3.x/index.html)

Mature, battle tested project, likely the most used Java HTTP client (ignoring Android platforms). Integrated in many projects such as RESTEasy, Jersey, Feign, etc.
Huge feature set, very configurable. Likely requires a bit of a learning curve to use properly.

Supports self-signed certificates, HTTP proxies, custom authentication schemes, request and response interceptors, asynchronous and reactive APIs, automated retry handling, caching, custom DNS resolver, logging via SLF4J.
Does not support metrics or tracing out of the box, but Micrometer provides interceptors for such things. No special testing framework.
No special JSON encoding/decoding utilities.

## [OkHttp](https://square.github.io/okhttp/)

Mature project, most popular HTTP client on Android, but also used outside. Easier to use and configure than HC5 out of the box, but less flexible. OkHttp3 migrated to Kotlin, so brings the stdlib with it, and also documentation is Kotlin first.
Smaller feature set than HC5, but also means easier to learn and understand.

Backed by Square, a fintech company, so releases, CVEs, etc., are all well maintained.

Supports automated retry, request/response interceptors, caching (and custom caching), 
Partially supports self-signed certificates: it seems to be mostly for testing and not for production usage though. However, users can provide custom Keystore/Truststore to circumvent this (which diverges from how we handle TLS so far).
Partially supports custom DNS resolvers, meaning you can inject your own, but doesn't provide any implementations other than the JVM's.
Does not support logging, metrics, tracing, etc. However, Micrometer provides out of the box bindings for it. No special JSON encoding/decoding utils either.

One interesting point is that gRPC supports switching away from Netty to OkHttp. I assume this is for Android support. But it means we could consolidate how our client works by simply using a single
library, OkHttp, and getting rid of Netty on the client side, thus reducing our CVE surface.



## [reactor-netty-http](https://github.com/reactor/reactor-netty)

Underpins Spring WebFlux, and provides the raw HTTP capabilities. Unfortunately also includes the server parts, but that's par for the course with many of the libraries. 

Backed by VMWare/Spring, so releases, CVEs, etc., are all well handled.




Big points about OkHttp: can reuse for gRPC, meaning we can share dependencies and transport configuration.
HC5: most commonly used (outside of Android), very flexible, huge community. 
RESTEasy wraps Apache HTTP Client 4.x, so configurable as much as that one
Jersey supports multiple connector providers (i.e. low level clients like HC5), so also fairly configurable
Retrofit technically also supports Apache HTTP Client
Feign supports most client and is a bring-your-own stuff
