### ISSUE TITLE
Extend generalized command distribution for subsets of partitions

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#16385]
This is needed for:
- Process Instance Migration of Message Subscriptions: reliably communicate the `MessageSubscription:MIGRATE` command 
- Replacing the reliable communication of Message Subscription Opening, Closing, and Correlation to benefit from generalized command distribution, like exponential backoff, actor yielding (not yet supported), caching (not yet supported), ordered distribution (not yet supported), metrics (not yet supported), etc

**Comment by tmetzke** [comment]
ZPA triage:
- Alternatives:
  - We could build the communication to the other partition(s) for migration specifically like we did for Message Subscription Opening and Closing. However, this just adds more technical debt.
  - We could unsubscribe from the old message and subscribe to the new one.
- In the long run, this would create a lot of benefits on a technical level and remove tech debt.
- On an engineering level, it makes most sense to build this properly right now instead of postponing it and adding more technical debt. It will be implemented in the focus #15407.
