### ISSUE TITLE
Banning doesn't block related instances (parent or childs)

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#16412]
**Describe the bug**

When due to an error a process instance is banned it doesn't make sense to allow the processing of the parent nor child nor sibling. We should prevent these executions as well. 

Related to #16410 

The severity is high, as this can cause severe issues when dealing with different parts of the process mistakenly. Not only on recursion but also on other cases, like multi-instance one instance is banned because of an error (wrong data/too large) and others continue and might corrupt the state further.

Likelihood low as we expect bugs which cause to ban instance to be low as well, but as soon a process instance is banned this likelihood of course increases.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by tmetzke** [comment]
ZPA triage:
- Banning is historically meant to preserve the state so we can properly do root-causing. In that sense, banning child and parent instances might make sense so we preserve the state.
- However, banning is a dead-end. We want to rather focus on incident handling/introduction and process [suspend/resume](https://github.com/camunda/product-hub/issues/289) of instances.
- We also question whether banning is the right tool to handle the linked issue (endless recursion via self-referencing call activities). Suspension would be a better tool for this.
- We don't plan to extend banning at this stage for this case, thus we're closing this issue here and won't move it to the backlog. We'll rather invest the time for process suspension.
