### ISSUE TITLE
Get rid of Dependabot for Operate dependencies

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17172]
We want to completely replace dependabot with renovate

See related slack https://camunda.slack.com/archives/C06HTSPD5AP/p1711091253406079?thread_ts=1711040114.746319&cid=C06HTSPD5AP

**Comment by cmur2** [comment]
Consider disabling https://github.com/camunda/zeebe/settings/security_analysis scan if they are not useful to the team.

**Comment by cmur2** [comment]
# Current status

Dependabot PR updates are disabled in https://github.com/camunda/zeebe/settings/security_analysis *except* for security-relevant problems - that means that if Github's vulnerability database contains a vulnerability related to one of the versions we use, Dependabot will raise a PR anyways.

We can consider to also disable this behavior because (hypothesis) Renovate should detect and cover those updates as well.

Let's compare the list of [Dependabot security PRs](https://github.com/camunda/zeebe/pulls/app%2Fdependabot) with what Renovate detects:

* ✔️ https://github.com/camunda/zeebe/pull/17156 - also covered by Renovate in all branches according to https://github.com/camunda/zeebe/issues/12605 but awaiting schedule: `deps: Update version.elasticsearch to v7.17.19 (stable/8.1) (co.elastic.clients:elasticsearch-java, org.elasticsearch.client:elasticsearch-rest-client)`
* ✔️ https://github.com/camunda/zeebe/pull/17100 - also covered by Renovate in https://github.com/camunda/zeebe/pull/17198
* 🔍 https://github.com/camunda/zeebe/pull/17112 - ???
* 🔍 https://github.com/camunda/zeebe/pull/17093 - ???
* 🔍 https://github.com/camunda/zeebe/pull/17048 - ???
* 🔍 https://github.com/camunda/zeebe/pull/16891 - ???
* 🔍 https://github.com/camunda/zeebe/pull/16879 - ???

**Comment by cmur2** [comment]
https://github.com/camunda/zeebe/pull/17305 was merged and I forced the creation of https://github.com/camunda/zeebe/pull/17310 ahead of schedule. Using that I could confirm that Dependabot security PRs like https://github.com/camunda/zeebe/pull/17112 are now covered.
