### ISSUE TITLE
Rework Operate Dockerfile to be architecture agnostic

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17181]
> Renovate keeps updating the digest of the base image with a wrong hash, we should close the next renovate PR by doing the same
> **_As posted by @houssain-barouni in https://github.com/camunda/zeebe/pull/17065_**

The Zeebe team found a solution (by @npepinpe in https://github.com/camunda/zeebe/pull/14186) to the problem and it should also be applied to the Operate Dockerfile. This allows smooth (auto) updates via Renovate and reduces code duplication.

Also posted via slack here https://camunda.slack.com/archives/C01H4NG9XDY/p1711380447439419

Tasks:

* apply the solution from https://github.com/camunda/zeebe/pull/14186 to https://github.com/camunda/zeebe/blob/main/operate.Dockerfile and ensure working builds and usage
* revert https://github.com/camunda/zeebe/commit/44b4fc9d630a54e74cc35e29a3ed6273adf17c94 to enable Renovate updates again (relevant for security)

Hints:

* you can approach @npepinpe and @cmur2 for input

**Comment by cmur2** [comment]
@johanwelgemoed we discussed this issue in the C8AS project team with @romansmirnov and decided that while we can provide help with this topic, we'd like to see the Operate team driving this improvement. The reason here is to focus the project team on the migration and laying foundational frameworks. This issue was already solved by the Zeebe team so a blueprint exists that can be applied to Operate. We are available for questions obviously :+1:

**Comment by johanwelgemoed** [comment]
@cmur2 no worries. I think I did the previous changes from ubuntu to alpine so makes sense for us to do it. We just did not have time last week so will get on it this week to resolve the dependency stuff asap. Thanks for the patience.
