### ISSUE TITLE
Review community-project latest changes

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#17340]
Review latest changes on the community project (https://github.com/camunda-community-hub/spring-zeebe/pull/690) and move them into the client if necessary

**Comment by ana-vinogradova-camunda** [comment]
I've reviewed community project changes:
The main change is in how application properties are handled. Properties are read from `.yaml files` (`application-camunda-<mode>.yaml`) instead of using multiple configuration classes (such as `OptimizeClientConfigurationProperties` for example). As a result, multiple configuration files were marked as deprecated or removed and classes that are used for properties handling were added.

The main things added:

- `.yaml` files for `simple`, `saas` and `oidc` - default properties for setting up all connection details for each mode. The modes are described in the updated README `Configuring Camunda 8 connection` section.
- `PropertiesPostProcessor` - reads the properties from the properties file
- `CamundaClientProperties` - configuration properties class, contains `ApiProperties` for each component and `ZeebeClientProperties`
- `ZeebeClientProperties` - client's properties, extends `ApiProperties`
- `ApiProperties` - API properties such as URL etc.
- `AuthProperties` - authentication properties for `simple`, `saas` and `oidc` modes
- `PropertiesUtil` - utility class, used to get gateway address
- `AuthenticationConfiguration` - takes `CamundaClientProperties` and `JsonMapper` to configure authentication. It checks which mode is used: if `simple` - then configure tasklist and operate only (In general, it looks like simple auth is only used to configure tasklist and operate), `oidc`: configure zeebe, tasklist, operate, optimize. `saas`: configure all. It looks to me that this class can be simplified.

`ZeebeClientAllAutoConfiguration`, `ZeebeClientProdAutoConfiguration`, `ZeebeClientConfiguration`, `ExecutorServiceConfiguration` use `CamundaClientProperties` from now.

The main things removed (that are relevant to us):

- `ConsoleClientConfiguration`

The below configuration classes that are relevant to us are marked as deprecated:

- `CommonClientConfiguration`
- `CommonConfigurationProperties`
- `ConsoleClientConfigurationProperties`
- `ZeebeClientConfigurationProperties`
- `ZeebeSelfManagedProperties`
- `Client`
- `Keycloak`

These are not all the changes, but the main ones. A lot of tests were added too.
