### ISSUE TITLE
test shouldEnableStreamingWithProperty fails when building locally

### ISSUE THREAD

**Issue by matt-whiteman** [camunda/zeebe#17910]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
Seems like it fails all the time when I try to build zeebe locally using 'mvn clean package' in the zeebe subdirectory
- Does it block your work?
No, I just want to make sure I can build the entire mono-repo locally if necessary
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
[ERROR] Tests run: 57, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.267 s <<< FAILURE! -- in io.camunda.zeebe.client.ZeebeClientTest
[ERROR] io.camunda.zeebe.client.ZeebeClientTest.shouldEnableStreamingWithProperty -- Time elapsed: 0.018 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be true but was false
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.camunda.zeebe.client.ZeebeClientTest.shouldEnableStreamingWithProperty(ZeebeClientTest.java:186)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by npepinpe** [comment]
I think @koevskinikola had mentioned to me this was a known issue, but I can't remember. It only happens when you run all tests - if you run the test individually, it's fine, which hints that it's more about some environmental thing than a real issue. Still annoying, of course.

As Nikola is on FTO for now, I don't remember what the issue was, but maybe someone from the ZPA team would, I'll ask.

**Comment by oleschoenburg** [comment]
Perhaps because tests such as `shouldEnableStreamingWithEnvironmentVariableWhenApplied` modify `Environment.system()`?

**Comment by Zelldon** [comment]
Oh they don't use a stub / proxy env map?

**Comment by berkaycanbc** [comment]
It was due to `JobWorkerImplTest.workerBuilderShouldOverrideEnvVariables` modifying the Environment:https://github.com/camunda/zeebe/blob/e7dcdf283d0511ab0cbff755b06e6d2bc330b3e6/zeebe/clients/java/src/test/java/io/camunda/zeebe/client/impl/worker/JobWorkerImplTest.java#L179-L181

We have an `EnvironmentRule` rule class to clean up the environment before and after each test:
https://github.com/camunda/zeebe/blob/e7dcdf283d0511ab0cbff755b06e6d2bc330b3e6/zeebe/clients/java/src/test/java/io/camunda/zeebe/client/impl/util/EnvironmentRule.java#L21-L34

Adding this to `JobWorkerImplTest` class should resolve the issue.
