### ISSUE TITLE
Separate embedded from standalone gateway configuration

### ISSUE THREAD

**Issue by menski** [camunda/zeebe#2017]
With the closer integration of the embedded gateway into the broker the configuration for the embedded gateway has a lot of parameters which are not respected. We should split them apart so they are focused on the actual use case.

**Comment by npepinpe** [comment]
Looking at it, it seems only the following are not respected:

1. ThreadsCfg - the embedded gateway reuses the same actor scheduler as the broker.
1. ClusterCfg#contactPoint - this is hardcoded to the local broker
1. NetworkCfg - the default host is replaced with the broker's default host, and the port is re-computed with the broker's portOffset (if any)

Everything else seems to be respected. I would propose instead of sub-classing `GatewayCfg`, we just wrap it, and apply overrides (sort of as we do now) - but we still need to pass a `GatewayCfg` to the `Gateway` at the end.

**Comment by alexanderavdeev14** [comment]
I would like to take this issue.

**Comment by Zelldon** [comment]
I think there is no need for it right now. We can reopen it if the priority changes or open a new issue.
