### ISSUE TITLE
CommandAPI may not release writer on becoming follower

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#3965]
**Describe the bug**

On becoming a follower, there is a chance that CommandApi does not close the writer, thus preventing logstream from closing the dispatcher. When this node becomes leader again, it starts with a wrong position thus making the position in the log not sorted. This can lead to issues like #3920 

On becoming a follower, command to close the writer is submitted to the command queue. But this command queue is drained by the request handler handling requests from the gateway. This happens only if there are new requests from the gateway. 

```
void removePartition(final LogStream logStream) {
    cmdQueue.add(
        () -> {
          final var recordWriter = leadingStreams.remove(logStream.getPartitionId());
          if (recordWriter != null) {
            recordWriter.close();
          }
          partitionLimiters.remove(logStream.getPartitionId());
        });
  }
```

**To Reproduce**
When forcing a step down of a node with out shutting it down, you can observe that dispatcher is not closed sometimes.

**Expected behavior**
CommandAPI release the writer and thus close the dispatcher.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.23.0-SNAPSHOT]
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
@MiguelPires is this still true after the transition refactoring we did?

**Comment by MiguelPires** [comment]
Looking at the current code, I don't get how the CommandApi prevents the dispatcher from being closed. I do get that if the command to remove the writer is added to the queue and no request comes in, then we don't run that command and the writer is never removed. That issue was not fixed by the refactoring. What was fixed by the refactoring is that the partition listeners are informed of transitions even if something went wrong. The refactoring made it so that the log stream is closed as a normal partition step (either during leader->follower transitions or if some failure occured) and AFAIK that will close the Dispatcher.

**Comment by deepthidevaki** [comment]
As far as I know, this is still an issue. It doesn't impact us now because logstream is closed when transitioning from leader to follower. If we want to keep the logstream open (for eg:- when building state on followers), this would be an issue.

**Comment by Zelldon** [comment]
@deepthidevaki do you see this still as an issue?

**Comment by deepthidevaki** [comment]
Looks like it is fixed https://github.com/camunda/zeebe/blob/d218d46555e8bce8d9609a19c6d4e71f58a256f1/broker/src/main/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiRequestHandler.java#L148-L152

Adding to cmdQueue to replaced by `actor::submit`. So the writers are guaranteed to be removed.
