### ISSUE TITLE
Use timeouts in LogStorageAppender to detect health of raft leader

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#4032]
**Description**

Now we rely on raft thread to report failure to the health monitor. In addition to that LogStorageAppender might be able to detect when raft leader is not making progress by keeping track of responses from the appends. If an append does not invoke the commit listener with in a specific duration (large enough), it indicates that raft thread is not making progress. Appender can then determine it as an unhealthy state and report it to the health monitor.

**Comment by npepinpe** [comment]
Can you elaborate on how this would benefit us? It's unclear to me what new actionable information this would provide.

**Comment by deepthidevaki** [comment]
I think the idea was that in case raft thread is blocked or not making progress, we can detect it from the appender. But I don't think we have ever observed raft thread is blocked. So may be not so important.

**Comment by npepinpe** [comment]
I would like to actually switch the paradigm eventually and have the Raft leader pull from the dispatcher/storage appender instead of us pushing into it - this would allow better flow control (i.e. using a credit based system). Plus, we would still like to switch Raft to the actor model, so it may not be worth doing before then unless we see some near-term value to this. Since it's unclear to me, and you also seem to not see it as important, I would propose we close this :slightly_smiling_face:

**Comment by deepthidevaki** [comment]
I will close this as we don't see much advantage in it.
