### ISSUE TITLE
Followers should acknowledge writes asynchronously to pipeline flush operations

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#4695]
**Description**

In order to be switch our log storage to memory mapped files, we currently have one big issue which is related to flushing I/O. To ensure data integrity, a follower should not acknowledge an append until the I/O operation was flushed to disk. This is however an expensive operation to do on every write.

A better way to do this would be to switch our pipeline to support asynchronously flushing and acknowledging multiple append requests at once after the flush.

Here the question would be what should be the trigger to flush? After X seconds? After we received X entries to append?

This would also greatly improve performance and data integrity.

**Comment by Zelldon** [comment]
In the previous logstorage we flushed on every 1024 writes I think. There was a class called RateLimiter which does this.

**Comment by npepinpe** [comment]
No time component? What if you're stuck at 1023 for 2 seconds?

**Comment by Zelldon** [comment]
I think the assumption was that there will be always a next record. E.g. job activation, timers etc.

**Comment by deepthidevaki** [comment]
When doing batch flushing, there is a caveat that the latency for single event/commands increases. But this is something that we can evaluate to see how much it impacts.

A related idea that I just want to chip in here: 
* Only flush and acknowledge when records that have observable side-effects are written(i.e usually commands).
* Stream-processor is allowed to read un-committed events, but not un-committed commands, to process because the results are not visible externally. This would not affect correctness because the events are deterministic. But the latency might decrease as we are not waiting for the flush+ack to process the events.

**Comment by npepinpe** [comment]
Some of our events produce follow up events - while they are deterministic, the ordering may not be since if you fail to obtain quorum, and re-run the sequence on a different machine, you may get new commands interleaved, no?

**Comment by deepthidevaki** [comment]
The ordering won't change, since we don't skip ahead the commands. If we have following records in the log - a command c1
Log: c1
Stream processor process c1 to create follow up event e1
Log: c1, e1
Stream processor continue processing uncommitted events to get follow up events e2 -> e3 -> e4
Log: c1, e1, e2, e3, c2, e4
and wait for command c2 to be committed. 
If a leader change happens at this time, the new leader has the following log
Log: c1
It processes this command resulting in
Log: c1, e1, e2, e3, e4
Command c2 is lost because it was never committed and that is ok. When the old leader comes back it will truncate its log and will have the same committed entries as the new leader.

**Comment by npepinpe** [comment]
Hm, but sometimes we have:

c1 produces e1,e2,e3,e4,e5. If we process e1 and it produces e6,e7, then we process e2 which produces e8,e9, but we crash before e6, e7, e8, e9 are committed (or even appended to any follower), then the log is back to c1,e1,e2,e3,e4,e5. On failover, we reprocess, but maybe between reprocessing e1 and e2 a command c2 is already appended to the dispatcher, so we will write e6, e7, c2, e8, e9. No? If I'm wrong then I think we should discuss over Zoom (though really a whiteboard would've been best :stuck_out_tongue:)

**Comment by deepthidevaki** [comment]
> EDITEDIT: ok but what if one of the uncommitted events we process sends a message subscription command (e.g. OpenMessageSubscriptionCommand) to another partition, and this is committed on the other partition? thinking Could this be an issue?

Any records that have side-effects should be treated like commands. So it should be processed only after committed. We can of course discuss and work out the details to see how it impacts correctness and if at all it improves the performance.

**Comment by npepinpe** [comment]
I think we can close this? We didn't find much gain at the moment from flushing/acknowledging asynchronously.
