### ISSUE TITLE
A lot of logs noise and CPU hungy long polling leaking handlers/listeners

### ISSUE THREAD

**Issue by denissabramovs** [camunda/zeebe#5642]
**Describe the bug**
https://www.loom.com/share/6cc01879ee024d488c4c81eb68a324e3
A lot o noise in the logs of zeebe server, after multiple restarts on zeebe-client.
Noise is coming from long polling implementation.
Slack related thread: https://zeebe-io.slack.com/archives/C6WGNHV2A/p1603124425146800

@korthout found out that there was a problem with clearing listeners related to long polling:

> I dug around a little, seems that our long polling code only looks at whether the client (i.e. worker) is still around when it wants to sent a response, so also when the timer runs out, but not when logging this message. So, the gateway does keep the request to the broker open, even though the worker is already gone. It would be better if the gateway would be notified of this cancelation and just cancels the request to the broker, but it currently does not do this.

**To Reproduce**
- use docker-compose from here https://gist.github.com/denissabramovs/add46d414f115abf9c44175b0f7d1c4f
- implement a simple node.js client from here with 5 workers and handlers
- start, wait until client will connect and start long polling session
- kill client
- repeat 1000+ times
- wait 30 seconds until long polling threshold is reached (30 seconds default or so)
- check logs, they should spawn a lot of log entries every 30 seconds from now on

If possible add a minimal reproducer code sample
- 

**Expected behavior**
Expected to have limited amount of long polling messages and less CPU hungry zeebe server

**Log/Stacktrace**
-

**Environment:**
 - OS: Ubuntu
 - Zeebe Version: 0.24.1
 - Configuration: defaults from above docker-compose, no additional configuration on client-side

**Comment by korthout** [comment]
I've given this `Impact: Usability`, because the issue concerns only 2 things:
1. a message is more often logged at DEBUG level than necessary
2. a long polling request from the gateway to a broker is unnecessarily kept open which may lead to jobs being activated for a worker that is no longer asking for work (this results in those jobs timing out and can then be picked up in the next request to activate jobs).

Only 2 seems to be of real importance, but only occurs when a worker disconnects and reconnects which is likely not common behaviour, thus `Severity: Low`

**Comment by korthout** [comment]
@npepinpe and I just discussed the topic. We could actually detect a worker leaving using `io.grpc.stub.ServerCalls.setOnCancelHandler(Runnable)`.

**Comment by Zelldon** [comment]
Since this issue is quite old and we made several improvements on the gateway side I would close this for now. Feel free to reopen it.
