### ISSUE TITLE
The broker tries to correlate the message infinitely if the command is rejected 

### ISSUE THREAD

**Issue by tjwp** [camunda/zeebe#5750]
This issue was first reported in a Zeebe Slack thread: https://zeebe-io.slack.com/archives/C6WGNHV2A/p1604077101313300

----

This week we have been experiencing an issue with our Zeebe cluster in our staging environment that I'm hoping someone can help us to remedy.

**Background**: We have a 3 node, 3 partition cluster running, and we have a Kafka exporter configured. We consume the messages from Kafka to monitor the cluster. Earlier this week we had an out-of-memory event for one of the brokers.

**Problem**: Since this happened earlier this week, we have seen two specific COMMAND_REJECTION events published repeatedly to Kafka. We are receiving each of these around twice per minute.

The messages are a NOT_FOUND for a WORKLOW_INSTANCE_SUBSCRIPTION with the reason:
```
Expected to correlate workflow instance subscription with element key '2251799816436558' and message name 'synthetic_message', but no such subscription was found
```
And an INVALID_STATE for a MESSAGE_SUBSCRIPTION with the reason:
```
Expected message '6755399443807792' to be correlated for workflow with BPMN process id 'synthetic' but no correlation was found
```
The messages that we are consuming from Kafka are always for these specific keys, and we are not reprocessing the same Kafka messages because the source record position is changing.

Also, based on other messages that we had already processed from Kafka when this problem was noticed, the workflow the errors are associated with a workflow instance that already completed successfully and the message (with the key from the error) was successfully correlated with the subscription corresponding to the element key.

**Help**: What we looking for is a way to stop these COMMAND_REJECTION from being continually published. We have already restarted all of the brokers in the cluster, and the messages continue. Is there a way for us to correct or clear the state to stop these messages? Our concern right now is that these messages could accumulate over time, especially if we have more similar incidents, and right now we have no way to stop them.

Please let me know if there is additional information that would be helpful. I'll attach the brokers logs from around when the problem started. Thank you!

[zeebe-broker-logs.txt](https://github.com/zeebe-io/zeebe/files/5478013/zeebe-broker-logs.txt)

----

Additional details from previous discussion:
- this did not occur around an upgrade
- the problem started in the early hours of a Monday morning in a staging environment with very little happening besides a once every 5min workflow

**Comment by saig0** [comment]
I'm not sure how the broker ended up in this situation. The subscription is (partially) in the state and it retries to correlate the message. The workflow instance closes the subscription already and rejects the correlation command. The rejection is sent back as response and processed. Here, the processor sees that the subscription is (partially) removed from the state and reject the rejection :sweat_smile: We need to make sure that the state is cleaned at this point (`RejectMessageCorrelationProcessor`).

**Comment by tjwp** [comment]
We've now hit this problem again, this time with our production cluster. With no way to clear this state, we will have to manually migrate to a new production cluster to stop the errors.

**Comment by jaeger401** [comment]
Would it be possible to have this re-examined and perhaps returned to planned status? We've hit this same issue again in the staging cluster Tim noted above. The only significant change is that we are now running Zeebe 0.26.3. We were on 0.24.3 when Tim first reported the issue in November

Migration to a new cluster is costly and time-consuming, so any means of clearing the erroneous state would be welcome. Thanks!

**Comment by saig0** [comment]
@jaeger401 thank you for the update :+1: 

We did a major refactoring of the workflow engine for version 1.0. It would be good to know if the failure is still present.

Please let us know if anyone sees the same failure in versions >= 1.0.

@npepinpe we should have a (timeboxed) root cause analysis to estimate the effort.

**Comment by npepinpe** [comment]
Is it possible for you to update to 1.x? With the 1.1 release, we will phase out support for versions < 1.0. 

Generally I do think we should we handle the rejections and stop correlating if we get one, but from speaking with @saig0 this isn't an expected case, as such we should also figure out why this happened.

Semi-related to https://github.com/camunda-cloud/zeebe/issues/6964

**Comment by jaeger401** [comment]
Apologies for the slow reply! I'm afraid we are not able to upgrade to 1.x at this time, though we plan to do so once we resolve other infrastructural issues. We've recently bumped to 0.26.4, and that's stable enough for now. 

Thanks for the notice about the deprecation of versions < 1.0 though. I guess that will add fuel to the fire of sorting out the upgrade path!

**Comment by rusterholz** [comment]
> Generally I do think we should we handle the rejections and stop correlating if we get one

@npepinpe Can you confirm whether 1.0 is designed to do this (stop correlating if it gets a rejection)? That is, is there any reason to think that the refactor would have specifically eliminated this bug?

If not, perhaps this bug could be returned to planned status now, and a future 1.X version could _explicitly_ ensure that it stops trying to correlate when it handles the rejection, regardless of whether anyone has yet replicated the issue with 1.0. E.G. if we know that the possibility of this bug is not guarded against in 1.0, it may still make sense to try to solve it before waiting for us to upgrade.

**Comment by npepinpe** [comment]
No, it isn't explicitly designed to handle this. There is another issue to address the wider idea of _always_ handling rejections, even from internal commands - this one is planned, and would technically cover this one here. The reason we asked if it happened in 1.0 is because the broker shouldn't have been in this state to begin with, so it's possible the root cause has been eliminated indirectly. So essentially there's two parts that we want to handle: 1) figure out why was one partition trying to correlate a message when there was no subscription to correlate to anymore, and 2) [handle rejections gracefully](https://github.com/camunda-cloud/zeebe/issues/6964)

Generally handling rejections is planned - here it's more about figuring out what the root cause of this issue was, and I would leave it in the backlog unless we have more actionable information.

**Comment by saig0** [comment]
We assume that the issue is solved already. 

Please reopen the issue if you are facing the problem again in a recent version.
