### ISSUE TITLE
Handling any type of Error

### ISSUE THREAD

**Issue by johnyrose** [camunda/zeebe#5881]
**Description**

Hi, 

We run multiple workflows with Zeebe. When it comes to handling errors, according to the documentation (https://docs.zeebe.io/bpmn-workflows/error-events/error-events.html), you can only do any form of error handling within the workflow if you throw an error with a specific error code.

We're interested to have "general" error handling in some of our workflows. Which means that when any kind of error is thrown, no matter the error code, it will go a different path and perform a set of actions. This can be useful when you want to perform some sort of "clean up" for example. 

We currently found a solution by always throwing an error with the same error code (something like "generalError"), and while that works its not the most ideal solution as its hard to track the original error that was thrown for troubleshooting it later.

Is there currently a recommended way to go about this, or a planned feature that can help with this?

**Comment by npepinpe** [comment]
I believe Camunda BPM supports this use case - if you omit the error code, then it will catch all errors. I think this is a valid case, and we'll bring it up to the product team. However, I think it's probably not very useful until https://github.com/zeebe-io/zeebe/issues/4337 is implemented, since a naive implementation of just catching everything would end up discarding the code/message.

**Comment by saig0** [comment]
Closing this issue in favor of #11126.
