### ISSUE TITLE
Add metrics to SwimMembershipProtocol

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#6003]
**Description**

To help tune the config parameters of Swim protocol, it would be useful to add some metrics. 
Examples:
- Probe latency - RTT for a probe request
- Gossip latency - how long until a metadata change on a node is propagated to another node.

Related to https://github.com/zeebe-io/zeebe/issues/4827#issuecomment-740624583 https://github.com/zeebe-io/zeebe/issues/4827#issuecomment-740768778

**Comment by Zelldon** [comment]
I feel with adding messaging service metrics we this covered as well https://github.com/camunda/zeebe/pull/11353 we have labels for the message types, which allows us to see also probe and sync req-response latencies etc.

**Comment by Zelldon** [comment]
I could add a separate section to the dashboard for swim using these metrics

**Comment by rodrigo-lourenco-lopes** [comment]
Since we are broadcasting the gossip of these updates with no answers, how could we go about measuring this gossip latency?
How about implementing a response for these broadcasts along with the metric and putting everything behind a feature flag?
Or ideally, there is a more straightforward way to measure this.

https://github.com/camunda/zeebe/blob/5280440c43122cf2da5b4b83dbff76a644273e7c/atomix/cluster/src/main/java/io/atomix/cluster/protocol/SwimMembershipProtocol.java#LL753C1-L758C4

wdyt? @npepinpe @Zelldon

**Comment by npepinpe** [comment]
Honestly, it sounds to me like distributed tracing would be the tool we want to have here. Start an operation somewhere, measure when it completes somewhere else, possibly with hops.

**Comment by rodrigo-lourenco-lopes** [comment]
The other thing we could measure perhaps is sync() we have a response for this one.
