### ISSUE TITLE
Support BPMN Inclusive Gateways

### ISSUE THREAD

**Issue by ningdr** [camunda/zeebe#6018]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by npepinpe** [comment]
Hi @ningDr. Could you describe your use case in more detail? Maybe we can help you find a different approach.

In the meantime, I can already tell you the core team has no short or mid term plan to support the inclusive gateway symbol, though I'm sure it will eventually make its way into Zeebe.

Hope this helps!

**Comment by ningDr** [comment]
For example, the node of flow_1111 will produce a variable which key is 'distStr', and the value of it is 'abd'. Then, after the inclusive gateway, this times, we need the engine to execute a and b branches. In the other process instance, if the value of the key has changed to 'abc', we need the engine to execute a, b, and c branches. For all of this, we just need to define a BPMN model. Because the ZEEBE engine didn't have an inclusive gateway, we can't use ZEEBE for our project!
![image](https://user-images.githubusercontent.com/38251752/104291817-fc820700-54f6-11eb-8041-ea0b5217e6de.png)

**Comment by saig0** [comment]
@ningDr thank you for providing the input :+1: 

I see that the inclusive gateway would be handy in this situation. It allows modeling the flow in a compact way.

But the inclusive gateway can also be tricky in more complex situations. Depending on the model, it can be hard to determine if an active path (i.e. a token) will merge with the inclusive gateway or not. This is important to know to decide if the gateway can be left or not.

In many situations, like in your case, you can model the workflow differently without inclusive gateways. For example, using a combination of parallel and exclusive gateways. It is not so compact and looks more complex but it would work for now :wink:

**Comment by ningDr** [comment]
I have thought of using the exclusive and parallel gateway, but, we need to load a BPMN model given by the other system, in this situation, we couldn't give a common function to process all the relationship which in the BPMN model. 
Though there is the function, the model's elements relations which after the processing of the function must be very complex so that humans couldn't understand.

**Comment by skayliu** [comment]
Hi，i'm trying the inclusive gateway ,it can be activted in the fullfield sequences
![20220707-160556](https://user-images.githubusercontent.com/26370117/177723863-322abedd-bc79-4adc-8e4c-4ea5a37ec58a.png)

but stuck with the merge，the outgoing have been trigged twices 

![20220707-160549](https://user-images.githubusercontent.com/26370117/177724541-de77684e-bc45-47a0-b0bb-96c97cfb1f88.png)

**Comment by skayliu** [comment]
@saig0 I think I have fix it，task a look those images。

![20220708174529](https://user-images.githubusercontent.com/26370117/177978788-06803ab9-398e-4e27-bfae-152cc456c7b0.png)


![20220708174803](https://user-images.githubusercontent.com/26370117/177978743-cf46e2f1-0655-415a-b0f9-28202dd6f9e9.png)

![20220708174825](https://user-images.githubusercontent.com/26370117/177978744-59cd8933-6410-45db-909a-c89c42b4d180.png)

**Comment by korthout** [comment]
#9747 added support for the diverging (forking) behavior. I'll open a new issue for the converging (joining) behavior.
