### ISSUE TITLE
Stream processor is not able to detect nor handle records of different versions gracefully

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#7449]
**Description**

Currently we compare on processing the version of the records, but this version is hard coded in the protocol. It might be never or very sparse updated. If a version mismatch is detected then the processor blows up. This might also not really visible to the end user.

Related comment on ZEP: Build State on Followers https://github.com/zeebe-io/enhancements/pull/16

> saig0
>> In our processing and replay state machine we have event filters, which verify the version of the read entry.
> 
> Yes, we have a filter in the processing and the replay state machine. But it's good to know that it checks the version of the protocol (defined in /protocol/pom.xml) and not the version of the broker itself.
> 
> Currently, the protocol version is not updated strictly. For example, when adding a new value type to the enum.
> 
> Apart from changing the protocol definition itself, we might need to consider other changes in the broker. For example, adding a new BPMN element type. If an old follower is not aware of a new BPMN element then it is not able to produce the correct state.
> 
> We should think about checking the broker version instead.
> 
>> Newer entries are ignored by the Follower with the old version.
> 
> Ignored is maybe not the correct word sweat_smile The version check throws an exception. I'm not sure how nice this looks in the logs.
> 
> Maybe, we want to handle this case more clear to identify it in the logs when it happens.

https://github.com/zeebe-io/enhancements/pull/16#discussion_r662755676

This is interesting for building state on followers and supporting rolling updates.

**Comment by remcowesterhoud** [comment]
I tried adding a filter to verify the current broker version it at least the broker version of the record:
```java
public class RecordBrokerVersionFilter implements MetadataFilter {

  public static VersionInfo CURRENT_BROKER_VERSION = VersionInfo.parse(VersionUtil.getVersion());

  @Override
  public boolean applies(final RecordMetadata metadata) {
    if (metadata.getBrokerVersion().isGreaterThan(CURRENT_BROKER_VERSION)) {
      throw new RuntimeException(
          String.format(
              "Cannot handle event with version newer "
                  + "than what is implemented by broker (%s > %s)",
              metadata.getBrokerVersion(), CURRENT_BROKER_VERSION));
    }
    return true;
  }
}
```

I've discussed this solution with @korthout and this works fine but this solution is not ideal. When we encounter a record with a newer version than the broker the partition will become unhealthy. If enough partitions are unhealthy a quorum cannot be reached and downtime will be experienced.

If a record was created in version 1.3.0 it does **not** mean that a broker with version 1.2.0 is unable to correctly handle the event. This depends on whether or not processing this event on version 1.2.0 would result in a different state from when we process it in version 1.3.0. When it results in the same state there should be no problem to process the 1.3.0 event on a broker with version 1.2.0.
To make this possible we would need to know if there were impactful changes in the processing of this event. We could do this by introducing a version to the event. If the processing results in a new state, we should also increase the version number of the event. In this filter we could then compare the `RecordMetadata` for the version of the event at creation time to the currently known version of the same event. If the broker does not know this version yet, we should throw the exception, as there is no possible way we could handle it whilst maintaining the correct state.
This new event version would only be updated when there are changes in the event appliers, as this should be the only way for the same event to result in a different state.

This seems like a rather large change to make as part of this issue. @npepinpe Any advice on how to proceed with this?

**Comment by korthout** [comment]
Thanks @remcowesterhoud I'd like to make a small side note. The problem that would be resolved by these filters is only relevant to bug fixes or changes to existing event appliers that lead to different state for the same event. AFAIK, we've not yet had to make such changes.

**Comment by npepinpe** [comment]
It's possible that improving the experience here is bigger than just the version. For example, having an election process which favors newer nodes would help as well (assuming the newer node is not far behind when it comes to replicating).

Anyway, I don't think we'll manage to get anything in 1.3, and that's OK. We should still start on this sooner than later, as I would be fine with possibly backporting some mitigations (assuming the risk/complexity isn't too high). So introducing a per-event version might be a solution, but there's no need to rush this. Considering the holidays are coming up, I'm not sure you'll have time to do much here Remco, so I would not pick this up if I were you. If it's still there when you're back, then by all means go for it :smile: If somebody is to work on this now, it might make more sense that Nico does as he's available right now (assuming, again, that we can achieve something before you're off for the holidays).

**Comment by korthout** [comment]
I've written down by thoughts about this in a bit more detail. And I agree that changing the election process could help here, although it might not be able to completely resolve the problem. I see some other low-hanging fruit that we could try still in 1.3.0.

# Some thoughts
It seems we have 2 problems related to rolling updates:
1. the follower goes unhealthy when it processes/replays a record with a higher protocol version
2. the follower might arrive at a different state than a newer leader for the same event

These problems occur at different frequencies:
1. every time we change the schema and increase the protocol version (e.g. introduce a new value type, add a new property, create a new message)
2. only when we change the implementation of an event applier in a way that leads to different state than before

Let's focus first on problem 1, because it blocks much more.

## Problem 1

The follower goes unhealthy when it processes/replays a record with a higher protocol version
- why? we have the protocol version check as record filter that throws an exception
- why? the follower might not be able to parse a record with a higher protocol version and we want to fail early
- why? the leader can write records using a schema that is not yet known by the followers, however most record schemas are already known
- why? the leader could be on a higher version than the follower

So, I see 2 solutions:
1. favor lower versions as leaders in election
2. don't fail early on protocol version, as it does not reflect the ability of a follower to parse the record

What I think we can do quickly:
- drop the protocol version restriction and fail late by parsing in best-effort
- fail early using more specialized checks (e.g. do we already know this value type)

## Problem 2

The follower might arrive at a different state than a newer leader for the same event
- why? the leader might have a bugfix in the event applier that leads to a different state and the follower does not know this
- why? the leader could be on a higher version than the follower
- why? there is no way for the leader to communicate to the follower that the event was applied differently
- why? the only way to communicate this currently is the brokerVersion which does not tell an older broker that something was changed
- why? we lack a way to communicate changes in event application between brokers
- why? so far it was not considered and not implemented

Here again we could favor lower versions as leaders in election.

Other solution ideas:
- add an integer property (e.g. `behaviorVersion`) to records that represents differences in behavior for the same record but for different versions of the broker. It communicates from a leader (writing the record) to a follower what it assumes to do with this record and what it expects followers to do with it. The follower can compare this number with it's own configuration for this record and decide to fail early if it can't behave the same way. This integer would in reality only be increased for events, as commands never produce state changes
- use gossip to communicate changes in event application behavior between the brokers. By using gossip, all brokers would be aware that a new version of a broker will replay events differently. This gossip could be kept to a minimum by only sharing their knowledge on startup, or when they become leader. The information that is gossipped should contain specifically which events changed in the new version, because other events could still be replayed normally.

## Conclusions
In the short-term, I think that we can mitigate most of problem 1 by:
- dropping the protocol version restriction and failing late by parsing in best-effort
- failing early using more specialized checks (e.g. do we already know this value type)

In the longer term we should consider how to communicate changes in event application between brokers of different versions, and consider changing the election process to favor older brokers as leaders.

**Comment by remcowesterhoud** [comment]
@korthout Thanks for the clear breakdown!

_dropping the protocol version restriction and failing late by parsing in best-effort_
What would be the impact of this? At some point a follower will encounter a record that it won't be able to parse. What will it do when this occurs? Will it throw an exception and become unhealthy, much like if we fail early?

_However, it means that a bug would exist longer in the cluster._
Do we know how long it takes to update a broker? I feel like the impact of this would be negligible, but obviously I can't say for sure.



My personal preference would be to fail early. I think it makes more sense to catch events that we cannot process in a centralised place, instead of having them fail randomly at certain point where they can't get parsed. With a proper filter we can give clearer error messages in case the problem occurs.
