### ISSUE TITLE
Granular authorization of operations

### ISSUE THREAD

**Issue by jwulf** [camunda/zeebe#8358]
At the moment, with Camunda Cloud and Self-Managed with an appropriately configured proxy, a client is either authorized or not. Once authorized, a client can perform any operation via the Zeebe Gateway.

Some form of granular permissions would be useful. What might this look like, though? Issuing API credentials with a checklist of allowed gRPC operations associated with them?

Some form of wild card matching on some aspects of processes? (Payload variables?)

This issue is to collect feedback from the community about use-cases and desires for granular permissions authorization.

**Comment by npepinpe** [comment]
Doing per-operation authorization is already possible, just not supported out of the box. You can use [custom interceptors](https://docs.camunda.io/docs/self-managed/zeebe-deployment/interceptors/) (available since 1.2) in the gateway to authorize all incoming calls and reject them if the user is unauthorized. You have to manage the authentication and authorization yourself of course.

You can also go one step further and do resource authorization, but that requires you to keep track as well of the resources you create and map them to principals - at the end though, you can still use interceptors to authorize those calls based on your own custom logic.

**Comment by Zelldon** [comment]
As mentioned by @npepinpe this is already possible with the interceptors and I don't see us implementing something else in the near future, so I will close this for now. Feel free to reopen the issue.
