### ISSUE TITLE
Replication seems to favor specific nodes

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8566]
**Describe the bug**

During investigating https://github.com/camunda-cloud/zeebe/issues/8551 I observed that the Leader always prefers one node, which gets more append requests in a second than others. Or maybe one node can always handle more than the other ? :thinking:  This causes then the other node always need to get an install request to catch up #8565 Furthermore this also means (in a 3 node cluster) if this preferred node goes down it can cause a longer delay to continue the processing (the slower one need to catch up first so we can commit).

When looking at the medic benchmarks we can see that the Node 2 always gets more or can process more append requests.

![appendEntriesMedic](https://user-images.githubusercontent.com/2758593/148772264-5e03fd38-f0c4-46bd-a138-2973319e4186.png)

First assumption was that this might be related to the case that the other nodes are leader for other partitions, but I have seen the same with one partition.

![appendEntriesSinglePartition](https://user-images.githubusercontent.com/2758593/148772647-8f585f2c-e9b5-44c0-a2ad-7a1c238c6fe8.png)

My current assumption is that we always sent the requests in the same order, so we always implicitly prefer one node. Since one node is enough to commit an index (in our default 3 node setup), we can continue with the next appends and the other node is not able to catch up with the load. But this is just a rough guess :shrug: 

See for example  https://github.com/camunda-cloud/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java#L102-L104

**To Reproduce**

Run a normal benchmark.

**Expected behavior**

All nodes are able to handle the same load and are mostly at the same state so it doesn't matter which node fails and we not need to regularly sent install requests.

**Environment:**

 - Zeebe Version: 1.2.x, 1.3.0
 - Configuration:

**Comment by npepinpe** [comment]
We turned on priority election by default, so that's probably it? @oleschoenburg

**Comment by oleschoenburg** [comment]
Hm, I don't see how this would relate to priority election. If I understand correctly the issue here is about how we replicate to followers.

**Comment by npepinpe** [comment]
Sorry, I read it very fast and for some reason was thinking about the same nodes being elected always (which could still be sort of true if the leader always prefers one node, so that node will always have the second longest log and has a higher chance of becoming leader if an election occurs, I guess).

I think your hypothesis is plausible, and it should be easy to confirm it by just introducing some randomness when replicating an event (just shuffle the list of followers every time before). But I have a feeling you're correct, and it's just because we always append to remote nodes in the same order.

**Comment by oleschoenburg** [comment]
Just shuffling the order here: https://github.com/camunda-cloud/zeebe/blob/df871f9add0f7e22d69078fb465859e6509eb4fd/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java#L102-L104

seems to have no consistent effect: 
![Screenshot 2022-01-10 at 18-18-09 Zeebe - Grafana](https://user-images.githubusercontent.com/1379753/148809428-74bf7cf7-1cb0-42b0-a7fe-3a19c0895972.png)

**Comment by npepinpe** [comment]
The assumption is the impact is completely temporary, and the cluster will recover. This also would only impact the cluster if the fast(er) follower were to crash/shutdown, which is hopefully not very likely. Still, it would be good to understand/verify if this is a case where metrics are showing the wrong thing or if one follower is always faster. We should verify if the it's not that the faster follower is receiving more requests, but with less entries in them due to being slightly more up to date than the other follower. If that's the case, we can just close this. Otherwise, it would be good to understand the behavior of the system, and fix any issues if applicable.

**Comment by npepinpe** [comment]
I think our metrics nowadays show that both nodes are pretty much always up to date, so I would close this. Please reopen if we have any info that disagrees with this.
