### ISSUE TITLE
BPMN Termination Event

### ISSUE THREAD

**Issue by andrejpetras** [camunda/zeebe#8789]
**Is your feature request related to a problem? Please describe.**
Currently, the `Terminate EndEvent` is not supported by Zeebe, which block us to implements few BPMN patterns (or migrate) in the Zeebe.

**Describe the solution you'd like**
Support the BPMN `Terminate EndEvent` in Zeebe and Zeebe Modeler.

**Describe alternatives you've considered**
None

**Additional context**
None

I hope we can help somehow to push it forward.

**Comment by npepinpe** [comment]
Hi, there's currently no short-term plans to implement this due to lack of resources, mostly. Our big focus in the engine right now is DMN, and we most likely won't implement new symbols until the first version of DMN is integrated. I'll bring it up to our product team however, which might influence planning.

It would also help if you could elaborate a bit on the use cases/patterns which you cannot implement at the moment in Zeebe.

**Comment by saig0** [comment]
## Relevant parts from the BPMN 2.0 spec

![Pasted image 20220921061924](https://user-images.githubusercontent.com/4305769/191446972-9833bcc0-6d1e-4836-b025-72732c857321.png)

---

![Pasted image 20220921062031](https://user-images.githubusercontent.com/4305769/191446976-f6506217-f605-495a-871a-c8dece168552.png)

---

![Pasted image 20220921062102](https://user-images.githubusercontent.com/4305769/191446979-348676f3-73d5-4fb1-b65e-76913dfab055.png)

---

![Pasted image 20220921062219](https://user-images.githubusercontent.com/4305769/191446982-0422bcc6-e24a-4550-bffd-247e560b038d.png)

---

![Pasted image 20220921062347](https://user-images.githubusercontent.com/4305769/191446984-eb179dc2-e44e-467c-983b-2d41f9643f3e.png)
