### ISSUE TITLE
Windows Smoke Test is unstable

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9077]
**Summary**
windows smoke test fails sometimes.

E.g. in this PR it failed twice before succeeding

**Comment by npepinpe** [comment]
Could you link the PR in question or the actions run/logs?

**Comment by pihme** [comment]
:facepalm: (Must not get distracted) :see_no_evil:  

https://github.com/camunda/zeebe/pull/9068

**Comment by npepinpe** [comment]
This error message is produced by Netty due to a `ConnectException`, so most likely because we're too fast and the gateway port is not yet ready. The test will start when the Spring Boot shell is ready, but that doesn't guarantee the gRPC server is ready (even if it is 99% of the time I guess), since we don't really hook into the Spring lifecycle at the moment.

**Comment by npepinpe** [comment]
OK, some other things about this test: the assumption is that we return UNAVAILABLE when there are no known brokers. However, turns out this is incorrect - we return UNAVAILABLE when the topology was not computed, but we may also return an empty topology even if there are no brokers. 

I would propose (in a separate issue/PR) to align the behavior, so we either always return UNAVAILABLE when there are no known brokers, or an empty topology (even if there is no known or computed topology). I'm not sure which is better. For calls which require a partition (so almost all calls but topology), we return unavailable if there are no known leaders. But topology is a status call, so it might be useful to know that a topology is empty instead of getting an error? :thinking:

**Comment by npepinpe** [comment]
Anyway, the error is exactly what you get if you try to access a non open port, and looking at the logs you can see that the test fails very quickly, while it takes the gateway ~1s to start fully, so I think there's a slight race condition.
