### ISSUE TITLE
Understand consistency requirement of Tasklist

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9107]
* Understand the consistency requirement of tasklist data alone
* Understand the consistency between zeebe and tasklist data

This would help us if we can rely on elasticsearch snapshot, what should be coordinated between zeebe backups and tasklist backups

**Comment by sdorokhova** [comment]
With **importing**, we can apply all the reasoning from [Operate](https://github.com/camunda/zeebe/issues/9105) and [Optimize](https://github.com/camunda/zeebe/issues/9106) issues.

**Comment by sdorokhova** [comment]
**Task completion**

We perform task completion is such order:
1. send command to Zeebe
2. persist task completion in `task` index
3. persist variables in `task-variables` index
4. import data and update `completionTime` in `task` index.

Potential inconsistency between Zeebe data and Tasklist data:
1. take snapshot of Zeebe data
2. complete task (4 steps) on Tasklist side
3. take snapshot of `task` and `task-variable` indices.
After restore of such Zeebe and Tasklist backups, task will be still open in Zeebe, but will be considered as completed in Operate.

**Completed task variables** During task completion we store task variables snapshot at the moment of task completion (index `task-variable`), so that the users can see variable values, with which the task was completed. Possible inconsistency:
1. backup of index `task-variable` is created
5. Task is completed (command sent, completed job record is imported)
6. backup of `task` index
In such case it may happen, that task completion is recorded, but there are no variables stored.
