### ISSUE TITLE
Update metrics exporter for start process instance anywhere

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#9406]
The metrics exporter needs to distinguish between process instances started at the root start event and process instances started at other elements. This will allow us to see whether the feature is actively being used in Grafana.

Blocked by #9390 
Possibly blocked by #9397 and #9398 for testing

**Comment by pihme** [comment]
Linked to wrong PR

**Comment by pihme** [comment]
Not clear what to do here. 

Which existing metrics should be differentiated?
Which new metrics shall be added?

**Comment by saig0** [comment]
There are no existing metrics yet. We have a metric for root process instances (i.e. no child instance) here: https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/metrics/ProcessEngineMetrics.java#L16 But we can't use this metric to track the different creation types.

In order to differentiate the process instance creation, we need a new metric. My suggestion (with non-final names):
* name = `process_instance_operations_total`
* labels = `organizationId, action, partition`
* with action: {`creation_at_start_event`, `creation_at_given_element`}

If we make the metric a bit more generic then we could use it also to track the process instance modifications.

**Comment by pihme** [comment]
What about
>     * with action: {`creation_at_default_start_event`, `creation_at_given_element`}

I find {`creation_at_start_event`, `creation_at_given_element`} ambiguous, because the given element might also be a start event (in an event sub process or an embedded sub process)

**Comment by pihme** [comment]
### Decisions
* `MetricsExporter` vs. `ProcessEngineMetrics`: Metric will be added to `ProcessEngineMetrics`. This class lives in `engine` module and already has logic to differentiate between rood process executions and child process executions. `MetricsExporter` on the other hand lives in `broker` module and operates currently at a coarser level of detail
