### ISSUE TITLE
Reject ProcessInstanceCreation command targeting unsupported element

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#9408]
Some elements cannot be supported as the target element for the ProcessInstanceCreation command with start instructions. 

For example, the engine has currently no way to process the taking of a sequence flow as a command. Sequence flows are taken as part of the completion of another flow node by writing events for each taken sequence flow, and commands for each flow node targetted by the sequence flow. 

Next to the sequence flow, there are some other elements that currently do not support the `ACTIVATE_ELEMENT` command.

Lastly, the root start event should also not be allowed as the target element for the ProcessInstanceCreation command with start instructions. This might lead to subscribing to the timer/message events twice (once when creating the instance and once when completing the start event). It would also circumvent the usage of output mappings to change the variables before merging them into the process instance.

The `ProcessInstanceCreation` command should be rejected:
- when one of the target element ids refers directly to a ~root~ start event
- when one of the target element ids refers directly to a sequence flow
- when one of the target element ids refers directly to a boundary event
- when one of the target element ids refers directly to an event belonging to an event-based gateway

Blocked by https://github.com/camunda/zeebe/issues/9390

**Comment by saig0** [comment]
Extending the list of not supported elements by:
* all start events, also in embedded/event subprocesses (i.e. non-root start events)

The reason for the non-root start events is the same as for the root start event. The activation of the start event would try to open the event subscriptions a second time.  

In general, we don't want to support the activation of these elements for now because we don't want to change existing behavior or introduce special cases. This helps us to scope the implementation. We may add support for these elements later.

The following process shows which elements can be activated (green) and which elements are not supported (red). 

![c8-activate-element](https://user-images.githubusercontent.com/4305769/170254589-22656ff1-48e7-4069-8914-674c0ab7ca4d.png)

**Comment by skayliu** [comment]
> all start events, also in embedded/event subprocesses（except subprocess with boundary event）

Hi, @saig0 @korthout, Depending on the PR #10905, Issue #10904, I've implemented `CreateProcessInstance` with `start instructions` at all start events, except subprocess with boundary event.

If you think it's acceptable, I can continue work on `ProcessInstanceModification`

**Comment by korthout** [comment]
@skayliu Please hold off on this. It's unclear whether the team would accept such changes at this time. I'll reach out if this changes.

**Comment by korthout** [comment]
I've clarified the team's perspective on this functionality in more detail in [another comment](https://github.com/camunda/zeebe/issues/10904#issuecomment-1316792201). I'm linking it here for completeness.
