### ISSUE TITLE
Support logical transactions for command processing

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#9420]
We want to be able to reject the ProcessInstanceCreation command during certain circumstances, for example when the construction of the element scopes fails. When we reject the command, no changes should be made to the state. In addition, we may want to avoid writing events to the log stream that were created as part of the now rejected command.

To accommodate this, we should support logical transactions for our command processing.

- [x] We'll probably need to add an abstraction around transactions that includes rollback for a batch of records, state changes, and side-effects (or avoiding that those have happened until the transaction can be atomically committed).

  -> When an exception is thrown by a processor, the StreamProcessor rolls back the transaction. The `Engine` has a `onProcessingError` method which is then called with the failed command, the exception and a new ResultBuilder.

  - [ ] We need to pass the error to the corresponding processor so it handle it accordingly.

Please make sure to document how logical transactions work as part of this issue.

**Comment by Zelldon** [comment]
> To accommodate this, we should support logical transactions for our command processing.
> 
> We'll probably need to add an abstraction around transactions that includes rollback for a batch of records, state changes, and side-effects (or avoiding that those have happened until the transaction can be atomically committed).

Could you elaborate on this? What is the difference to our current transaction handling? Does this involve here now multiple commands ? Or why is our current approaches no longer possible? :thinking:

**Comment by korthout** [comment]
The part that may fail happens during applying the state changes for one of the events that is written during the command processing. When that fails, we may already have written other events before which have had effects on the state and exist on the log. We should be able to atomically apply multiple events and write them or not.

**Comment by Zelldon** [comment]
> Does that make sense?

Tbh, no. Because records are written to the dispatcher. If the processing succeeds we flush the dispatcher. But it can be also reseted

**Comment by korthout** [comment]
There are some differences. 

Currently, the ProcessingStateMachine's error handling will blacklist the related process instance, because the related command is a ProcessInstanceRelatedIntent. We also don't want to write an error event, we only need to reject the command.

Also, the side effects are not cleared when the transaction is rolled back.

Lastly, we need some abstraction to easily define this transaction and how it differs from an actual error.

**Comment by saig0** [comment]
The implementation is currently blocked by the [engine abstraction topic](https://docs.google.com/document/d/15udS3fChbU7ORcgESFr18XiMHTfBLNotMU5aG03NsVI/). 

In order to support logical transactions, we would need to change how the stream processor is working (e.g. give transaction control to the engine). This part will change with the engine abstraction and we assume that it will be easier afterward. 

As a workaround, we could throw an exception in the engine. As a result, the command is rejected and no change is written to the state. Small downside, we would also write an error record and would blacklist the process instance. Especially, for the process instance modification, this is not acceptable for the final release.

**Comment by pihme** [comment]
First draft in #9865 

Note that it is still possible to throw an exception. This will result in `Engine.onError(...)` being called, which also contains the logic whether blacklisting is supposed to happen. I just wanted to mention it, since I wasn't sure exactly what we need (i.e. a rollback and then do something else, or a different error handling and ways to determine whether blacklisting should happen or not)

**Comment by npepinpe** [comment]
I'm just curious, because I'm not sure I understand what this entails. Feel free to ignore this while you're busy, but can someone elaborate on what we mean here? Is it that we want to rollback to a previously processed command? As in, process command X, which writes a follow up command X+1, and when we process X+1 we go ups, let's rollback to X-1?

Or it's just about rollback while still processing X? I'm also confused; like Chris, I thought we were already doing that :sweat_smile: I didn't really get the comment [here](https://github.com/camunda/zeebe/issues/9420#issuecomment-1132674698) :crying_cat_face:

**Comment by npepinpe** [comment]
A little bit, but I don't know enough about the planned implementation of the process modification. Anyway, it's just curiosity :)

**Comment by Zelldon** [comment]
We discussed that today. This will be possible (or is already) with the onError handling (callback) implementation by the engine. The engine can decide whether to blacklist the instance or handle the upcoming error differently, like try out a new path. The on error will run in a separate transaction, so the previous changes are undone already.

**Comment by menski** [comment]
Next step would be to validate if the approach described above is functioning and solves this issue.

**Comment by korthout** [comment]
> Next step would be to validate the approach

I've played around with the idea and it works. https://github.com/camunda/zeebe/pull/9865#issuecomment-1206373983

> A processor can throw an exception. Then the stream processor will respond to this by rolling back the transaction, and **not** flushing the result builder. It then creates a new transaction and a new result builder and provides these to the engine. In the engine we then need to lookup the processor again and pass both the failed command and the throwable to it. The processor can then decide what to do depending on the passed command and throwable.

@Zelldon @pihme This makes me wonder whether we can further improve the `RecordProcessor.process` interface. Instead of us throwing an exception, or returning `ProcessingResult`. Would it be an idea to return `Either<Throwable, ProcessingResult>`. This could further clarify how the API expects to be informed of expected errors and differentiate them from unexpected errors (e.g. NPE).

**Comment by Zelldon** [comment]
Regarding the `Either<Throwable, ProcessingResult>` I guess the failure object doesn't need to be throwable then right? Could also be something else? 

Speaking from the StreamProcessor view it doesn't matter, both could be handled easily from this side. Still we would need to handle potential exceptions.

Speaking from the Engine side I guess it is a bit harder to come back to the actual processing method and return a failure since you have to pass it everywhere. Or do you still want to use exceptions internally? Then if you still use exceptions then I see no benefit in it.

> this could further clarify how the API expects to be informed of expected errors and differentiate them from unexpected errors (e.g. NPE).

If an NPE happens here you would want to blacklist again right? (as we did before) Your filters in the `onError` would catch that in my opinion.

So general answer yes we could do that, but not 100% sure what the benefit would be and how it would look like in the engine then.

**Comment by korthout** [comment]
>I guess the failure object doesn't need to be throwable then right? Could also be something else?

An Either is fully generic, so we can use whatever we want. Does the Streamprocessor have any special needs for the error handling? In that case the streamprocessor should decide what it looks like (e.g. throwable or some custom interface)

**Comment by korthout** [comment]
> Still we would need to handle potential exceptions.

Absolutely, unexpected errors can always pop up and the stream processor should be able to handle them

**Comment by Zelldon** [comment]
>  Does the Streamprocessor have any special needs for the error handling?

Not really. It would just roll the changes back, pass it to the RecordProcessor again and write all the results from the onError handling

> Absolutely, unexpected errors can always pop up and the stream processor should be able to handle them

This is then interesting, since I guess RecordProcessor also wants to handle them e.g. for blacklisting

**Comment by korthout** [comment]
>not 100% sure what the benefit would be and how it would look like in the engine then.

Let me know if you want to discuss F2F to form a better picture

**Comment by Zelldon** [comment]
I guess we can count this as further/later improvement and close this issue for now. But feel free to open an issue for the things you have proposed.

**Comment by korthout** [comment]
I'll leave this issue open. Yes it works with the current idea, but we still need to pass the error handling to to the individual processor.

**Comment by Zelldon** [comment]
Ah good point :+1: Ok :)

**Comment by korthout** [comment]
Nah, there are a few issues depending on this one. I've updated the issue description.
