### ISSUE TITLE
Catch error message/details on a boundary event

### ISSUE THREAD

**Issue by bhsdodo** [camunda/zeebe#9473]
**Is your feature request related to a problem? Please describe.**
Trying to capture the error message/description thrown by a worker within `ERROR BOUNDARY EVENT`.

For example I have the following workflow:
![image (4)](https://user-images.githubusercontent.com/56037024/171296868-38d288a9-dd87-4d32-b7b5-7238a53a4ba6.png)

All workers (Service 1 and 2) have same `errorCode` value defined in the Header:
![image (5)](https://user-images.githubusercontent.com/56037024/171296916-bf13ccd2-9f74-4755-b59b-36cc91719c50.png)

Therefore, if any exception happens, the worker will throw the error with that code and it will be handled by the Boundary Event:
![image (6)](https://user-images.githubusercontent.com/56037024/171296938-0ec69ccb-75c4-4fa9-be0d-ddcd93e97b37.png)

For workers, I am using the npm library with the following logic:
```
try {
  // do worker logic
  job.complete();
} catch (error) {
  const errorCode: string = job.customHeaders.errorCode;
  job.error(errorCode, error.message);
}
```
As you can see, the client library allow it to pass an optional error message as the second parameter. And that's the message I am trying to capture in the BPMN model after catching the error and using it on Service 3.

**Describe the solution you'd like**
I would like to receive that error message thrown by any Service inside that subprocess (1 or 2) as output variable and use it in the Service 3.

**Describe alternatives you've considered**
I thought one way of handling it by having multiple Error Boundary Events (each one with an unique errorCode). Then, I would be able to map those failures to know where it failed (in Service 1 or 2). However, I won't have specific details about the error (e.g. stack trace). Another problem with this approach is that I have multiple workers inside a subprocess. This is just a sample workflow. My workflows are much more complex than that and it would require many Boundary Events.

**Additional context**
I already seen #4337  and #4080 topics while investigating alternatives and I couldn't find what I am looking for.

**Comment by skayliu** [comment]
![image](https://user-images.githubusercontent.com/26370117/198682438-4006ad2c-23ce-4329-b53f-10b462faaa65.png)

**Comment by bhsdodo** [comment]
Thanks for the release. Will test it and let you know.

**Comment by korthout** [comment]
@saig0 Can you please clarify why you reopened this issue?

**Comment by saig0** [comment]
@korthout I added a comment about my reasoning here: https://github.com/camunda/zeebe/issues/4337#issuecomment-1330676763

**Comment by korthout** [comment]
Thanks, @saig0. I believe it makes sense to keep this issue open.

Looking at the difference between this issue, #4337 and #4080, I see them as follows:
- this issue: allows specifying an output mapping on the error boundary event to extract the error code and error message from the thrown error. For example, an output mapping like `source: '= error.code'; target: 'errCode'` would end up creating a process variable named `errCode` with as value the thrown error's error code. In this case, the error context is a property provided by Zeebe that hides other variables with the same name, similar to [multi-instance properties in the completion condition expression](https://docs.camunda.io/docs/next/components/modeler/bpmn/multi-instance/#completion-condition)
- #4337: allows specifying specific variable names for the `errorCode` and `errorMessage` in the process model (BPMN). The specified variables will be created with as values the error code and error message provided along with the thrown error, respectively. For example, `errorCodeVariable: 'errCode'` would end up creating a process variable named `errCode` with as value the thrown error's error code.
- #4080: allows passing along variables with the thrown error so that users can provide any details. This can be used as a workaround for both this issue and #4337.

@bhsdodo, please correct me if I made a mistake in my understanding of this issue.
