### ISSUE TITLE
How can the exporter export all the historical process instance data existing in the Zeebe process engine?

### ISSUE THREAD

**Issue by heerzhang** [camunda/zeebe#9607]
[problem]
 it is possible that some process instances stored in the Zeebe process engine cluster will be left behind, and the client has been unable to know the existence of these process instances, and the forgotten engine storage data cannot be automatically cleared.

I use Elastic exporter :  but ,Unable to export the internal historical process instance of Zeebe engine?

**Comment by oleschoenburg** [comment]
>I use Elastic exporter : but ,Unable to export the internal historical process instance of Zeebe engine?

That is correct, Zeebe can't retroactively export records since they are usually not available anymore. This is not something that we plan to change because Zeebe needs to compact the log occasionally so that it doesn't run out of disk.

> the client has been unable to know the existence of these process instances

Workers would still receive tasks, even for very old process instances. In that sense, process instances are never forgotten.

If you still need a way to inspect or list active process instances and don't have them exported somewhere, I believe your only options are debugging tools such as zdb.


In general questions such as this are better directed at our [forum](https://forum.camunda.io/) or [community slack](https://camunda-slack-invite.herokuapp.com/).
