### ISSUE TITLE
Use regular `StandaloneGateway` in `ClusteringRule`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9670]
**Description**

Currently, `ClusteringRule` has custom code to build and configure a Gateway. This can lead to drift between test and production code, as seen in https://github.com/camunda/zeebe/pull/9669 which would have been caught by tests if the `ClusteringRule` would just use the regular `StandaloneGateway`, for example like we do in the `StandaloneGatewaySecurityTest`.

**Comment by npepinpe** [comment]
I think first we would need to make sure all the Spring Boot stuff lives in the dist. I say this because since we have some Spring Boot magic living in gateway, broker, util, etc., I'm not sure we can manually configure our standalone apps properly without going through the Spring Boot lifecycle - and then, running multiple Spring Boot apps from the same JVM isn't easy I think.

Just a warning, maybe I'm wrong, and happy to be wrong :smile:

**Comment by npepinpe** [comment]
Sort of, I guess. It's reusing the same config as from dist. I think that's good enough for now :+1:

**Comment by deepthidevaki** [comment]
Then I think we can close this. Please reopen if you think otherwise.
