### ISSUE TITLE
Resource definition deletion task breakdown

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#9745]
Breakdown the resource definition deletion into tasks

**Comment by remcowesterhoud** [comment]
@korthout I can't really ask for a review in the proper way as I can't make a PR here, so I'll do it through this comment. Would you mind giving a review on the task breakdown for the resource deletion epic?

https://github.com/camunda/zeebe/issues/9576

**Comment by korthout** [comment]
@remcowesterhoud Sure, I'll have a look as soon as I can. I'll let you know when I've reviewed it

**Comment by korthout** [comment]
👏 Really nice work @remcowesterhoud 

Here are my thoughts, questions and feedback:

- https://github.com/camunda/zeebe/issues/9576

👍 I really like that you summarize the main concept in the epic and the diagram is very useful here.

> We need to make sure the deployment has already happened. Otherwise the delete could happen before the deployment, resulting in the version to still be deployed  

❓ Is this an issue in the proposed ordering of records? If so, do you have an idea how we can guarantee this? 

> What do we do with blacklisted instances? We cannot terminate these, do we just delete these?

🤔 That's a really good question. 

I see multiple potential solutions:
 - just delete them from the state on applying the `PROCESS` `DELETED` event. However, it's not that nice on the log because we ignore them. Is that reasonable for Apps consuming the exporter stream?
 - write `ELEMENT_TERMINATING` and `ELEMENT_TERMINATED` events for these element instances as well. This might cause problems because potentially this process instance is in a corrupted state where we can't fully apply these events. If we're able it would look better on the log.
 - introduce a new `RecordType`: `CORRECTION`. This record type is generally used in event-sourced systems to correct corrupted data from (previously) existing bugs. Blacklisted instances exist because of Error records, and so can be considered corrupted data that requires correction. This is probably a larger topic altogether, and I'm not sure we should introduce it for this use case, since we already have `PROCESS` `DELETED` event available. I just wanted to share my thoughts about this possibility. 

- https://github.com/camunda/zeebe/issues/9766

🔧 Please add the name of Intent enum to create 

- https://github.com/camunda/zeebe/issues/9768

🔧 Please add the name of intent enum to create

- https://github.com/camunda/zeebe/issues/9771

🔧 I think this applier should also delete the process from the cache (or do we do that somewhere else?)

>If deleted version is the latest version, store this in the state so a new deployment will not reuse this version.

🔧 Alternatively, we could keep track of this version for every new deployed resource and leave that counter alone when we delete the process (the same can work for deleted decisions/drgs)

- https://github.com/camunda/zeebe/issues/9785

>Could we send the `Process DELETED`, `DecisionRequirements DELETED` and `Decision DELETED` events here to reuse the code?

Yes, we can simply write these events with the state writer, but not in the `ResourceDeletion.DISTRIBUTED` applier. Writing records must happen in a command processor.

- https://github.com/camunda/zeebe/issues/9795

🔧 I think we need to do #9797 before #9795. Otherwise, in what code do we create an incident for the call activity.

🔧 Please consider the following: To be able to "retry" the call activity by resolving the incident, we'll either:
- need special logic in the incident resolved processor (it will see that the call acvitity is already activated and so it cannot determine what to do, see https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#incident)
- or need to put the call activity back in the ELEMENT_ACTIVATING state so the incident resolution can continue to activate the call activity once more.

- https://github.com/camunda/zeebe/issues/9800

❓ Rejection might seem to the user that nothing has happened. Should we reject the command if it was able to terminate some of the instances but not all? Should we then rollback everything? In that case this depends on: 
- https://github.com/camunda/zeebe/issues/9420

- https://github.com/camunda/zeebe/issues/9790

❓ Did we decide to only allow deletion by key? The EPIC description talks about specifying the resource and version. If you change this, please update the data in the related record issues.

**Comment by remcowesterhoud** [comment]
>> We need to make sure the deployment has already happened. Otherwise the delete could happen before the deployment, resulting in the version to still be deployed
>
>❓ Is this an issue in the proposed ordering of records? If so, do you have an idea how we can guarantee this?

I wrote this down as something to be aware of. I don't think it will be a problem as partition 1 will process the commands in order. So if it receives a deploy before a delete it will first make a call to the other partitions about the deploy, and after the call for the delete.

>> https://github.com/camunda/zeebe/issues/9766
>
>🔧 Please add the name of Intent enum to create
>
>>https://github.com/camunda/zeebe/issues/9768
>🔧 Please add the name of intent enum to create

I have separate issues for the intents which lists the names of the intents. 

>> https://github.com/camunda/zeebe/issues/9785
>>Could we send the Process DELETED, DecisionRequirements DELETED and Decision DELETED events here to reuse the code?
>
>Yes, we can simply write these events with the state writer, but not in the ResourceDeletion.DISTRIBUTED applier. Writing records must happen in a command processor.

So what you're saying is this should be done in the `DISTRIBUTE` command processor?

>>https://github.com/camunda/zeebe/issues/9795
>
>🔧 I think we need to do https://github.com/camunda/zeebe/issues/9797 before >https://github.com/camunda/zeebe/issues/9795. Otherwise, in what code do we create an incident for the call activity.

I don't think we do. We already have termination logic in place. My idea was to change this, allowing for termination of child instances in all cases, instead of just while deleting a resource.

> - need special logic in the incident resolved processor (it will see that the call acvitity is already activated and so it cannot determine what to do, see https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#incident)
> - or need to put the call activity back in the ELEMENT_ACTIVATING state so the incident resolution can continue to activate the call activity once more.

❓ Is there any way you would recommend? My current preference would be to modify the incident resolved processor and make an exceptional case for call activities.

>>https://github.com/camunda/zeebe/issues/9790
>
>❓ Did we decide to only allow deletion by key? The EPIC description talks about specifying the resource and version. If you change this, please update the data in the related record issues.

Honestly, I still don't know. I've asked and no one seemed to have a preference. I figure it makes sense to use the key as it is the identifier. We could always extend it later when we see it'd be a valuable addition.

**Comment by korthout** [comment]
> > > We need to make sure the deployment has already happened. Otherwise the delete could happen before the deployment, resulting in the version to still be deployed
> > 
> > ❓ Is this an issue in the proposed ordering of records? If so, do you have an idea how we can guarantee this?
> 
> I wrote this down as something to be aware of. I don't think it will be a problem as partition 1 will process the commands in order. So if it receives a deploy before a delete it will first make a call to the other partitions about the deploy, and after the call for the delete.

👍 That makes sense. 🔧 Please add a note about dealing with deleting an incomplete deployment distribution (still has pending deployments). I think all we need to do is delete the pending deployments.

> > > #9766
> > 
> > 
> > 🔧 Please add the name of Intent enum to create
> > > #9768
> > > 🔧 Please add the name of intent enum to create
> 
> I have separate issues for the intents which lists the names of the intents.
 
🔧 I meant to say the name of the intent enum, not the enum values. Could you add those? It's just to make it easier to complete that issue without having to look at the follow-up issue.

> > > #9785
> > > Could we send the Process DELETED, DecisionRequirements DELETED and Decision DELETED events here to reuse the code?
> > 
> > Yes, we can simply write these events with the state writer, but not in the ResourceDeletion.DISTRIBUTED applier. Writing records must happen in a command processor.
> 
> So what you're saying is this should be done in the `DISTRIBUTE` command processor?

👍 Yes, the ResourceDeletionDistributeProcessor should write these events.
 
> > > #9795
> > 
> > 🔧 I think we need to do #9797 before >#9795. Otherwise, in what code do we create an incident for the call activity.
> 
> I don't think we do. We already have termination logic in place. My idea was to change this, allowing for termination of child instances in all cases, instead of just while deleting a resource.

❌ We cannot reuse the termination logic, as this works asynchronously (i.e. it writes a `TERMINATE_ELEMENT` command for a process instance, which results in the element being set to `ELEMENT_TERMINATING` with the event and writing a `TERMINATE_ELEMENT` command for its children. Each command is then independently processed. The last child that terminates finally writes the `ELEMENT_TERMINATED` event for each parent recursively). We need to rely on the synchronous termination of the instances otherwise, we cannot reject the `DELETE` command and roll back the terminations.

> > * need special logic in the incident resolved processor (it will see that the call acvitity is already activated and so it cannot determine what to do, see https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#incident)
> > * or need to put the call activity back in the ELEMENT_ACTIVATING state so the incident resolution can continue to activate the call activity once more.
> 
> ❓ Is there any way you would recommend? My current preference would be to modify the incident resolved processor and make an exceptional case for call activities.

💭 It might be difficult to put the call activity back in the `ELEMENT_ACTIVATING` state:
- writing that event would cause a new element instance to be added to the state and so, which we don't want; and it would also be confusing to exporter consumers.
- we could do it in the `ELEMENT_TERMINATED` of the child `PROCESS`, but that's not so elegant.

👍 I agree that we can do this by modifying the resolve incident processor. If it's a call activity in the `ELEMENT_ACTIVATED` state then we can activate a new child instance. 

❓ Should this also [evaluate the input mappings again](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/CallActivityProcessor.java#L60-L63)? 🤔 We shouldn't subscribe it again to events, because it's already/still subscribed. What about the `processId` expression?
 
> > > #9790
> > 
> > ❓ Did we decide to only allow deletion by key? The EPIC description talks about specifying the resource and version. If you change this, please update the data in the related record issues.
> 
> Honestly, I still don't know. I've asked and no one seemed to have a preference. I figure it makes sense to use the key as it is the identifier. We could always extend it later when we see it'd be a valuable addition.

👍 Thanks, as long as Operate knows the key of the process I think we're good.
