### ISSUE TITLE
Actuators are cumbersome to maintain and extend

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9996]
**Description**

We have multiple open issues to extend or improve the actuators:
- https://github.com/camunda/zeebe/issues/9961
- https://github.com/camunda/zeebe/issues/9630
- https://github.com/camunda/zeebe/issues/9633

Implementing actuators can be very cumbersome due to the need for `SpringGatewayBridge` and `SpringBrokerBridge` which leads to code duplication (see `RebalancingService`).

There are other issues, for example the /rebalance actuator only works on a standalone gateway and on brokers with an embedded gateway. There's no technical reason it shouldn't work on standalone brokers without the embedded gateway, the only reason it doesn't work currently is that no one builds a `BrokerClient`.

I think we should spend some time to improve this. I've tried out a couple of approaches but they require a decent amount of refactoring.

My approach would be this: 

- [ ] Let the `dist` module be in charge of creating `Broker` , `Gateway` , `BrokerClient` , `AtomixCluster` and `ActorScheduler`. For `StandaloneGateway` we are doing most of that already but not for `StandaloneBroker`. 
- [ ] Actuators in `dist` have direct access to a `BrokerClient` because it can be injected by Spring, which removes the need for the spring bridges and code duplication.

related to https://github.com/camunda/zeebe/issues/8845

**Comment by npepinpe** [comment]
Semi related: https://github.com/camunda/zeebe/pull/10101

**Comment by npepinpe** [comment]
Should I take over here?

**Comment by npepinpe** [comment]
So looking into it, what I see is the following needs to be done to enable the broker client to be used in the broker actuator:

- [ ] the actor scheduler is created in the `dist` module at the `StandaloneBroker` level, and injected into the broker as is
- [ ] the Atomix cluster is created in the `dist` module at the `StandaloneBroker` level, and injected into the broker as is
- [ ] the broker client must be changed to accept a request timeout instead of the complete `GatewayCfg`; this will avoid having to pass around the embedded gateway config which may or may not be initialized, and decouple the client a little from the gateway in general

I'm a bit reticent to do more changes, as the final destination isn't clear to me. Where do we want to end up with this?

I have some ideas while I'm working on this which fit with what it's in our team vision document, and I'll expand on them after this is done (or during), but won't include much of this in this issue as we should focus on the hot backups first and foremost.

**Comment by npepinpe** [comment]
Working on the broker side, it's clear that doing this will introduce confusion between the broker and the standalone broker. Since we would now create some components outside of the `Broker` (and `broker` module), you would expect them to also not be configured by the broker, yet they are still configured via the `BrokerCfg`. Why is this an issue? Our test rules expect to configure everything in the broker via `BrokerCfg`, but now that you inject the cluster into the `Broker`, you have to either:

- Have some factory which can take a `BrokerCfg` and produce a cluster, living in the `broker` module which is used in production _only_ in the `dist` module, and in tests can be used by the rules we have
- Duplicate the cluster creation code, such that it lives both in the `dist` module and in the `broker` tests
- Move the configuration out of the `broker` module (which is what I would expect) and have the cluster services 100% injectable, with controlled implementations for the `broker` tests

The latter is the correct way, I think, but much more effort, and I'm not super keen on doing this right now due to time constraints :shrug:

**Comment by npepinpe** [comment]
God this second PR was painful...
